### ISSUE TITLE
[release] eventlet 0.38.1

### ISSUE THREAD

**Issue by itamarst** [eventlet/eventlet#1001]
Trying to get a fix into `oslo.log` (for supporting asyncio hub) that needs #994.

At minimum should probably get #1000 merged first though.

**Comment by 4383** [comment]
There is no new features, 2 fixes around threads, and a github action update. I propose a bugfix version (0.38.1).

List of commits:

- 548129bf Python 3.13: Use greenthread's dead state where possible (#1000)
- e647bd89 Update Actions (#996)
- ab617c84 Fix bug where asyncio hub didn't support multiple os threads (#995)

Global diff between 0.38.0 and master (the coming release 0.38.1):

https://github.com/eventlet/eventlet/compare/0.38.0..master

**Comment by 4383** [comment]
- Git tag: https://github.com/eventlet/eventlet/releases/tag/0.38.1
- Package: https://pypi.org/project/eventlet/0.38.1/

Thanks everyone!
