### ISSUE TITLE
eventlet monkey patching on python-xmpp got error.

### ISSUE THREAD

**Issue by netmaid** [eventlet/eventlet#124]
I'm using Ubuntu 14.04.1 LTS and installed ubuntu package recent version of python-xmpp.
And installed eventlet 0.15.1 using pip.

I've tried monkey patching on first line in my pushserver.py.
And later, try to connect xmpp server, then got error like below.
```
Traceback (most recent call last):
  File "pushserver.py", line 220, in <module>
    inst = PushServer()
  File "pushserver.py", line 55, in __init__
    self.init_gcm_push(max_gcm_conns, gcm_server, gcm_port, gcm_username, gcm_password)
  File "pushserver.py", line 68, in init_gcm_push
    if conn.connect(gcm_server, gcm_port, gcm_username, gcm_password):
  File "/home/ened/workspace/something/gcmpush.py", line 39, in connect
    self.client.connect(server=(self.SERVER, self.PORT), secure=1, use_srv=False)
  File "/usr/lib/python2.7/dist-packages/xmpp/client.py", line 200, in connect
    if not CommonClient.connect(self,server,proxy,secure,use_srv) or secure<>None and not secure: return self.connected
  File "/usr/lib/python2.7/dist-packages/xmpp/client.py", line 178, in connect
    transports.TLS().PlugIn(self,now=1)
  File "/usr/lib/python2.7/dist-packages/xmpp/transports.py", line 274, in PlugIn
    if now: return self._startSSL()
  File "/usr/lib/python2.7/dist-packages/xmpp/transports.py", line 309, in _startSSL
    tcpsock._sslIssuer = tcpsock._sslObj.issuer()
AttributeError: 'GreenSSLSocket' object has no attribute 'issuer'
```

I knew GreenSSLSocket inherit SSLSocket class in python system.
So, GreenSSLSocket maybe has issuer() function.
I'm digging more and more into the deep source.

Ref: https://launchpad.net/ubuntu/+source/python-xmpp

**Comment by blshkv** [comment]
there is a bug in xmppy lib. Here is the patch:
https://raw.githubusercontent.com/freebsd/freebsd-ports/master/net-im/py-xmpppy/files/patch-xmpp-transports.py

**Comment by tovmax** [comment]
Thank you very much for this patch, now it works!

**Comment by temoto** [comment]
@blshkv thank you.

**Comment by dnldd** [comment]
+1 for that patch @blshkv :)

**Comment by blshkv** [comment]
wow, didn't expect so many replays. Glad to help! Cheers

**Comment by rochacbruno** [comment]
:+1:  thanks @blshkv I am using your fork until the official is not updated.

**Comment by fradeve** [comment]
:+1: thanks @blshkv this has prevented me to be stuck on a thing I'm working on :dancer:

**Comment by TOANLAB** [comment]
@blshkv, using the patch will eliminate the errors however I am stuck in the authentication part know:

jid     =  xmpp.protocol.JID(username) 
jidpass = password
tojid   = xmpp.protocol.JID( touser)
cl  =  xmpp.Client(jid.getDomain(),debug=[])
cl.connect( ( 'jabber.no-sense.net', 5222 ) )
cl.auth( jid.getNode( ), jidpass ) #Failed 

The code above works fine for most cases however won't work with eventlet.

Any suggestion?

**Comment by blshkv** [comment]
sorry, no idea. I'm actually not using eventlet. 
Please open a new bug report and submit all details.
