### ISSUE TITLE
Modification time forward, the timer failure

### ISSUE THREAD

**Issue by ljz888666555** [eventlet/eventlet#132]
To take effect, for example, modify the local time forward one hour timer to wait one hour after

**Comment by haypo** [comment]
FYI I backported the PEP 418 to Python 2 using ctypes:
https://bitbucket.org/haypo/misc/src/tip/python/pep418.py

**Comment by temoto** [comment]
@haypo great, thank you.

**Comment by temoto** [comment]
Monotonic time patch was merged into master f92b49f77e073dad40a71858ef9149b543e07d67, should fix this issue.
