### ISSUE TITLE
'maximum recursion depth exceeded in GreenSocket.__del__

### ISSUE THREAD

**Issue by hardys** [eventlet/eventlet#137]
Since 8f98f8b I'm seeing the following error in the close path:

maximum recursion depth exceeded while calling a Python object' in bound method `GreenSocket.__del__` of `eventlet.greenio.GreenSocket` object

The problem may actually be in the previous commit da87716 as this seems to rework the close/delete path but I can't test that independently atm due to the coupling between the patches around updated select arguments.

I don't have a minimal reproducer yet, but this issue is observable on many openstack services when an RPC Heartbeat timeout happens:  https://bugs.launchpad.net/oslo.messaging/+bug/1369999

Prior to da87716 everything works fine, so it seems this may be a regression caused by one of these patches?

**Comment by hswayne77** [comment]
hi, everyone, I've met the same errors, my eventlet version is 0.15.2

anyone has some suggestions to resolve this issue ?  thks

May  4 11:34:42  Exception RuntimeError: 'maximum recursion depth exceeded' in <bound method GreenSocket.__del__ of <eventlet.greenio.GreenSocket object at 0x8fe7b10>> ignored
May  4 11:34:42  'maximum recursion depth exceeded' in <bound method GreenSocket.__del__ of <eventlet.greenio.GreenSocket object at 0x8fe7b10>> ignored

**Comment by temoto** [comment]
@hswayne77 update to latest version. Today 2015-05-04 it's `0.17.3`.
