### ISSUE TITLE
monkey patch leaves blocking methods in select

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#169]
Since we're asking to patch the module, if you're planning to leave poll() as an operation which blocks all of Python, I think it's best to have huge warnings on the monkey patcher that this will not work. I think the expectation of most users would be that this function is either patched or deleted.
For reference, gevent deals with this by deleting select.poll, select.epoll, select.kqueue and select.kevent.

CC from https://bitbucket.org/eventlet/eventlet/issue/167/monkey-patch-on-select-leaves-selectpoll

**Comment by jstasiak** [comment]
This is taken care of by https://github.com/eventlet/eventlet/commit/f63165c0e3c85699ebdb454878d1eaea13e90553 (it deletes the unpatched methods).
