### ISSUE TITLE
"Bad file descriptor" Error occuring when websocket is closed.

### ISSUE THREAD

**Issue by Mike-Baker** [eventlet/eventlet#171]
Hi,
As the title suggests I have been seeing errors like the one below in server logs when closing websockets.

```
Traceback (most recent call last):
  File "/ENV/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/ENV/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 671, in process_request
    proto.__init__(sock, address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/ENV/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 588, in finish
    greenio.shutdown_safe(self.connection)
  File "/ENV/local/lib/python2.7/site-packages/eventlet/greenio.py", line 673, in shutdown_safe
    return sock.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

This stack-trace appears on the server whenever a websocket connection is closed by the client (for example by navigating away from the page). I have not noticed any problems with the functionality of the sockets or the server other than these error messages.

I have run git-bisect on this issue and it says the commit which introduced this behaviour was introduced on commit 23beb7d43e3b80f0fa557ec80101d7e6f12621ff

```
git bisect start
# bad: [8931e9f794356f4d4772344b26dc09ae5e5e8f2f] tpool: Windows compatibility, fix ResourceWarning. Thanks to Victor Stinner
git bisect bad 8931e9f794356f4d4772344b26dc09ae5e5e8f2f
# good: [203e629212be5cf6e53d577734421d494b255754] PEP-8 fixes
git bisect good 203e629212be5cf6e53d577734421d494b255754
# good: [e7b08cf398acbf9560483ef5c3b4013328fbca76] Refactor capturing stderr into a context manager
git bisect good e7b08cf398acbf9560483ef5c3b4013328fbca76
# bad: [bce9cc334343ab97503088721bed30de87d40550] Give credits for 23beb7d
git bisect bad bce9cc334343ab97503088721bed30de87d40550
# good: [66c824c3552848dd822bbccc39f68f6c9250be6a] Improve Python 3 compat: WSGI tests
git bisect good 66c824c3552848dd822bbccc39f68f6c9250be6a
# good: [3870f6b055dd91179bdac670ee417ef74b2a4ed3] wsgi: Add send_hundred_continue_response() API to the docs
git bisect good 3870f6b055dd91179bdac670ee417ef74b2a4ed3
# bad: [a70b4ba4839a6ba94238a474ba1f471d4b878b67] pep8: trivial fixes
git bisect bad a70b4ba4839a6ba94238a474ba1f471d4b878b67
```

Specifically the changes in this commit which seem to have triggered this behaviour are in eventlet/wsgi.py and relate to the "Input" class. (Determined by rolling back the changes only in that file and testing)

If it happens to make a difference the websockets which I have observed this behaviour on are handled by _handle_hybi_request in /eventlet/websocket.py

If there is any information I am missing then please let me know so I can attach it to this issue.

Kind regards
Mike

**Comment by davidszotten** [comment]
hi. also running into this. did you find any more information on this?

**Comment by temoto** [comment]
@Mike-Baker David's fix is merged into master, could you try it? Please reopen if the issue still exist.

**Comment by Mike-Baker** [comment]
Works perfectly here now, thank you very much.
