### ISSUE TITLE
Pip and tar files are inconsistent for 0.16.0

### ISSUE THREAD

**Issue by jrosenboom** [eventlet/eventlet#186]
The pip install still includes files like util.py which should have been removed in the corresponding source package. This makes it quite difficult to debug issues arising due to other programs still using these modules.

This is for

https://pypi.python.org/packages/2.7/e/eventlet/eventlet-0.16.0-py2.py3-none-any.whl#md5=eb80b1a1816b3538e2d07a6b6aace4f8

vs.

https://pypi.python.org/packages/source/e/eventlet/eventlet-0.16.0.tar.gz#md5=cd3e282d8d014e68f4118f8bc0ebd8cb

**Comment by haypo** [comment]
I confirm.

Tarball doesn't have the eventlet.util  module:

```
(BLA)haypo@smithers$ pip install --no-use-wheel eventlet && python -c 'import eventlet.util; print(eventlet)'
Downloading/unpacking eventlet
  Downloading eventlet-0.16.0.tar.gz (268kB): 268kB downloaded
(...)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named util
```

Wheel package has the module:

```
(BLA)haypo@smithers$ pip install eventlet && python -c 'import eventlet.util; print(eventlet)'
Downloading/unpacking eventlet
  Downloading eventlet-0.16.0-py2.py3-none-any.whl (152kB): 152kB downloaded
(...)
<module 'eventlet' from '/home/haypo/BLA/lib/python2.7/site-packages/eventlet/__init__.pyc'>
```

**Comment by temoto** [comment]
Thanks.

**Comment by haypo** [comment]
I suggest to release a version 0.16.1 where the only change is the version number. Wheel files may be cached, publishing a new 0.16.0 file with different content may not fix the issue.

**Comment by tsg-** [comment]
Did we decide on what we are going to do here?  Cut a 0.16.1 release?

**Comment by temoto** [comment]
Guys I just uploaded v0.16.1.
I don't know exactly how this happened, maybe should always remove build, dist, .egg-info directories. I double checked new package does not contain zombie module.

Thank you for report and reminder.
