### ISSUE TITLE
tests/manual installed

### ISSUE THREAD

**Issue by Arfrever** [eventlet/eventlet#190]
`setup.py` has `packages=find_packages(exclude=['tests', 'benchmarks'])`. This does not disable installation of subpackages, so installation of eventlet creates `/usr/lib/pythonX.Y/site-packages/tests/manual`.

Fix:
```
--- setup.py
+++ setup.py
@@ -11,7 +11,7 @@
     author='Linden Lab',
     author_email='eventletdev@lists.secondlife.com',
     url='http://eventlet.net',
-    packages=find_packages(exclude=['tests', 'benchmarks']),
+    packages=find_packages(exclude=['tests', 'tests.*', 'benchmarks']),
     install_requires=(
         'greenlet >= 0.3',
     ),
```

**Comment by temoto** [comment]
Thank you, fixed in ee9bcc36be28c7be57b8380e508bc75f96e5c459, will do bugfix release 0.17.2 soon.
