### ISSUE TITLE
Python 3: `Bad file descriptor` error on green subprocess.Popen.stdin.close

### ISSUE THREAD

**Issue by vikt0rs** [eventlet/eventlet#204]
I got the ``OSError: [Errno 9] Bad file descriptor``when I tried to run the following code [1]. See full traceback at [2]

[1] http://paste.openstack.org/show/181120/
[2] http://paste.openstack.org/show/181124/

**Comment by vikt0rs** [comment]
btw, the following code [1] fixes this issue, but I'm not sure, that this is totally correct. @jstasiak @temoto - can you please look there.

[1] http://paste.openstack.org/show/181126/

**Comment by temoto** [comment]
I think at the very least it needs OSError errno check to hide only this particular exception. Will post more info later.

Convenience copy-paste:
test
```
import eventlet; eventlet.monkey_patch(os=False)
from eventlet.green import subprocess

import signal

obj = subprocess.Popen(
    ['ls'],
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    close_fds=True,
    shell=False,
    cwd=None,
    env=None)

result = obj.communicate(None)
obj.stdin.close()

print(result)
```

traceback
```
Traceback (most recent call last):
  File "close_err.py", line 17, in <module>
    obj.stdin.close()
  File "/home/viktors/sandbox/.tox/py34/lib/python3.4/site-packages/eventlet/greenio/py3.py", line 130, in close
    _original_os.close(self._fileno)
OSError: [Errno 9] Bad file descriptor
```

patch
```
diff --git a/eventlet/greenio/py3.py b/eventlet/greenio/py3.py
index e41663a..6deb392 100644
--- a/eventlet/greenio/py3.py
+++ b/eventlet/greenio/py3.py
@@ -126,7 +126,11 @@ class GreenFileIO(_OriginalIOBase):
                     trampoline(self, write=True)
 
     def close(self):
-        _original_os.close(self._fileno)
+        try:
+            _original_os.close(self._fileno)
+        except OSError:
+            # probably, file already closed
+            pass
```

**Comment by temoto** [comment]
@jstasiak emerge. You may possess the wisdom on this one.
```
# eventlet/green/subprocess.py
class Popen(...):
  def __init__(...):
    # ...
                if pipe is not None and not type(pipe) == greenio.GreenPipe:
```
`GreenPipe` is now a function in `greenio/py3.py` so that type check couldn't work. I can't invent the proper fix right now, too tired. Do you have anything in mind?

**Comment by jstasiak** [comment]
@temoto Is this code responsible for this bug? Looks tricky but I'll have a look later today

**Comment by temoto** [comment]
@jstasiak I'm not sure it's responsible, but looks related and looks Python3-broken anyway.

**Comment by jstasiak** [comment]
I took a quick look but didn't come up with a solution right away, unfortunately I don't have much time to spend on it at the moment.

**Comment by temoto** [comment]
@vikt0rs please close this issue only if you have no problem with recent master.

**Comment by vikt0rs** [comment]
@temoto - I've run tests with the recent master and do not observe this issue anymore
