### ISSUE TITLE
Correct way to import urllib? import error since 0.17

### ISSUE THREAD

**Issue by bitnumus** [eventlet/eventlet#205]
I'm getting an ImportError on "urlopen" since the upgrade to 0.17. What has changed?

I've tried various imports looking at urllib docs this should work?

`from eventlet.green.urllib import request`

Using python 3

**Comment by temoto** [comment]
```
% uname -a
Linux temoto-mobi 3.18.2-2-ARCH #1 SMP PREEMPT Fri Jan 9 07:37:51 CET 2015 x86_64 GNU/Linux

% venv-34/bin/python                      
Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from eventlet.green.urllib import request
>>>
```
What is different in your environment?

**Comment by vikt0rs** [comment]
Seems to be, that @bitnumus trying to run this example - [1] with python3 

[1] - http://eventlet.net/doc/examples.html#web-crawler

**Comment by bitnumus** [comment]
@temoto Apologies, it seems PyCharm didn't pick it up but it does in fact work. Sorry!
