### ISSUE TITLE
mysql warning

### ISSUE THREAD

**Issue by imazor** [eventlet/eventlet#216]
Hi,

I am using evenlet with mysql and getting the following mesage:
/usr/local/lib/python2.7/dist-packages/eventlet/tpool.py:80: Warning: Table './sandbox/pusher_log' is marked as crashed and last (automatic?) repair failed
  rv = meth(*args, **kwargs)

any ideas?

**Comment by temoto** [comment]
Hello.

That means you have a broken table in mysql. It has nothing to do with eventlet, you'd get the very same error using command line mysql client or any other. Try this for fix: http://stackoverflow.com/questions/8843776/mysql-table-is-marked-as-crashed-and-last-automatic-repair-failed
