### ISSUE TITLE
Backport fix for #137 to v0.15.2?

### ISSUE THREAD

**Issue by mcsaucy** [eventlet/eventlet#220]
#137 appears to fix issues I'm seeing in v0.15.2. A major user of eventlet has this issue (Openstack) and it can't update eventlet past v0.15.2.
This appears to be fixed with cb5ae33ca164b050498a346da8b0fd99bf801dab and 47b85e19b5a1ee3af44d515d26692b3ff7a80fd3. The tests for the latter commit rely upon larger, over-arching changes to the testing infra. As such, I've created be4ca3a8490b72be35a941a4ea2b8ee751e44fcf to use the testing infra that existed in v0.15.2, which is to say I just ripped out capture_stderr's logic and dropped it into the test itself.

Would it be possible to get these patches backported to v0.15.2 and possibly do a v0.15.3 with this patch?

Thank you.

**Comment by temoto** [comment]
I don't see how backporting would help, considering Openstack can't update eventlet past v0.15.2?

Why can't they update it? Fixing that issue would bring many other good news as well.

**Comment by mcsaucy** [comment]
Thanks for the reply. I ended up digging a little deeper into why Openstack can't update Eventlet. It seems v0.16 removed deprecated code that chunks of Nova rely upon (namely, event.util), so locking requirements to Eventlet v0.15.2 was applied as a temporary fix. The commits I mentioned originally cover the fixes required for #137, but none of the Openstack-breaking changes that went into v0.16.

It looks like folks have been gutting the calls to deprecated code to allow use of the current release of Eventlet, which I agree is the ideal solution.

**Comment by temoto** [comment]
Ah yes, the `eventlet.util` removal. Who knew somebody actually used it! I'll try to announce our API compatibility changes better next time.

So there's no need in backport after all? I read they've done `patcher.original('socket')` in mid January this year, some 2 months ago.

**Comment by mcsaucy** [comment]
You appear to be correct. Seeing as #137 fixed my original issue and I'm now running a version greater than 0.15.2, I think we're set. Thanks!
