### ISSUE TITLE
threading.Threading.join() broken in Python 3.4 with monkey-patching

### ISSUE THREAD

**Issue by haypo** [eventlet/eventlet#223]
Hi,

threading.Threading.join() doesn't work in Python 3.4 with monkey-patching. It's related to the new "thread-state lock" introduced in Python 3.4:
https://hg.python.org/cpython/rev/d52b68edbca6
https://bugs.python.org/issue18808

This lock is related internally when the C thread exits. So it doesn't work well with monkey-patching.

My pull request #187 fixed threading.Condition, but it also tried to handle this new lock by setting it to None.

**Comment by haypo** [comment]
I wrote a fix in pull #224. With this fix, tests of the Oslo Messaging project now pass on python 3.4 with eventlet and monkey-patching!

And if my pull request is merged, would it possible to prepare a new release? It would allow me to port more OpenStack projects to python3! Eventlet is blocking more than 10 projects because it doesn't work well on python 3. It looks like this issue is the last known eventlet issue with monkey-patching on Python 3.

**Comment by temoto** [comment]
Congratulations with Oslo/Py3.4! I'll bake 0.17.3 bugfix some time soon. And thanks for letting me know of blockers, I was going to communicate with somebody from OpenStack team to know if there are any eventlet blockers for you guys.
