### ISSUE TITLE
WSGI server incorrectly logs socket address if it's UNIX, not INET

### ISSUE THREAD

**Issue by booxter** [eventlet/eventlet#235]
If I pass a socket that is of AF_UNIX type with file path of /var/tmp/socket, then I get the following in my logs:

wsgi starting up on http:///:v/

This is because wsgi server assumes that the socket is not local, by constructing host and port as:

port = sock.getsockname()[:2]

And since (quoting python docs), "A single string is used for the AF_UNIX address family.", the split attempt ends up messed.

**Comment by mangelajo** [comment]
I can confirm this bug:

2015-06-02 06:01:04.855 19623 INFO eventlet.wsgi.server [-] (19623) wsgi starting up on http:///:v/

In different places of openstack-neutron where we start wsgi servers with unix domain sockets.

**Comment by booxter** [comment]
I've uploaded a fix for the start just to give a grasp of the expected fix. It probably needs some unit tests, so I don't assume it will be merged as-is; but I failed to run eventlet test suite successfully, so I will allow someone else to complete the work.

**Comment by temoto** [comment]
Thanks for bug report and fix!

I'm interested what was the difficulty in running test suite? Should be a simple `tox` run, or `tox -e py27-selects` if you want to test particular environment.

**Comment by booxter** [comment]
@temoto sorry, that was my patch fault. :) I've updated the repo with the fix, tests should pass now.

**Comment by booxter** [comment]
There was a bug in the patch itself. I've updated the repo and added a unit test. Hopefully this is it.

**Comment by temoto** [comment]
Some info for level up. Don't worry about fixing it.

```
>>> s4.type  # ipv4
<SocketKind.SOCK_STREAM: 1>
>>> su.type  # unix
<SocketKind.SOCK_STREAM: 1>
>>> socket.AF_INET
<AddressFamily.AF_INET: 2>
>>> socket.AF_UNIX
<AddressFamily.AF_UNIX: 1>
```

**Comment by booxter** [comment]
Yeah, .type -> .family is handled in the latest version.

**Comment by temoto** [comment]
@booxter 3ba7b02dfacb00e51dcad8097c3854f51c2b7d71 does it look fine for you?

**Comment by booxter** [comment]
@temoto +1. That's a lot better than mine. :)

**Comment by temoto** [comment]
It's merged in master. Thank you.
