### ISSUE TITLE
eventlet.green.OpenSSL is not compatible with Python 3

### ISSUE THREAD

**Issue by haypo** [eventlet/eventlet#238]
Example:

```
>>> import eventlet.green.OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haypo/prog/openstack/eventlet/eventlet/green/OpenSSL/__init__.py", line 1, in <module>
    import rand
ImportError: No module named 'rand'
```

**Comment by haypo** [comment]
The following pull request fixes this issue: https://github.com/eventlet/eventlet/pull/237

**Comment by temoto** [comment]
Your fix is merged into master e9f19c6df4a6e97a36a974338196a5a0bda079e4
Thanks!

**Comment by haypo** [comment]
Can you please notify me when a new version of eventlet including this fix is released? There is no urgency. It's to port OpenStack Cinder to Python 3.

**Comment by anthraxx** [comment]
@temoto  would appreciate a new release, had to backport this (and the mswindows attribute) patch... would be awesome to have a new release :stuck_out_tongue:
