### ISSUE TITLE
GreenSocket.send broken if socket has a timeout set

### ISSUE THREAD

**Issue by jstasiak** [eventlet/eventlet#260]
This is the code right now:

```python
    def send(self, data, flags=0):
        fd = self.fd
        if self.act_non_blocking:
            return fd.send(data, flags)

        # blocking socket behavior - sends all, blocks if the buffer is full
        total_sent = 0
        len_data = len(data)
        while 1:
            try:
                total_sent += fd.send(data[total_sent:], flags)
            except socket.error as e:
                eno = get_errno(e)
                if eno == errno.ENOTCONN or eno not in SOCKET_BLOCKING:
                    raise

            if total_sent == len_data:
                break

            try:
                self._trampoline(self.fd, write=True, timeout=self.gettimeout(),
                                 timeout_exc=socket.timeout("timed out"))
            except IOClosed:
                raise socket.error(errno.ECONNRESET, 'Connection closed by another thread')

        return total_sent
```

If a socket has a non-zero timeout set then it's not considered a non-blocking socket (``self.act_non_blocking`` is ``False``) and the blocking socket behavior path is chosen. Then, ``fd.send()`` and ``self._trampoline()`` are called in a loop and it may happen (happened to us) that ``self._trampoline()`` raises a ``socket.timeout`` error after some ``fd.send()`` call(s) already succeeded.

The client code (code calling ``GreenSocket.send``, either explicitly or because of a monkey patching) sees ``socket.timeout`` and is very likely to assume that no data has been sent and then retry sending everything (following the https://docs.python.org/3.5/library/socket.html#socket.socket.send interface and behavior).

The easiest fix would be change ``total_sent += fd.send(data[total_sent:], flags)`` to ``return fd.send(data[total_sent:], flags)`` but on the other hand it's not impossible that some people depend on ``GreenSocket``'s ``send`` having ``sendall``-like behavior.

What else could we do here? Have different paths for sockets with timeout set and with ones without a timeout?

pinging @temoto

**Comment by jstasiak** [comment]
This is what I believe to be the most reasonable solution to this (this would need a backwards (in)compatibility note in the changelog and an appropriate package version bump):

(I made this quickly without testing, may've missed something)

```diff
diff --git a/eventlet/greenio/base.py b/eventlet/greenio/base.py
index 18799af..8718df5 100644
--- a/eventlet/greenio/base.py
+++ b/eventlet/greenio/base.py
@@ -351,27 +351,17 @@ class GreenSocket(object):
         if self.act_non_blocking:
             return fd.send(data, flags)
 
-        # blocking socket behavior - sends all, blocks if the buffer is full
-        total_sent = 0
-        len_data = len(data)
-        while 1:
-            try:
-                total_sent += fd.send(data[total_sent:], flags)
-            except socket.error as e:
-                eno = get_errno(e)
-                if eno == errno.ENOTCONN or eno not in SOCKET_BLOCKING:
-                    raise
-
-            if total_sent == len_data:
-                break
-
-            try:
-                self._trampoline(self.fd, write=True, timeout=self.gettimeout(),
-                                 timeout_exc=socket.timeout("timed out"))
-            except IOClosed:
-                raise socket.error(errno.ECONNRESET, 'Connection closed by another thread')
-
-        return total_sent
+        try:
+            self._trampoline(self.fd, write=True, timeout=self.gettimeout(),
+                             timeout_exc=socket.timeout("timed out"))
+        except IOClosed:
+            raise socket.error(errno.ECONNRESET, 'Connection closed by another thread')
+        try:
+            return fd.send(data, flags)
+        except socket.error as e:
+            eno = get_errno(e)
+            if eno == errno.ENOTCONN or eno not in SOCKET_BLOCKING:
+                raise
 ```

I don't know at the moment how to produce a test case for this though.

**Comment by jstasiak** [comment]
@temoto I believe this is a serious issue as it breaks the ``socket.send`` contract, what's your position on this?

**Comment by temoto** [comment]
My position is: the simpler the code the better, `send()` is not supposed to act like `sendall()`, so if you depend on that and your code breaks, that's fine by me... except that I've recently merged the opposite behavior change to `GreenFileIO` #248 https://github.com/eventlet/eventlet/commit/e3f88347d96f653d65f66a46b6bda618a6cb129d

This `while 1` loop was added by @eugeneoden in 495939982bfebf856332f36c0d8a04ce89d4b889 while fixing (what now looks like an irrelevant to this issue) https://bitbucket.org/eventlet/eventlet/issues/38

I couldn't understand why the loop was added. Your code looks fine except I'm against unconditional trampoline before `fd.send`. We only need trampoline in case of `EAGAIN`.

**Comment by temoto** [comment]
And yes, it's a serious issue, thanks for bumping.

**Comment by jstasiak** [comment]
@temoto I figured the unconditional trampoline would be undesirable, see this patch without it below.

Additionally I just blindly copied and pasted the try/except block around fd.send - the only purpose it serves in that patch is it can silence some types of exceptions which doesn't make sense at the end of the function there. Anyway, modified patch below:

```diff
diff --git a/eventlet/greenio/base.py b/eventlet/greenio/base.py
index 18799af..8718df5 100644
--- a/eventlet/greenio/base.py
+++ b/eventlet/greenio/base.py
@@ -351,27 +351,17 @@ class GreenSocket(object):
         if self.act_non_blocking:
             return fd.send(data, flags)
 
-        # blocking socket behavior - sends all, blocks if the buffer is full
-        total_sent = 0
-        len_data = len(data)
-        while 1:
-            try:
-                total_sent += fd.send(data[total_sent:], flags)
-            except socket.error as e:
-                eno = get_errno(e)
-                if eno == errno.ENOTCONN or eno not in SOCKET_BLOCKING:
-                    raise
-
-            if total_sent == len_data:
-                break
-
-            try:
-                self._trampoline(self.fd, write=True, timeout=self.gettimeout(),
-                                 timeout_exc=socket.timeout("timed out"))
-            except IOClosed:
-                raise socket.error(errno.ECONNRESET, 'Connection closed by another thread')
-
-        return total_sent
+        while True:
+            try:
+                return fd.send(data, flags)
+            except socket.error as e:
+                eno = get_errno(e)
+                if eno == errno.ENOTCONN or eno not in SOCKET_BLOCKING:
+                    raise
+            try:
+                self._trampoline(self.fd, write=True, timeout=self.gettimeout(),
+                                 timeout_exc=socket.timeout("timed out"))
+            except IOClosed:
+                raise socket.error(errno.ECONNRESET, 'Connection closed by another thread')
 ```

I kept the "while True: perform io, trampoline if needed" pattern I see in some other methods.

Side note: the timeout semantics may be off with a loop like this if trampoline is called more than once (the effective timeout for the ``send`` call could be more than ``self.gettimeout()``, there's a similar misfeature fixed in Python 3.5's ``socket.sendall``: https://docs.python.org/dev/library/socket.html#socket.socket.sendall)

**Comment by jstasiak** [comment]
PS. @temoto can you see the GreenFileIO change (#248 e3f8834) potentially breaking anything? I'm not sure I fully understand its implications.

**Comment by temoto** [comment]
Thanks. GreenFileIO forced sendall semantics will not break anything, that's the reason why I merged it. It just does more job than expected and misleading and just sucks to have two sendall methods with different names. Especially so if that was made in backward compatibility trap situation.

**Comment by temoto** [comment]
This is how to fix total timeout thing:
```
timeout_left = self.gettimeout()
while True:
  t1 = time.time()
  try:
    return fd.send()...
  send_time = time.time() - t1
  if timeout_left is not None:
    timeout_left -= send_time
  try:
    self._trampoline(... timeout=timeout_left)
```

**Comment by jstasiak** [comment]
@temoto Will 719e987c0de7f3c69f5b0fa6e51a65beba1068b8 (socket-send branch) work? Feel free to merge if so, or I can do it.

The timeout calculation will need to be bit more complicated I think, the trampolining time needs to be included in it from what I see .

**Comment by temoto** [comment]
I'd like to ask you to run this branch before merging for as long as it needs before you feel confident it's good.

**Comment by temoto** [comment]
And yes, trampolining time needs to be also excluded, thanks.

**Comment by jstasiak** [comment]
Sure, I'll do some testing.

**Comment by jstasiak** [comment]
After a week of testing the patch seems fine - just merged into master.

**Comment by temoto** [comment]
Thank you very much.

**Comment by jstasiak** [comment]
I'll reopen this because I reverted the original commit[1]. @temoto what do you think about this test?

```
======================================================================
FAIL: test_multiple_readers (tests.greenio_test.TestGreenIoLong)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/eventlet/eventlet/tests/__init__.py", line 71, in wrapped
    return func(*a, **kw)
  File "/home/travis/build/eventlet/eventlet/tests/greenio_test.py", line 836, in test_multiple_readers
    assert len(results2) > 0
AssertionError
```

I can rarely and unreliably reproduce this locally. I suspect the failure happens because the new ``send`` implementation doesn't call ``trampoline`` on every retry so that the second reader thread doesn't have chance to run; that whole test doesn't inspire confidence in me.

[1] https://github.com/eventlet/eventlet/commit/3ae710e70ecb3683f83b9829011de01b5d3e0bf4

**Comment by jstasiak** [comment]
I produced a change to the test code that makes it pass now: https://github.com/eventlet/eventlet/commit/c315ee86dac996ac533b738f7c8777f4d01a0472 (it's in master)

**Comment by temoto** [comment]
:+1: thank you.
