### ISSUE TITLE
WSGI server shouldn't read all request body file when the connection is marked to be closed.

### ISSUE THREAD

**Issue by mouadino** [eventlet/eventlet#27]
Hi,

Please allow me to start with some historical fact before.

While working on a [bug fix](https://bugs.launchpad.net/python-glanceclient/+bug/1171241) for an OpenStack project (Glance) which use eventlet wsgi server as a backend server, i stumble upon a strange behavior from eventlet.wsgi server.

In our case we have a client that use chunked body transfert to upload a file to the server like so:

    conn = httplib.HTTPConnection(...)
    conn.putrequest(method, conn_url)
    ...
    while chunk:
        conn.send('%x\r\n%s\r\n' % (len(chunk), chunk))

Now the problem is that the server may raise an error while the file is being uploaded, but this will not stop the client of sending more and more until all the file is sent to the serve, which is not what i was expecting specially if i send a Connection: close header with my request, which i presume (please correct me if i am wrong) should advice the server to close connection when a response is sent back (per HTTP standard, please see the end of this bug report).

So after a bit of investigation in the eventet/wsgi.py code, i was able to found the [2 line of code](https://github.com/eventlet/eventlet/blob/master/eventlet/wsgi.py#L431) which are responsible for this behavior:

    while self.environ['eventlet.input'].read(MINIMUM_CHUNK_SIZE):
        pass

Which will ask the client in our case to upload more and more chunks while the server will throw them away, so what i am proposing is the follow:

    while self.environ['eventlet.input'].read(MINIMUM_CHUNK_SIZE) and not  self.close_connection:
        pass

So i am not sure if this is a correct fix neither the impact of this on other codes neither why do you need to read all the request body in the first place !?, but as far as i could understood this is what [HTTP standard](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) recommend to do in cases like this:

> HTTP/1.1 defines the "close" connection option for the sender to signal that the connection will be closed after completion of the response. For example,
>
>       Connection: close
> in either the request or the response header fields indicates that the connection SHOULD 
> NOT be considered `persistent' (section 8.1) after the current request/response is 
> complete.

And please correct me if i am wrong, thanks,

Cheers,

**Comment by temoto** [comment]
@mouadino hi again. Recent issues have brought this up again and I realised you was right all along. If the connection was about to be closed anyway, that's not normal browser behaviour (even for old IE). So not a big deal to just close it without reading leftovers from request body. Commit b443de3 with fix may just be merged soon. Review is warmly welcome.

I understand it's ridiculous to continue 2 year old discussion, but also good to close a hanging issue.

**Comment by temoto** [comment]
Fix is merged in master.
