### ISSUE TITLE
socket.recv_into() is really slow on eventlet

### ISSUE THREAD

**Issue by kaniini** [eventlet/eventlet#272]
Hello,

Consider the following code with redis-py:

```python
import eventlet.queue
eventlet.monkey_patch()

import redis
import redis.connection

pool = redis.BlockingConnectionPool(connection_class=redis.connection.UnixDomainSocketConnection,
                                    path='/tmp/redis.sock',
                                    max_connections=250, timeout=5, queue_class=eventlet.queue.LifoQueue, db=1)
rc = redis.StrictRedis(connection_pool=pool)

rc.put('test', 'Foo' * 100)
```

Now run timeit:

```
# python3.5 -m timeit -s "from test import rc" -- "rc.get('test')"
10000 loops, best of 3: 88.2 usec per loop
```

Profiling shows that it is due to `socket.recv_into()` call in redis-py's `HiredisParser.read_response()`.  We can disable that codepath by patching `redis.connection` module:

```
# python3.5 -m timeit -s "import redis.connection; redis.connection.HIREDIS_USE_BYTE_BUFFER = False; from test import rc" -- "rc.get('test')"
10000 loops, best of 3: 49.7 usec per loop
```

These are times on a Sandy Bridge Xeon e3-1230 CPU, but the same pattern shows up on various other hardware configurations.

Without eventlet, there is no difference in `socket.recv_into()` performance.

**Comment by jstasiak** [comment]
Hey @kaniini, would you mind performing the same test with the version from the master branch? There's a commit[1] that changes the ``recv_into`` implementation and I suspect this may affect the results.

[1] https://github.com/eventlet/eventlet/commit/bc4d1b5d362e5baaeded35b1e339b9db08172dd2

**Comment by kaniini** [comment]
Hello,

I am seeing improved performance on bc4d1b5.  I think this bug can be closed.

**Comment by jstasiak** [comment]
Awesome, I'll close it then.
