### ISSUE TITLE
On Python 3, sock.makefile('rb').readline() doesn't handle blocking errors correctly

### ISSUE THREAD

**Issue by haypo** [eventlet/eventlet#274]
On Python 3, socket.socket is monkey-patched to GreenSocket (of eventlet.greenio.base) object. When sock.makefile('rb') is called, 

sock.makefile('rb')  creates a SocketIO object (of socket). SocketIO.readline() calls GreenSocket.recv_into() until it gets enough data. It stops when recv_into() returns 0 byte... but also when it returns None.

GreenSocket.recv_into() starts with a trampoline to check if we have data to read, but *sometimes* this check is not enough: recv_into() raises a BlockingIOError. Sadly, GreenSocket.recv_into() only calls the trampoline once, it doesn't handle BlockingIOError.

In case of BlockingIOError, recv_into() is indirectly converted to None, and readline() interprets None as "end of line" so readline() returns an incomplete or empty line.

In the unit test of the OpenStack Glance project, an unit test fails because the HTTP client gets a BadStatusLine (of http.client). In fact, the underlying recv_into() raised BlockingIOError and the read is not retried.

I will propose a fix.

**Comment by temoto** [comment]
Great, thanks. Please, see comments to 4th commit.

Also, about issue reference in commit text. With this format `gh #274` the `gh` is separate word, not parsed by github or any software. Github parses strings like `gh-274`. Personally I think the best option is long URL, like `https://github.com/eventlet/eventlet/issues/274`, because it's clickable in any case.

**Comment by haypo** [comment]
> Github parses strings like gh-274

Ok done.

> Personally I think the best option is long URL, like https://github.com/eventlet/eventlet/issues/274, because it's clickable in any case.

I also added this link.

**Comment by temoto** [comment]
LGTM now

**Comment by jstasiak** [comment]
https://github.com/eventlet/eventlet/pull/275 (just merged) fixes this I believe, please reopen if I'm wrong.

**Comment by jstasiak** [comment]
I completely missed the fact that this breaks tests on Python 3, just reverted, will reopen this issue until that's resolved.

**Comment by haypo** [comment]
> I completely missed the fact that this breaks tests on Python 3, just reverted, will reopen this issue until that's resolved.

I was unable to run tests on Python 3 on my Fedora 23. I found the issue: tox.ini requires explicitly an old version of PyOpenSSL which doesn't work on Fedora 23. Remove the version from tox.ini allows me to run tests on Python 3.

So, I fixed the issue by exchanging the trampoline and the call the the read method in recv_loop(). I don't understand well eventlet, so I'm not sure that it's correct.

**Comment by haypo** [comment]
Oh... It looks like tests now pass on Python 3, but I broke them on Python 2... Any idea how to implement correctly the "recv loop" for GreenSocket?

Or I can write simpler patch with conditional code depending on the Python major version.

**Comment by jstasiak** [comment]
Hah, that's annoying. Let me have a look at what that test does in the first place.

**Comment by jstasiak** [comment]
I think I know what this is (tests break for me locally on Python 2.7.10 too BTW).

The test:
```python
        buf = array.array('B')
        # ...
            value = client.recv_into(buf)
            self.fail("socket.timeout not raised, got %r instead" % (value,))
```

The patch makes so that ``recv_meth`` is called at least once before ``trampoline`` is called:
```diff
-    def recv(self, buflen, flags=0):
+    def _recv_loop(self, recv_meth, *args):
         fd = self.fd
         if self.act_non_blocking:
-            return fd.recv(buflen, flags)
+            return recv_meth(*args)
         while True:
             try:
-                return fd.recv(buflen, flags)
+                return recv_meth(*args)
             except socket.error as e:
                 if get_errno(e) in SOCKET_BLOCKING:
                     pass
@@ -328,35 +328,28 @@ class GreenSocket(object):
                 # Perhaps we should return '' instead?
                 raise EOFError()
```

From what I see the builtin ``socket.recv_into`` (and ``socket.recv`` too) called with non-blocking socket (as it's used by Eventlet internally) won't raise an exception if one attempts to read zero bytes (Python 2.7.10):

```python
>>> s.settimeout(0)
>>> s.recv(0)
''
>>> s.recv(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.error: [Errno 35] Resource temporarily unavailable
>>> 
>>> s.recv_into(bytearray(b''))
0
>>> s.recv_into(bytearray(b'x'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.error: [Errno 35] Resource temporarily unavailable
```

The test suite is making sure an exception is raised while the builtin ``recv_into`` just returns 0, your patch fixes this incompatibility therefore breaking the tests :) I think the right approach here is to modify the tests to enforce builtin ``recv_into`` behaviour (0 when 0 bytes attempted to be read, timeout otherwise in this case).

**Comment by jstasiak** [comment]
In the response above I mixed some things up, sorry. The ``recv_into`` behaviour described is correct for nonblocking sockets but this is about a socket with a timeout. The buitlin ``recv_into``:

```python
>>> s.settimeout(0.1)
>>> s.recv_into(array.array('B', b''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.timeout: timed out
>>> s.recv_into(array.array('B', b'x'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.timeout: timed out
```

So yes, the test is correct (un)fortunately.

**Comment by jstasiak** [comment]
I played with it locally and I modified ``recv`` tests:

```diff
diff --git a/tests/greenio_test.py b/tests/greenio_test.py
index 5c404cc..f2a9f86 100644
--- a/tests/greenio_test.py
+++ b/tests/greenio_test.py
@@ -123,6 +123,8 @@ class TestGreenSocket(tests.LimitedTestCase):
 
         client.connect(addr)
 
+        expect_socket_timeout(client.recv, 0)
         expect_socket_timeout(client.recv, 8192)
 
         evt.send()
```

This introduces a test failure that can solved by something like:

```diff
diff --git a/eventlet/greenio/base.py b/eventlet/greenio/base.py
index 18799af..09bb382 100644
--- a/eventlet/greenio/base.py
+++ b/eventlet/greenio/base.py
@@ -310,6 +310,8 @@ class GreenSocket(object):
             return fd.recv(buflen, flags)
         while True:
             try:
+                if buflen == 0:
+                    self._read_trampoline()
                 return fd.recv(buflen, flags)
             except socket.error as e:
                 if get_errno(e) in SOCKET_BLOCKING:
@@ -319,15 +321,19 @@ class GreenSocket(object):
                 else:
                     raise
             try:
-                self._trampoline(
-                    fd,
-                    read=True,
-                    timeout=self.gettimeout(),
-                    timeout_exc=socket.timeout("timed out"))
+                self._read_trampoline()
             except IOClosed as e:
                 # Perhaps we should return '' instead?
                 raise EOFError()
 
+    def _read_trampoline(self):
+        self._trampoline(
+            self.fd,
+            read=True,
+            timeout=self.gettimeout(),
+            timeout_exc=socket.timeout("timed out"),
+        )
+
```

**Comment by haypo** [comment]
```
+                if buflen == 0:
+                    self._read_trampoline()
```

Oh, thanks for the hint. It looks like tests now pass on Python 2 and Python 3.

**Comment by jstasiak** [comment]
Thanks @haypo, this is now in master.

**Comment by haypo** [comment]
Wow, cool, thank you.

**Comment by raylu** [comment]
With python 3 and 0.17.4, this code always works:

```python
#!/usr/bin/env python3

from eventlet import wsgi
import eventlet

ten_point_one_MiB = 10 * 1024 * 1024 + 128 * 1024

def iter_response():
    for i in range(10 * 1024 // 256):
        yield 'a' * 256 * 1024
    yield 'a' * 128 * 1024

def app(env, start_response):
    start_response('200 OK', [('Content-Type', 'text/plain'), ('Content-Length', ten_point_one_MiB)])
    return iter_response()

wsgi.server(eventlet.listen(('', 8090)), app)
```
```
$ curl localhost:8090 > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.1M  100 10.1M    0     0   386M      0 --:--:-- --:--:-- --:--:--  389M
```
but in 0.18.1, sometimes it works and sometimes you get
```
$ curl localhost:8090 > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 98 10.1M   98  9.9M    0     0  62769      0  0:02:49  0:02:45  0:00:04     0
```
and it just hangs, never downloading the last 128KiB.

`eventlet.wsgi` calls `writelines` https://github.com/eventlet/eventlet/blob/a8125b602110ffd88acb317cc7915ba604cff4bb/eventlet/wsgi.py#L437
on `wfile`, created with the original `makefile` https://github.com/eventlet/eventlet/blob/a8125b602110ffd88acb317cc7915ba604cff4bb/eventlet/greenio/base.py#L293
which is a `socket.SocketIO` object https://github.com/python/cpython/blob/e2165e5eb2ad2bc792d2752b5366cb9d9f083ad2/Lib/socket.py#L532
which inherits from `io.RawIOBase` which inherits from `io.IOBase` which inherits from `_io._IOBase` whose `writelines` implementation just calls `write` and doesn't check the bytes written https://github.com/python/cpython/blob/1fe0fd9feb6a4472a9a1b186502eb9c0b2366326/Modules/_io/iobase.c#L730
and `socket.SocketIO`'s `write` calls `send`, not `sendall` https://github.com/python/cpython/blob/04eca3310445f504e3723d07756b5accfa91421e/Lib/socket.py#L593
so arguably, this is a bug in CPython

**Comment by haypo** [comment]
>  so arguably, this is a bug in CPython

As a Python core developer, I have to disagree :-D I opened the bug report https://github.com/eventlet/eventlet/issues/295

**Comment by jstasiak** [comment]
@raylu @haypo I'll just leave this here for reference: https://mail.python.org/pipermail/python-dev/2012-August/121396.html

Considering the above I'm inclined to say the ``wsgi`` module only worked before because ``GreenSocket.send`` was broken too and was working like ``sendall`` internally therefore the fix is to stop using ``writelines()``.

**Comment by jstasiak** [comment]
Related Python bug report for reference: [Raw I/O writelines() broken for non-blocking I/O](http://bugs.python.org/issue26292)
