### ISSUE TITLE
eventlet.green.zmq ignores RCVTIMEO setting

### ISSUE THREAD

**Issue by talwrii** [eventlet/eventlet#282]
RCVTIMEO is documented here: http://api.zeromq.org/2-2:zmq-setsockopt

Here is a repro for you: 

```
from eventlet.green import zmq # broken with this
#import zmq # works with this

sock = zmq.Context().socket(zmq.SUB)
sock.connect('tcp://127.0.0.1:10432')
sock.setsockopt(zmq.RCVTIMEO, 1000)
sock.recv() # hangs with eventlet zmq, times out with zmq
```

**Comment by talwrii** [comment]
I've got a patch that fixes this...

Just writing some unit tetsts now (I wanted a bug number)

**Comment by talwrii** [comment]
Mergey Merge Merge:

https://github.com/eventlet/eventlet/pull/283

**Comment by temoto** [comment]
Thank you. Slightly modified version f657c22eff384439ed19ea61720dbe678de4cd51 of your patch is merged into master. It'll be released on PyPI soon.
