### ISSUE TITLE
Empty list for headers_set in wsgi.py

### ISSUE THREAD

**Issue by andrefreitas** [eventlet/eventlet#288]
Hi,
With python3.4 and eventlet 0.17.4, I am having the following issue:

```
Traceback (most recent call last):
  File "/home/rsddssd-runner/app/releases/201601211/.env/lib/python3.4/site-packages/eventlet/wsgi.py", line 462, in handle_one_response
    'Content-Length' not in [h for h, _v in headers_set[1]]:
IndexError: list index out of range
```

This doesn't happen with python 3.5.

Note: I am using flask-socketio that is using eventlet. I don't know if is a bug from your side or their side, anyway, since this is a long method in wsgi.py (almost 200 lines), it is probably a bug.

**Comment by jstasiak** [comment]
Hey @andrefreitas, is this the whole traceback? Can you provide a code sample that allows reproducing this?

**Comment by andrefreitas** [comment]
@jstasiak is the only traceback I have. I will try to make a reproducible example. It is hard to debug with just the information I gave.

**Comment by andrefreitas** [comment]
Hi,
I am debugging and the problem is that the start_response method is not called:

    result = self.application(self.environ, start_response)

Therefore in this line the headers_set is still empty:

   Content-Length' not in [h for h, _v in headers_set[1]]:


This only happens in the websocket handshake.

**Comment by temoto** [comment]
@andrefreitas does it work now?

**Comment by andrefreitas** [comment]
@temoto well, as I remember this was due a misconfiguration of NGINX proxying to this microservice.

A PR could be validating if content length is present in the Headers, but since is a very particular case, I believe you don't need to do nothing.

Thanks for your support!
