### ISSUE TITLE
Custom header for urllib2.urlopen

### ISSUE THREAD

**Issue by tuanchauict** [eventlet/eventlet#289]
I'm writing a crawler that the webpage just be able to get data if signed in. The method is quite easy with custom cookie. But I don't find out any code or document for this behaviour. How can I change the cookie or headers for a request of `urllib2.urlopen` or any similar function.

Thanks

**Comment by temoto** [comment]
This is a generic Python question and I'm just quoting the answer found on Stackoverflow.
```
import urllib2
request = urllib2.Request("http://domain/path", headers={"Cookie": "bla-bla-bla"})
contents = urllib2.urlopen(request).read()
```

I highly recommend using any of the following libraries: httplib2, urllib3, requests.
