### ISSUE TITLE
Using eventlet pool inside a for loop gives error after first iteration in python

### ISSUE THREAD

**Issue by skk2142** [eventlet/eventlet#304]
When I run the code below, I get error during second iteration. I wonder if it's because I didn't terminate the first pool before generating a new pool? If so, how do I terminate a pool? I get the same error when I define the pool outside the for loop. 
```python
num_parallel_loop = 6;
collect_result = []
for i in range(n):
   pool = eventlet.GreenPool(size=num_parallel_loop)
   for result in pool.imap(func, dictionary.iteritems()):
		    collect_result.append(result)
```
Error:

> Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 325, in _handle_workers
    while thread._state == RUN or (pool._cache and thread._state != TERMINATE):
AttributeError: '_MainThread' object has no attribute '_state'

**Comment by temoto** [comment]
We have multiprocessing compatibility issue: #147 
It would help if you post full code as comment to 147.
I'm closing this as duplicate.
