### ISSUE TITLE
eventlet not terminating the green threads?

### ISSUE THREAD

**Issue by christopher-abastar** [eventlet/eventlet#306]
Hello, 

Currently, i'm experiencing the same scenario as this guy and it affects my gunicorn, celery termination pretty badly.  Miguel pointed out it could be a eventlet error.  Any ideas on how to fix it? not sure if i'm on the correct project to bug this.

[flask-socketio-eventlet](http://stackoverflow.com/questions/35928723/flask-socketio-debug-with-eventlet-and-redis-spawns-extra-greenthreads)

**Comment by temoto** [comment]
The problem in that code - `redisReader` is started no matter if it's a "worker manager" or an actual "request handler" process. So, don't create and start that pool unconditionally. Consult Werkzeug documentation where is your "application init" event, and only start `redisReader` there.
