### ISSUE TITLE
TypeError: _wrap_socket() argument 1 must be _socket.socket, not GreenSocket

### ISSUE THREAD

**Issue by collinstocks** [eventlet/eventlet#311]
Hi all,
I'm running into a problem after upgrading eventlet via pip when using it with the certifi cafile. The issue seems related to https://github.com/eventlet/eventlet/issues/201.

```python
import certifi
from eventlet.green import urllib2

urllib2.urlopen('https://example.com')  # Works fine.
urllib2.urlopen('https://example.com', cafile=certifi.where())  # TypeError
```

Here's the full traceback (made more detailed by ipython):
```python
<ipython-input-4-e8c65a0ff7bd> in <module>()
----> 1 urllib2.urlopen('https://example.com', cafile=certifi.where())

/usr/lib/python2.7/urllib2.pyc in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    152     else:
    153         opener = _opener
--> 154     return opener.open(url, data, timeout)
    155 
    156 def install_opener(opener):

/usr/lib/python2.7/urllib2.pyc in open(self, fullurl, data, timeout)
    429             req = meth(req)
    430 
--> 431         response = self._open(req, data)
    432 
    433         # post-process response

/usr/lib/python2.7/urllib2.pyc in _open(self, req, data)
    447         protocol = req.get_type()
    448         result = self._call_chain(self.handle_open, protocol, protocol +
--> 449                                   '_open', req)
    450         if result:
    451             return result

/usr/lib/python2.7/urllib2.pyc in _call_chain(self, chain, kind, meth_name, *args)
    407             func = getattr(handler, meth_name)
    408 
--> 409             result = func(*args)
    410             if result is not None:
    411                 return result

/usr/lib/python2.7/urllib2.pyc in https_open(self, req)
   1238         def https_open(self, req):
   1239             return self.do_open(httplib.HTTPSConnection, req,
-> 1240                 context=self._context)
   1241 
   1242         https_request = AbstractHTTPHandler.do_request_

/usr/lib/python2.7/urllib2.pyc in do_open(self, http_class, req, **http_conn_args)
   1192 
   1193         try:
-> 1194             h.request(req.get_method(), req.get_selector(), req.data, headers)
   1195         except socket.error, err: # XXX what error?
   1196             h.close()

/usr/lib/python2.7/httplib.pyc in request(self, method, url, body, headers)
    999     def request(self, method, url, body=None, headers={}):
   1000         """Send a complete request to the server."""
-> 1001         self._send_request(method, url, body, headers)
   1002 
   1003     def _set_content_length(self, body):

/usr/lib/python2.7/httplib.pyc in _send_request(self, method, url, body, headers)
   1033         for hdr, value in headers.iteritems():
   1034             self.putheader(hdr, value)
-> 1035         self.endheaders(body)
   1036 
   1037     def getresponse(self, buffering=False):

/usr/lib/python2.7/httplib.pyc in endheaders(self, message_body)
    995         else:
    996             raise CannotSendHeader()
--> 997         self._send_output(message_body)
    998 
    999     def request(self, method, url, body=None, headers={}):

/usr/lib/python2.7/httplib.pyc in _send_output(self, message_body)
    848             msg += message_body
    849             message_body = None
--> 850         self.send(msg)
    851         if message_body is not None:
    852             #message_body was not a string (i.e. it is a file) and

/usr/lib/python2.7/httplib.pyc in send(self, data)
    810         if self.sock is None:
    811             if self.auto_open:
--> 812                 self.connect()
    813             else:
    814                 raise NotConnected()

/usr/lib/python2.7/httplib.pyc in connect(self)
   1210 
   1211             self.sock = self._context.wrap_socket(self.sock,
-> 1212                                                   server_hostname=server_hostname)
   1213 
   1214     __all__.append("HTTPSConnection")

/usr/lib/python2.7/ssl.pyc in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
    348                          suppress_ragged_eofs=suppress_ragged_eofs,
    349                          server_hostname=server_hostname,
--> 350                          _context=self)
    351 
    352     def set_npn_protocols(self, npn_protocols):

/usr/lib/python2.7/ssl.pyc in __init__(self, sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, family, type, proto, fileno, suppress_ragged_eofs, npn_protocols, ciphers, server_hostname, _context)
    558             try:
    559                 self._sslobj = self._context._wrap_socket(self._sock, server_side,
--> 560                                                           server_hostname, ssl_sock=self)
    561                 if do_handshake_on_connect:
    562                     timeout = self.gettimeout()

TypeError: _wrap_socket() argument 1 must be _socket.socket, not GreenSocket
```

I'm using the following versions:
certifi==2016.2.28
eventlet==0.18.4

```
$ python --version
Python 2.7.9
```

Keeping everything else the same, the same code runs perfectly in eventlet==0.17.4, but not in any newer release on pypi (pip can't find 0.18.0 or 0.18.1).

**Comment by temoto** [comment]
Please, give me value of `certifi.where()`.

**Comment by temoto** [comment]
NVM, I can reproduce it.

**Comment by collinstocks** [comment]
I would love to help with this, but I'm not up to speed with eventlet internals. Any suggestions on where to start?

**Comment by collinstocks** [comment]
Please see https://github.com/eventlet/eventlet/pull/312 for a fix. I believe this bug has been around since 2009 (https://github.com/collinstocks/eventlet/commit/f6e97445c892e3063c67012ca17695b03b3799a8), but was masked by the recently fixed bug where merely importing eventlet would cause ssl to be monkey-patched (https://github.com/eventlet/eventlet/issues/240; fixed by https://github.com/eventlet/eventlet/pull/277).

**Comment by collinstocks** [comment]
Sorry if this is the wrong place to ask, but I'm wondering what the release cycle looks like (that is, when eventlet==18.5 looks like it's going to be released). For now, we're still using eventlet==17.4, but we recently realized that version is causing a resource leak due to an interaction between boto's use of threads and the monkey-patched SSL module. This problem will go away when we upgrade to eventlet==18.x, but we can't do that until the fix for this issue (#311) is released. I don't mean to rush you -- I'm just hoping for some visibility into the release plan.

**Comment by temoto** [comment]
Ah that's simple. There is no release plan. Because there is no value in release. It's just a git tag and upload to pypi.

I encourage you to use `-e git://github.com/eventlet/eventlet.git@COMMIT` in requirements, that way you have full control which version to include and bonus: github is more available than pypi.

If you still absolutely must use release, like Openstack people, no problem, I'll make another release soon.

**Comment by collinstocks** [comment]
Thanks!

**Comment by richardasaurus** [comment]
> There is no release plan. Because there is no value in release. It's just a git tag and upload to pypi.

Are you trolling?

**Comment by temoto** [comment]
@richardasaurus sometimes I'm too aggressive towards certain minded people. But I stand my words, release entity has no value. You can achieve even better results by pointing requirements to particular git commit. The commit id is hash of repository content, so it means there is no way to reupload changes under same release number, no way for man-in-the-middle attack.

I understand release numbers are more popular, so Eventlet gets PyPI releases without problem.

**Comment by collinstocks** [comment]
Releases indicate to users of your library which commits are considered
stable/functional.

**Comment by temoto** [comment]
@collinstocks TL;DR: consider stable/functional every commit on master branch.

I think that expectation of stable releases comes from the old development process (subversion and before), when we didn't have easy way of dealing with branches. Now with modern SCMs, I can't imagine an excuse to commit half baked feature into main source timeline in hope it will be finished by release. You just do it in branch so nobody gets "raw" code.

Also we don't have testers, so no release candidates, feature freezes. Every commit on every branch is checked against all tests on Travis. On sunny days contributors also verify new versions in their environment. So every commit gets as much attention and testing as it possibly can.

What actually describes Eventlet (and plethora other projects) releases - random batches of (mostly) unrelated commits. I think waiting for few other unrelated commits before one that concerns you gets a release number does not make sense.

**Comment by collinstocks** [comment]
I think that's a great way of doing things when running a project with
multiple contributors. It's just not something I as a library user would
expect automatically without your very nice explanation above.

**Comment by temoto** [comment]
Yeah, I guess it deserves a note in readme or website, thanks for idea.
