### ISSUE TITLE
greendns.getaddrinfo fails on LLA with scope index

### ISSUE THREAD

**Issue by jjohnson42** [eventlet/eventlet#321]

**Comment by jjohnson42** [comment]
I meant to write some commentary, I made the following change to have is_ipv6_addr return True for fe80::abcd%eno2 for example
def is_ipv6_addr(host):
    """Return True if host is a valid IPv6 address"""
    if not isinstance(host, six.string_types):
        return False
    host = host.split('%', 1)[0]
    try:
        dns.ipv6.inet_aton(host)
    except dns.exception.SyntaxError:
        return False
    else:
        return True

**Comment by jjohnson42** [comment]
Made pull request 322 with the change.

**Comment by temoto** [comment]
Thanks, your fix is merged into master.
