### ISSUE TITLE
Drop support for older Python versions

### ISSUE THREAD

**Issue by jstasiak** [eventlet/eventlet#333]
Since the resources people can dedicate to this project are very limited and supporting older Python versions causes more and more trouble I propose what follows:

* Drop Python 2.6 and 2.7 support immediately (affects all future non-patch releases)
* Create a branch based on the most recent Eventlet release so we can apply bug fixes there and release on PyPI for the time being

Pinging @temoto

**Comment by jstasiak** [comment]
Actually now that I think about it I'm fine with not having any bugfix Python 2-compatible branch and releases at all (unless someone wants to step up and maintain it).

**Comment by temoto** [comment]
- 2.7 will be supported.
- We can definitely sacrifice 2.6 granted sufficient benefits (so far I don't know any).

If there's community interest, I propose split into packages:
- `eventlet` high level API and Python version independent things like Queue, Event, etc
- `eventlet-low-py{2,3,py}` low level API for different platforms, things like Hub, greenio, SSL

**Comment by jstasiak** [comment]
I think I understand where you're coming from. What would you suggest I should do in cases where I want to contribute (bug fix most likely) but do not want to spend any more time on Python 2 compatibility?

**Comment by temoto** [comment]
Principle in short: no violence. Do only what you feel is right.

Some options:
- A patch that fixes bug for one platform leaving other versions broken is still better than not fixing anything.
- I'm very fine with copying parts of stdlib.
- Write me an email or find `temotor` in Telegram messenger to discuss particular case.
- Guard bugfix with version check and commit it as py3-only.

**Comment by jstasiak** [comment]
Hah, I haven't thought of that - version guarding new code/bugfix will certainly work for me, I should've thought about it. If you're fine with it I'm fine with it, let me close the issue.
