### ISSUE TITLE
monkey_patch(subprocess=True) doesn't patch CalledProcessError

### ISSUE THREAD

**Issue by nat-goodspeed** [eventlet/eventlet#357]
My script uses:

    eventlet.monkey_patch(os=True, select=True, socket=True, time=True,
                      builtins=True, subprocess=True)
    # ...
    import subprocess
    # ...
    try:
        output = subprocess.check_output(...)
    except subprocess.CalledProcessError as error:
        # ...

This fails to catch CalledProcessError. Changing the `except` line to:

    except eventlet.green.subprocess.CalledProcessError as error:

does catch the exception.

**Comment by temoto** [comment]
Please track progress on this problem here #413
