### ISSUE TITLE
monkey_patch breaks keyboard input in ipdb inside docker-compose

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#361]
This issue was originally posted on Stackoverflow https://stackoverflow.com/questions/40842877

> So I am using the micro-servicing python package _nameko_ which runs a service using `eventlet` and calls `eventlet.monkey_patch()` on import. 
> I have deciphered that it is this piece of code that is blocking any debug attempts via `ipdb`. The `ipdb` console shows in the terminal but I cannot type anything and have to close the entire terminal session in order to quit the process.
> The stuck console looks like:
[![enter image description here][1]][1]
> How can I use `ipdb` with this function?
> EDIT: This issue _only_ seems to happen when within a docker container.

  [1]: https://i.stack.imgur.com/fUN3D.png

**Comment by temoto** [comment]
As of 2016-12-02, the issue is not studied, I suggest to try `monkey_patch(os=False)`.

**Comment by marco-lavagnino** [comment]
This bug is the same as in #395. Solving that issue would likely solve this one too.

**Comment by temoto** [comment]
@marco-lavagnino how do you know it's the same?

**Comment by marco-lavagnino** [comment]
@temoto manually installed latest ipdb, latest eventlet and old ipython (4.0.1) in a virtualenv, and it didn't hang. If I installed ipython 5 in the same virtualenv, ipdb did hang.

**Comment by temoto** [comment]
Duplicate of #395 

@marco-lavagnino thank you.
