### ISSUE TITLE
DNS is broken with eventlet==0.20.0

### ISSUE THREAD

**Issue by mattbennett** [eventlet/eventlet#363]
Upgrading to eventlet 0.20.0 breaks DNS lookups of fully-qualified domain names that do not end with a `.` if a search domain is specified.

dnspython doesn't support this behaviour (https://github.com/rthalley/dnspython/issues/219), I guess because it's not strictly correct, but `socket.getaddrinfo` _does_, so the behaviour is different with and without the monkeypatch.

Gist to reproduce is here: https://gist.github.com/mattbennett/b0340fedd8a8f1fecd47cba26c7bec6b

**Comment by temoto** [comment]
Please try this version with fix

`pip install https://github.com/eventlet/eventlet/archive/2dabaecdc1c582f2db43f114b10af461430deced.zip`

**Comment by mattbennett** [comment]
Yep, this solves the problem. Thank you.

I guess the `resolve.conf` docs are vague -- "Resolver queries having fewer than ndots dots in them will be attempted using each component of the search path..." but if `ndots` is _zero_ then shouldn't a no-dot domain name be interpreted as fully-qualified? `getaddrinfo` seems to be interpreting it one way and `dnspython` the other.

**Comment by temoto** [comment]
I deeply agree that `resolv.conf` specs could use some tough clarification. I think `ndots:0` makes unqualified names invalid. Also, from managing persistent virtual machines I learned that adding `.local` domain everywhere makes things really clear and easy to configure.

**Comment by temoto** [comment]
The fix is included in v0.20.1 version that is already available on PyPI.
If you pinned requirements to 0.19, please update to `eventlet==0.20.1` now.
