### ISSUE TITLE
monkey_patch line blocking APScheduler

### ISSUE THREAD

**Issue by MPagel** [eventlet/eventlet#365]
http://stackoverflow.com/q/41326156/4228193

An APScheduler task is failing to trigger when also using Eventlet.  If I comment out the `patcher.monkey_patch(all=True)` line, APScheduler fires properly (but I don't think the Eventlet code would work appropriately in those circumstances).

**Comment by MPagel** [comment]
Moving the import and monkey_patch line up to the top of the module (outside of __main__) still results in deactivation of APScheduler. Moving it into the same procedure where I first call and use a GreenPool allows APScheduler to fire but results in the following errors when I control-C out of the program (KeyboardInterrupt is trapped in the main() procedure)

> 2016-12-26 19:46:20 UTC (+0000): EXITING due to control-C or other exit signal
> Jobstore default:
>     Time-Activated Download (trigger: interval[0:05:00], next run at: 2016-12-26 11:50:00 PST)
> 2016-12-26 19:46:20 UTC (+0000): 1
> Traceback (most recent call last):
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 457, in fire_timers
>     timer()
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\timer.py", line 58, in __call__
>     cb(*args, **kw)
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\semaphore.py", line 157, in _do_acquire
>     waiter.switch()
> error: cannot switch to a different thread
> Traceback (most recent call last):
>   File "ReadQueues.py", line 1034, in <module>
>     main(sys.argv)
>   File "ReadQueues.py", line 1029, in main
>     sched.shutdown(wait=False)
>   File "D:\Programs\Python\Python27\lib\site-packages\apscheduler\schedulers\background.py", line 40, in shutdown
>     self._thread.join()
>   File "D:\Programs\Python\Python27\lib\threading.py", line 940, in join
>     self.__block.wait()
>   File "D:\Programs\Python\Python27\lib\threading.py", line 340, in wait
>     waiter.acquire()
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\semaphore.py", line 125, in acquire
>     hubs.get_hub().switch()
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 294, in switch
>     return self.greenlet.switch()
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 346, in run
>     self.wait(sleep_time)
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\selects.py", line 34, in wait
>     time.sleep(seconds)
> KeyboardInterrupt
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "D:\Programs\Python\Python27\lib\atexit.py", line 24, in _run_exitfuncs
>     func(*targs, **kargs)
>   File "D:\Programs\Python\Python27\lib\site-packages\concurrent\futures\thread.py", line 39, in _python_exit
>     t.join(sys.maxint)
>   File "D:\Programs\Python\Python27\lib\threading.py", line 951, in join
>     self.__block.wait(delay)
>   File "D:\Programs\Python\Python27\lib\threading.py", line 359, in wait
>     _sleep(delay)
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\greenthread.py", line 34, in sleep
>     hub.switch()
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 294, in switch
>     return self.greenlet.switch()
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 346, in run
>     self.wait(sleep_time)
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\selects.py", line 34, in wait
>     time.sleep(seconds)
> KeyboardInterrupt
> Error in sys.exitfunc:
> Traceback (most recent call last):
>   File "D:\Programs\Python\Python27\lib\atexit.py", line 24, in _run_exitfuncs
>     func(*targs, **kargs)
>   File "D:\Programs\Python\Python27\lib\site-packages\concurrent\futures\thread.py", line 39, in _python_exit
>     t.join(sys.maxint)
>   File "D:\Programs\Python\Python27\lib\threading.py", line 951, in join
>     self.__block.wait(delay)
>   File "D:\Programs\Python\Python27\lib\threading.py", line 359, in wait
>     _sleep(delay)
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\greenthread.py", line 34, in sleep
>     hub.switch()
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 294, in switch
>     return self.greenlet.switch()
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 346, in run
>     self.wait(sleep_time)
>   File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\selects.py", line 34, in wait
>     time.sleep(seconds)
> KeyboardInterrupt
> 
>

**Comment by MPagel** [comment]
eventlet.patcher.monkey_patch(all=False, os=True, select=True, socket=True, thread=False, time=True) doesn't block APScheduler, but will probably block eventlet.  I'll give it a whirl though.

**Comment by MPagel** [comment]
It **appears** to be working at present. I'm not sure which modules specifically need monkeypatching in my case - I was going off the advice at http://stackoverflow.com/a/4721264/4228193 to just go ahead and monkeypatch all.

Perhaps it is working because when I'm using the GreenThreads, I'm distinctly NOT responding to changes to files in the config directory (the WaitForSingleObject code), nor am I responding to APScheduler events.  I tell APScheduler to pause before I call the procedure that has eventlet contained within.  

I was using the whole monkey_patch line, as the [documentation](http://eventlet.net/doc/basic_usage.html#patching-functions) states
 
> `eventlet.monkey_patch(all=True, os=False, select=False, socket=False, thread=False, time=False)`
> 
>     Globally patches certain system modules to be greenthread-friendly. The keyword arguments afford some control over which modules are patched. If all is True, then all modules are patched regardless of the other arguments. If it’s False, then the rest of the keyword arguments control patching of specific subsections of the standard library

Which I took to mean that the default behavior was to patch all, and if you switch the "all" to false, you would need specifically override the defaults for the other parameters. Is it basically "smart" and interprets the opposite of your explicit declaration values are for the non-explicit variables"?

Unfortunately running on linux is not an option - the purpose of this script is to feed Amazon Web Service SQS messages into a MS SQL Server database. My institution does not support migrating to another solution (e.g. MySQL, postgreSQL, etc) on linux, so I'm stuck developing in the windows world.

Thanks for all your assistance - I'll consider wrapping the other code in `eventlet.tpool.execute` if I hit any snags with the present model (e.g. if my downloads take longer than the period APScheduler is configured for).

**Comment by temoto** [comment]
Great, if it doesn't work, write me more. You mentioned downloading files, basically, you only need to patch socket, maybe select. Non-blocking file IO is so hard most people revert to thread pools. We don't have even that, so wrapping `file.write` calls with `eventlet.tpool.execute` is a very good idea.

`monkey_patch` acts smart, yes. I think it's at teen level right now. Sometimes rebels for no reason and refuses to explain. But yeah, I'm glad we're keeping up with worldwide AI trend.

Should tpool not fulfill your expectations, another great option is to split code in two processes: cooperative and blocking connected by TCP socket. It has advantage of fail-proof by design, no quirks possible.

**Comment by MPagel** [comment]
good point re: file.write. There are circumstances when two processes might attempt to write the same (non-critical) file, so I'll wrap those in the tpool.execute as appropriate.  Right now I just have it re-attempting writes (appends) upon failure after one minute.

**Comment by temoto** [comment]
Concurrent append is no joke problem and the only real solution is to execute writes one at a time. To do that across different processes means "database server" process and some kind of queue in it. Just `open('path', 'ab').write('foo")` may overwrite (or worse - partially) concurrent updates.

`tpool.execute` doesn't serialize calls, by default it's configured to 20 threads.

**Comment by MPagel** [comment]
There's probably a way to require file accesses to be serialized within GreenPools using your eventlet.queue class, but sometimes the wheel gets reinvented.

Do you see any problems with the following:
```
#!/usr/bin/env python
from __future__ import print_function
import eventlet

eventlet.patcher.monkey_patch(thread=False) # other configurations seem to result in APScheduler not working.
"""
It is important to call monkey_patch() as early in the lifetime of the application as possible.
Try to do it as one of the first lines in the main module.
The reason for this is that sometimes there is a class that inherits from a class that needs to be greened - e.g. a class that inherits from socket.socket -
and inheritance is done at import time, so therefore the monkeypatching should happen before the derived class is defined. It?s safe to call monkey_patch multiple times.
"""
import time, random, sys
DEBUG = True
VERBOSE = True

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

class LockError(Exception):
  def __init__(self, value):
    self.value = value
  def __str__(self):
    return repr(self.value)

def staticVars(**kwargs):
  def decorate(func):
    for k in kwargs:
      setattr(func, k, kwargs[k])
    return func
  return decorate

@staticVars(lockedFiles={},counter=0)
def lockFn(itr=-1,lock=True,fname='',locker=None,timeout=60,raiseErrors=True):
  lockFn.counter += 1
  cnt=itr if itr>=0 else lockFn.counter
  if (not fname) or (not locker): return False
  startTime = time.time()
  if lock:
    while 1:
      while 1:
        if fname in lockFn.lockedFiles:
          if time.time() > startTime + timeout:
            if DEBUG or VERBOSE:
              try:
                eprint("Timeout reached in iter{} while attempting to lock {} with {}. Process {} has the lock".format(cnt,fname,locker,lockFn.lockedFiles[fname]))
              except Exception: # locker is unprintable - it doesn't have a __str__ function.
                eprint("Timeout reached in iter{} while attempting to lock {}. Unknown process has the lock".format(cnt,fname))
            if raiseErrors: raise LockError("Lock Timeout")
            return False
          time.sleep(0.06) # looser = doesn't check if the lock is free as often. Tighter = more frequent checks.
          continue
        break
      lockFn.lockedFiles[fname] = locker
      time.sleep(0.1) # so as to not succomb to race conditions..can probably tighten up a bit
      try: 
        if lockFn.lockedFiles[fname] != locker:
          if DEBUG or VERBOSE:
            try:
              eprint("Error in iter{}: lock changed\n\t{} tried to lock {}, but {} grabbed it after\n\tWill wait patiently".format(cnt,locker,fname,lockFn.lockedFiles[fname]))
            except Exception:
              eprint("Error in iter{}: lock changed".format(cnt))
          continue # try again
      except KeyError,IndexError: # lock was deleted
        if VERBOSE: print("Thought that a lock for {} already existed, but it was released before we could check which file had it".format(fname))
        continue # should grab it next pass
      try:
        if VERBOSE: print("Lock established in iter{} for {} by {}".format(cnt,fname,locker))
      except Exception:
        print("Lock established in iter{} for {} by unknown".format(cnt,fname))
      break
#  print("itr {} counter value @ exit: {}".format(itr,doStuff.counter))
  else: # release
    try:
      if lockFn.lockedFiles[fname] != locker:
        if DEBUG or VERBOSE:
          try:
            eprint("Error unlocking {} in iter{}: {} was the wrong locking entity".format(fname,cnt,locker))
          except Exception:
            eprint("Error unlocking {} in iter{}: Wrong locking entity".format(fname,cnt))
        if raiseErrors: raise LockError("Wrong Lock for Unlock")
        return False
      lockFn.lockedFiles.pop(fname,None)
      try:
        if VERBOSE: print("{} released {}".format(locker,fname))
      except Exception:
        if VERBOSE: print("{} was released".format(fname))
    except IndexError:
      if DEBUG or VERBOSE: eprint("Error in iter{}: No lock for {} exists".format(cnt,fname))
      if raiseErrors: raise LockError
      return False
    except LockError:
      if DEBUG or VERBOSE: eprint("Error in unlock for {} in iter{}".format(fname,cnt))
      if raiseErrors: raise
      return False
    except Exception:
      if DEBUG or VERBOSE: eprint("Error in iter{}: Unknown exception raised in unlock action for {}".format(cnt,fname))
      raise # regardless of raiseErrors
  return True

@staticVars(counter=0) # I don't understand why this doesn't carry over, even when on a sep line from the lockedFiles bit. Magic voodoo I guess.
def processFile(fname,recID,itr=-1):
  processFile.counter += 1
  cnt = itr if itr >= 0 else processFile.counter
  if lockFn(itr=cnt,lock=True,fname=fname,locker=recID):
    # open file
    openSecs = random.randint(3,20)
    for i in range(openSecs*10):
      time.sleep(0.1)
    if lockFn(itr=cnt,lock=False,fname=fname,locker=recID):
      pass # release
    else:
      try:
        print("We've got a problem, boblem. Iter{} File name: {}; Locker: {}".format(cnt,fname,recID))
      except Exception:
        print("We've got a problem, boblem. Iter{} File name: {}; unknown locking entity".format(cnt,fname))
      return False
  return True

def runThreads():
  fileList = ["bob.txt","sally.txt","sally.txt","bob.txt",
              "bob.txt","sally.txt","sally.txt","bob.txt",
              "bob.txt","sally.txt","sally.txt","bob.txt",
              "bob.txt","sally.txt","sally.txt","bob.txt"]
  receiversList = ["first","first","second","second",
                   "first","second","first","second",
                   "first","second","second","first",
                   "second","second","first","first"]
  pool = eventlet.GreenPool(size=5)
  for i in range(0,len(fileList)):
    pool.spawn(processFile,fname=fileList[i],recID=receiversList[i],itr=i)
  print("Waiting for final threads to exit")
  pool.waitall()
  print("All done, but you can tell that already by the fact that the prompt is now open")

runThreads()
```

one run's output (with VERBOSE=TRUE):

```
Lock established in iter1 for sally.txt by first
Lock established in iter3 for bob.txt by second
second released bob.txt
Lock established in iter4 for bob.txt by first
first released sally.txt
Lock established in iter6 for sally.txt by first
first released sally.txt
Lock established in iter5 for sally.txt by second
first released bob.txt
Lock established in iter8 for bob.txt by first
second released sally.txt
Lock established in iter9 for sally.txt by second
second released sally.txt
Lock established in iter10 for sally.txt by second
first released bob.txt
Lock established in iter0 for bob.txt by first
first released bob.txt
Lock established in iter12 for bob.txt by second
second released bob.txt
Lock established in iter11 for bob.txt by first
second released sally.txt
Lock established in iter14 for sally.txt by first
Timeout reached in iter2 while attempting to lock sally.txt with second. Process first has the lock
Traceback (most recent call last):
  File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 457, in fire_timers
    timer()
  File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\timer.py", line 58, in __call__
    cb(*args, **kw)
  File "D:\Programs\Python\Python27\lib\site-packages\eventlet\greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "greentest.py", line 104, in processFile
    if lockFn(itr=cnt,lock=True,fname=fname,locker=recID):
  File "greentest.py", line 48, in lockFn
    if raiseErrors: raise LockError("Lock Timeout")
LockError: 'Lock Timeout'
Waiting for final threads to exit
first released sally.txt
Lock established in iter13 for sally.txt by second
first released bob.txt
Lock established in iter15 for bob.txt by first
Timeout reached in iter7 while attempting to lock bob.txt with second. Process first has the lock
Traceback (most recent call last):
  File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\hub.py", line 457, in fire_timers
    timer()
  File "D:\Programs\Python\Python27\lib\site-packages\eventlet\hubs\timer.py", line 58, in __call__
    cb(*args, **kw)
  File "D:\Programs\Python\Python27\lib\site-packages\eventlet\greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "greentest.py", line 104, in processFile
    if lockFn(itr=cnt,lock=True,fname=fname,locker=recID):
  File "greentest.py", line 48, in lockFn
    if raiseErrors: raise LockError("Lock Timeout")
LockError: 'Lock Timeout'
first released bob.txt
second released sally.txt
All done, but you can tell that already by the fact that the prompt is now open
```

If having a process locker like this is important for you, you're free to use the code.

**Comment by temoto** [comment]
`  lockFn.counter += 1` is not atomic, executing this in two threads may end up with only one increment applied.

Everything else I just glanced fast, basically you do per-file locks. That's a viable strategy, I hope it works for you.

I'd recommend following approach with queue, indeed. For compatibility with tpool you'd need queue synchronised to OS threads (`eventlet.patcher.original('queue')` to ensure using unpatched version).

```
writers = {}
writers_lock = threading.Lock()

def append_handler(req):
  filepath = make_filepath(req)
  useful_bytes = make_block(req)
  safe_append(filepath, useful_bytes)


def writer(q, stop):
  while 

def new_writer(path):
  # use class if you prefer
  try:
    f = open(path, 'ab')
  except Exception:
    # ... handle errors how you please
  
  q = Queue()
  private = (f, time.time(), 'additional per-file info')
  
  return (q, private)

def safe_append(path, bs):
  with writers_lock:
    w = writers.get(path)
    if w is None:
      w = writers.setdefault(path, new_writer(path))

  qwe
```

**Comment by temoto** [comment]
(maybe you received notification with unfinished draft of this message)

`  lockFn.counter += 1` is not atomic, executing this in two threads may end up with only one increment applied.

Everything else I just glanced fast, basically you do per-file locks. That's a viable strategy, I hope it works for you.

I'd recommend following approach with queue, indeed. For compatibility with tpool you'd need queue synchronised to OS threads (`eventlet.patcher.original('queue')` to ensure using unpatched version).

```
os_threading = eventlet.patcher.original('threading')
os_queue = eventlet.patcher.original('queue')
writers = {}
writers_lock = threading.Lock()  # this may be green or OS threading, I expect both should work


def append_handler(req):
  filepath = make_filepath(req)
  useful_bytes = make_block(req)
  done = safe_append(filepath, useful_bytes)
  done.wait()  # if you don't want write finish synchronisation, remove all Event related code or you will leak memory to event objects


def write_once(f, bs):
  try:
    f.write(bs)
    # you may not need this if writes are frequent and small
    f.flush()
    # if sudden shutdown loss/corruption is not acceptable, you need both flush and OS level `fsync`
    return True
  except Exception:
    return False


def writer_loop(f, q):
  try:
    while True:
      item = q.get(block=True)
      if item is None:  # close signal
        break
      bs, done = item
      ok = write_once(f, bs)
      if not ok:
        print('write error, handle as you please')
      done.set()
  finally:
    f.close()


def new_writer(path):
  # use class if you prefer
  try:
    f = open(path, 'ab')
  except Exception:
    # ... handle errors how you please
  
  q = os_queue.Queue()
  t = os_threading.Thread(target=writer_loop, args=(f, q))
  private = (f, t, time.time(), 'additional per-file info')
  return (q, private)


def safe_append(path, bs):
  with writers_lock:
    w = writers.get(path)
    if w is None:
      w = writers.setdefault(path, new_writer(path))

  done = threading.Event()
  w.put((bs, done))
  return done
```

**Comment by temoto** [comment]
This thing, properly generalized and documented probably deserves a place in Eventlet source or as a separate package, because the task is actually very common. Thanks for bringing this up.
