### ISSUE TITLE
Eventlet doesn't accept external requests for some reason

### ISSUE THREAD

**Issue by iiDatKat** [eventlet/eventlet#366]
I'm running Flask + Socket.IO on the Eventlet library that I got via pip.
Here's my code:

    from flask import Flask, request, render_template
    from flask_socketio import SocketIO
    from flask_cors import CORS, cross_origin
    app = Flask(__name__)
    app.config['SECRET_KEY']='secret!'
    socketio = SocketIO(app)

    import eventlet
    eventlet.monkey_patch()

    @app.route("/")
    def index():
        return "<html><body><h1>Hellooooooooooo</h1></body></html>"

    if __name__ == '__main__':
        CORS(app)
        socketio.run(app, host='0.0.0.0', debug = False, use_reloader=False)

The last line of code (`socketio.run(app, host='0.0.0.0', debug = False, use_reloader=False)`), according to the socket.io documentation, should run the Eventlet server, and it does. I specify the host to be `0.0.0.0`, so theoretically it should accept requests from outside, e.g. from local IP (192.168.1.xxx) and from localhost. 

When I run it, it does say that it's running on 0.0.0.0:5000 (default port on Flask), but when I try to access it via web browser (`192.168.1.xxx:5000`) it gets stuck and doesn't load the webpage. Same result with `localhost:5000`. 

However, if I uninstall eventlet, it runs on the default Flask web server. I commented out the eventlet part of the code and ran it again. Sure enough, visiting `localhost:5000` works but `192.168.1.xxx:5000` doesn't work.

Is this an error with eventlet or socket.io?

**Comment by temoto** [comment]
My best guess is you have a negative network policy for 5000 port. Or you tried wrong IP. tcpdump would help a lot.

**Comment by iiDatKat** [comment]
@temoto Should I do tcpdump while Eventlet server is running?

**Comment by temoto** [comment]
Yup, this line was giving useful info for me `tcpdump -i any -An -vvv -ttttt -s1500 'port 5000'`

**Comment by iiDatKat** [comment]
@temoto Well, it doesn't look too helpful to me. This is `tcpdump`:

    tcpdump: data link type PKTAP
    tcpdump: listening on any, link-type PKTAP (Apple DLT_PKTAP), capture size 1500 bytes

That's it.

**Comment by temoto** [comment]
You should also try to make request while tcpdump is capturing network.

**Comment by iiDatKat** [comment]
@temoto Request to where? The server? I can't access the server page from IP or localhost.

**Comment by temoto** [comment]
While otherwise allmighty, tcpdump is not able to think up useful information. You must attempt requests even if that wasn't working before.

**Comment by iiDatKat** [comment]
@temoto Now it works somehow. Huh. That was random.

**Comment by temoto** [comment]
(Assuming Linux or similar POSIX OS).
Try to inspect `netstat -nat |fgrep -c TIME_WAIT`, if that number goes too high, it means you need to add `net.ipv4.tcp_tw_recycle = 1` to sysctl.

**Comment by iiDatKat** [comment]
Never mind @temoto I'm having the problem again.

**Comment by iiDatKat** [comment]
@temoto Sometimes the server only accepts `localhost` requests, other times it doesn't accept both `localhost` and the local ip requests.

**Comment by iiDatKat** [comment]
@temoto And `netstat -nat |fgrep -c TIME_WAIT` returned 0.

**Comment by iiDatKat** [comment]
@temoto I updated my question. Visiting `192.168.1.xxx:5000` on the Flask webserver also doesn't work.

**Comment by iiDatKat** [comment]
@temoto Ahhhhh, issue resolved. My IP unexpectedly changed midway, so the old IP didn't work.
