### ISSUE TITLE
tests.greendns_test.TestGetaddrinfo failing: assert udp in filt_res, res

### ISSUE THREAD

**Issue by onovy** [eventlet/eventlet#373]
Hi,

I'm Debian maintainer of python-eventlet package.

I just got this bugreport: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850508

That means, package can't be build on current Debian unstable. Reason is:

```
======================================================================
FAIL: test_getaddrinfo (tests.greendns_test.TestGetaddrinfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/greendns_test.py", line 470, in test_getaddrinfo
    assert udp in filt_res
AssertionError

======================================================================
FAIL: test_getaddrinfo_idn (tests.greendns_test.TestGetaddrinfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/greendns_test.py", line 484, in test_getaddrinfo_idn
    assert udp in filt_res, res
AssertionError: [(2, 1, 6, '', ('127.0.0.2', 22))]

======================================================================
FAIL: test_getaddrinfo_inet (tests.greendns_test.TestGetaddrinfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/greendns_test.py", line 494, in test_getaddrinfo_inet
    assert udp in [ai[:3] + (ai[4],) for ai in res]
AssertionError

======================================================================
FAIL: test_getaddrinfo_inet6 (tests.greendns_test.TestGetaddrinfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/greendns_test.py", line 504, in test_getaddrinfo_inet6
    assert udp in [ai[:3] + (ai[4],) for ai in res]
AssertionError

----------------------------------------------------------------------
Ran 626 tests in 59.798s

FAILED (SKIP=90, failures=4)
```

Package is version 0.19.0. I tried to build newest version 0.20.1, and issue is same. Because this package builts fine before, I think it can be related to some dependency upgrade.

Any suggestion?

Thanks.

**Comment by temoto** [comment]
Sorry, I'm on road for a week, this would only be guesses.

Please, try previous versions of dnspython and/or greenlet.

**Comment by Kobla** [comment]
Hi,

I tried to build it with following versions:
dnspython 1.14.0-3
dnspython 1.13.0-2
greenlet 0.4.10-1
greenlet 0.4.9-2

But issue is same.

**Comment by temoto** [comment]
Is it possible to get a big diff of everything that changed since successful build? AFAIK Debian unstable enjoys rolling updates. Maybe there's some kind of repository which specifies current state of packages and it's possible to rollback in time? I'm not familiar with Debian internal kitchen.

**Comment by Kobla** [comment]
Hi, problem fixed.
New version of netbase package causes test failures.
See details in commit message.

**Comment by onovy** [comment]
PL https://github.com/eventlet/eventlet/pull/375

**Comment by temoto** [comment]
That was merged. Please, try again with latest code.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`

**Comment by temoto** [comment]
From PR conversation I assume everything is fine. Please reopen if the problem wasn't fixed.

**Comment by onovy** [comment]
yep, it's fixed and uploaded to Debian. Thanks!
