### ISSUE TITLE
Timeout deprecation error

### ISSUE THREAD

**Issue by davidszotten** [eventlet/eventlet#378]
In current master, it seems a deprecation warning has been added for `TimeoutError`. However, it looks like it may be accidentally firing too much:

```
$ python -Wall -c 'import eventlet; eventlet.Timeout()'

sys:1: DeprecationWarning: eventlet.TimeoutError is deprecated and will be removed in next version. Use eventlet.Timeout instead.
Autoupgrade: fgrep -rl 'eventlet.TimeoutError' . |xargs -t sed --in-place='' -e 's/eventlet.TimeoutError/eventlet.Timeout/'
```

**Comment by temoto** [comment]
Thanks, I didn't test enough.

**Comment by temoto** [comment]
@davidszotten 
Fix was merged in master. Please, try 

`pip install https://github.com/eventlet/eventlet/archive/master.zip`

Optimistic close. :-)

**Comment by davidszotten** [comment]
https://travis-ci.org/nameko/nameko/jobs/192331036

**Comment by temoto** [comment]
Uhm, linked build passed, I assume everything is fine?

**Comment by temoto** [comment]
This one bothers me, though. https://travis-ci.org/nameko/nameko/jobs/192331040

**Comment by davidszotten** [comment]
? It passed too...

Maybe you looked before I kicked them all off?

**Comment by temoto** [comment]
Yup, cool. Thanks for reporting this.
