### ISSUE TITLE
pypy + subprocess.PIPE broken since eventlet 0.20.0 

### ISSUE THREAD

**Issue by mattbennett** [eventlet/eventlet#384]
A TypeError is thrown when you try to capture output of a `Popen` with `subprocess.PIPE`:

```
(tmp-1209f2c647c454f)Matts-13-inch-Macbook-Pro:~ mattbennett$ pypy
Python 3.2.5 (b2091e973da6, Oct 19 2014, 18:30:58)
[PyPy 2.4.0 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import eventlet
>>>> eventlet.monkey_patch()
>>>> import subprocess
>>>> subprocess.Popen(['ping', '127.0.0.1'], stdout=subprocess.PIPE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattbennett/.virtualenvs/tmp-1209f2c647c454f/site-packages/eventlet/green/subprocess.py", line 72, in __init__
    wrapped_pipe = greenio.GreenPipe(pipe, mode, bufsize)
  File "/Users/mattbennett/.virtualenvs/tmp-1209f2c647c454f/site-packages/eventlet/greenio/py3.py", line 211, in GreenPipe
    return _open(name, mode, buffering, encoding, errors, newline, closefd, opener)
TypeError: open() takes exactly 7 arguments (8 given)
```

It works as expected on eventlet<0.20.0

**Comment by jstasiak** [comment]
You seem to be using PyPy implementing Python 3.2.5, which is not a supported Python version. I suggest upgrading PyPy to a version implementing Python 3.3.

**Comment by temoto** [comment]
@mattbennett sorry, mate, 3.2 is not going to be fixed. I suggest you upgrade to PyPy 3.7 :-)

Please write if it works on 3.3+.

**Comment by mattbennett** [comment]
I did wonder about that. Unfortunately this is the version of PyPy that Travis uses by default.

Just thought I'd raise it in case it wasn't a known bug.

**Comment by temoto** [comment]
PyPy tests are in allow failures group on Travis for this and few other reasons. In general Eventlet/PyPy support is uhm optimistic.
