### ISSUE TITLE
DNS resolution not respecting the /etc/hosts

### ISSUE THREAD

**Issue by canassa** [eventlet/eventlet#387]
The DNS resolution does not seem to be respecting the `/etc/hosts` file:

I have the following entry on my `/etc/hosts`:

```
127.0.0.1	localhost
127.0.0.1    www.google.com
```

If I try to fetch the IP using vanilla Python it works fine:

```python
import socket
print(socket.gethostbyname('www.google.com'))
127.0.0.1
```

And using eventlet:

```python
from eventlet.green import socket
print(socket.gethostbyname('www.google.com'))
172.217.17.132
```

I am using eventlet 0.20.1 and Python 3.5

This bug doesn't happens with eventlet 0.20.0

**Comment by temoto** [comment]
What OS?

**Comment by temoto** [comment]
Never mind, it reproduces on my machine.

**Comment by temoto** [comment]
Please, try again with this version.

`pip install https://github.com/eventlet/eventlet/archive/dns-387.zip`

**Comment by temoto** [comment]
@canassa thanks for uncovering this shameful regression.

**Comment by canassa** [comment]
@temoto No problem! I am glad to help! 😁 

I tested the new version and I can confirm that the bug was fixed.

**Comment by temoto** [comment]
Cool, the fix is merged into master and will be released on PyPI shortly.
