### ISSUE TITLE
monotonic does not support kqueue

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#394]
@dirkye reported this traceback on FreeBSD against master with new default hub clock set to monotonic library.

```
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 42, in get_default_hub
    import eventlet.hubs.kqueue
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/kqueue.py", line 8, in <module>
    from eventlet.hubs.hub import BaseHub, READ, WRITE, noop
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 23, in <module>
    from eventlet.support import greenlets as greenlet, clear_sys_exc_info, monotonic, six
  File "/usr/local/lib/python2.7/site-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
```

**Comment by temoto** [comment]
Introduced in #388 
Affected releases: none.

**Comment by temoto** [comment]
Upstream issue https://github.com/atdt/monotonic/issues/21

**Comment by temoto** [comment]
Upon closer inspection I found that monotonic library is supposed to support FreeBSD, so have to narrow the problem down.

**Comment by atdt** [comment]
monotonic supports FreeBSD.

**Comment by temoto** [comment]
@dirkye inevitably more information is needed. Such as printing `locals()` on each line before that RuntimeError.

**Comment by temoto** [comment]
I'm sure monotonic only masks the real problem by shadowing exception. This issue, although came first is marked as duplicate of #401 please track progress there.

**Comment by temoto** [comment]
Turns out it was import cycle.
For history: dirty workaround is to add `eventlet.sleep()` before `monkey_patch()` to initialise hub and break import cycle.
