### ISSUE TITLE
eventlet 0.20.1 is incompatible with FreeBSD

### ISSUE THREAD

**Issue by nusov** [eventlet/eventlet#396]
Hello,
The new version of eventlet is incompatible with FreeBSD OS

  File "/usr/local/lib/python2.7/site-packages/eventlet/support/greendns.py", line 82, in <module>
    EAI_NODATA_ERROR = socket.gaierror(socket.EAI_NODATA, 'No address associated with hostname')
AttributeError: 'module' object has no attribute 'EAI_NODATA'

socket.EAI_NODATA doesn't exist on FreeBSD

**Comment by temoto** [comment]
Duplicate https://github.com/eventlet/eventlet/issues/393
Fixed in master.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`
