### ISSUE TITLE
Update monotonic.py to latest version for getting IBM AIX support

### ISSUE THREAD

**Issue by bthery** [eventlet/eventlet#403]
Would it be possible to update eventlet/support/**monotonic.py** file to the latest available version from upstream monotonic: https://github.com/atdt/monotonic (version 1.3) in order to pick up support for IBM AIX?

That would be really great.
Thanks.

**Comment by temoto** [comment]
Please, try this patch.

`pip install https://github.com/eventlet/eventlet/archive/1a9b17c0f4e996490d6601b0c9896222c49bb4a1.zip`

**Comment by bthery** [comment]
Patch installed. It did the job.
On my AIX host, the exception "RuntimeError: no suitable implementation for this system" is no more.

Thanks a lot for the prompt update.

**Comment by temoto** [comment]
It's merged in master 1a9b17c . Have fun.
