### ISSUE TITLE
GreenSocket.accept does not notify_open

### ISSUE THREAD

**Issue by orishoshan** [eventlet/eventlet#405]
Hi, I've been experiencing this exception:
```RuntimeError: Second simultaneous read on fileno 21 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of GreenThread object at 0x7fd99375b050>; THAT THREAD=FdListener('read', 21, <function on_read at 0x7fd9938c2b90>, <built-in method throw of GreenThread object at 0x7fd99375b0f0>)```

The GreenSocket class currently only calls notify_open in the constructor, when creating a new socket. However, new fds are also created by GreenSocket when a new connection is accepted, and notify_open is not called for them.

Working with sockets from accept works:
* As long as you don't have multiple (synchronized) readers
* Doesn't present as a problem if your business logic can block on other events before performing a read(). If the socket closes before the other greenlet can call read(), it'll get IOClosed/EBADFD when attempting to read.

Consider the following scenario:
1. Server listens on sync socket.
2. Connection is accepted.
3. Multiple business logic greenlets are started, and multiple reads/writes to the sockets are prevented using a lock.
4. Greenlet A completes its logic, culminating in an error. After performing some I/O on other fds (e.g. notifying about the error), it closes the socket.
5. Meanwhile, while Greenlet A was performing unrelated I/O, in Greenlet B, a read() was placed on the socket, adding a read FdListener.
6. Greenlet A gracefully closes the socket (close()).
7. EXPECTED BEHAVIOR: Greenlet B's read returns with an error. But notify_close is not used, instead (according to notify_close's documentation), it is assumed notify_open will be called to remove stale FdListeners.
8. Another connection is accepted, re-using the same FD.
9. notify_opened is not called!
10. `Second simultaneous read`

Fix in PR #406.

**Comment by temoto** [comment]
Thanks for patch.
