### ISSUE TITLE
Memory usage increase after commit 9a13405598d25c76a5f9c44c8b8e584c41ec4c4f

### ISSUE THREAD

**Issue by amoralej** [eventlet/eventlet#412]
Testing OpenStack services with eventlet version v0.20.0 is showing that memory usage by processes using eventlet has increased in a very relevant way. A representative example:

For process murano-api (if this is relevant) righ after server reboot memory usage was ~ 66MB for versions < v0.20.0  and around 88MB with eventlet >= v0.20.0

Applying bisection i've found that commit https://github.com/eventlet/eventlet/commit/9a13405598d25c76a5f9c44c8b8e584c41ec4c4f is causing this memory usage increase. 

I wonder is this is a expected effect of bumping the version of dnspython or if there is something abnormal on this.

**Comment by temoto** [comment]
Let's test that dnspython change without eventlet. If it makes memory up, that's upstream bug to dnspython.

**Comment by amoralej** [comment]
Any idea about how could we test it with only dnspython?

**Comment by temoto** [comment]
@amoralej if your project is connected with eventlet only with `monkey_patch()` line, then it's easy: just remove `import eventlet` and patching and check memory usage.

If your code uses more eventlet API, then it's also easy:
- use eventlet >= 78f2ef8a81600d19d6d670803ef73747ab8d81b9 (v0.21)
- uninstall dnspython from virtualenv
- run with EVENTLET_NO_GREENDNS=yes

**Comment by amoralej** [comment]
I just tested using two scenarios:

1. Default configuration using eventlet from master (commit 0ec4df6). Process memory usage (rss) is around ~88MB pre process
2. I deployed dnspython based on the same commit bb0c9f21f4a6f56f2fe8d7c1fc991080ef89d223 and disabled greendns. Process memory usage is around 65MB which is about the same as we observed with previous versions of eventlet, before 0.20.0

So it seems that the problem is related to eventlet, right?

**Comment by temoto** [comment]
Yes, it well may be that we've introduced memory bloat somewhere.
Thank you for testing. Could you describe how to run the same test in command line terms?

**Comment by amoralej** [comment]
I'll describe my testing scenario. I'm running a openstack controller which includes multiple processes using eventlet. I'm taking one of them, "murano-api" which includes seven instances of the process, which are started using systemd. 

I've installed eventlet from commit 0ec4df6cbe1771493d112c3f893b8ac1d89b5dbf and dnspython from bb0c9f21f4a6f56f2fe8d7c1fc991080ef89d223. In both cases i did git clone + pip install.

Finally i start the service using regular systemd command:

systemctl start murano-api

And get memory usage using command "ps -eorss,pid,cmd|grep murano-api":

#  ps -eorss,pid,cmd|grep murano-api
89488 10190 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
87328 10221 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
87328 10222 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
87340 10223 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
84624 10224 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
88588 10225 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
87912 10228 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf

Then i modify systemd unit file /usr/lib/systemd/system/murano-api.service to add EVENTLET_NO_GREENDNS=yes:

[Service]
Type=simple
User=murano
ExecStart=/usr/bin/murano-api --config-file /etc/murano/murano.conf
Restart=on-failure
Environment=EVENTLET_NO_GREENDNS=yes

reload systemd using "systemctl daemon-reload" and restart the service. I run the same ps command again:

#  ps -eorss,pid,cmd|grep murano-api
65768 11194 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
64004 11209 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
64004 11210 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
64004 11211 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
60996 11212 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
66488 11213 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf
64476 11214 /usr/bin/python2 /usr/bin/murano-api --config-file /etc/murano/murano.conf

Unfortunately i couldn't get a simpler minimal reproducer for this issue.

**Comment by temoto** [comment]
Can I install openstack or murano via pip or what are the required steps?

**Comment by amoralej** [comment]
After some additional investigation, i found that the root cause seems to be https://github.com/rthalley/dnspython/commit/58e84f91047966ad36562cd19bd89c38680f3d8c
After that patch, dnspython is importing idna module which increases memory usage by ~ 25MB:

>>> import resource
>>> resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
5048
>>> import idna
>>> resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
31668
>>> 

My understanding is that this is expected and is not a bug nor a memory leak, as this memory increase is a one-time load. I'll wait for feedback before closing this issue.

**Comment by temoto** [comment]
I have nothing to add here. Thank you for doing all the work.

If you really want to cut memory you may import empty `idna` module before importing `eventlet` or `dns`. At the cost of unicode support.

**Comment by temoto** [comment]
@amoralej also I found that idna library has had quite a few memory related changes. https://github.com/kjd/idna/issues?utf8=%E2%9C%93&q=memory

Their version kjd/idna@1c7210da47fac6f3adafa66d61edf357a7389030 includes the latest memory optimization (pypi 2.3 if you are into releases).

Not scientific, but FWIW, `idna==2.5` adds only 2.4MB to maxrss on my laptop.

**Comment by amoralej** [comment]
Thanks for the hing, i just tested with idma==2.3 and memory usage is much lower:

```
>>> import resource
>>> resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
5048
>>> import idna
>>> resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
5892
>>> 
```

I'll try to find out if we can update it in CentOS/RDO

**Comment by amoralej** [comment]
I'm closing this issue as the actual problem is in idna module and has already been fixed upstream.

Thanks for your help.
