### ISSUE TITLE
DeprecationWarning: 'U' mode is deprecated (since Python 3.4)

### ISSUE THREAD

**Issue by frexvahi** [eventlet/eventlet#422]
https://github.com/eventlet/eventlet/blob/master/eventlet/support/greendns.py#L183
```with open(self.fname, 'rU') as fp:```

https://docs.python.org/3/library/functions.html#open

**Comment by frexvahi** [comment]
Since `strip()` is always called on the result, it should be OK just to remove the 'U'.

**Comment by temoto** [comment]
Thank you.

**Comment by frexvahi** [comment]
Also, looking at the rest of that code, it only skips comments where the '#' is the first character on the line

**Comment by frexvahi** [comment]
from `man 5 hosts` on Linux: 

> Text from a "#" character until the end of the line is a comment, and is ignored.
