### ISSUE TITLE
Inheritance of Queue within eventlet is not working properly

### ISSUE THREAD

**Issue by peter-wangxu** [eventlet/eventlet#443]
In normal python, it's possible to create customized queue by inheriting the `Queue.Queue`
see Queue.py:
https://github.com/python/cpython/blob/11225753a89c2907bb717e6c050fe907e5e11829/Lib/queue.py#L82
```python
    def qsize(self):
        '''Return the approximate size of the queue (not reliable!).'''
        with self.mutex:
            return self._qsize()
```
user can hook the _qsize() to return the size of the customized queue.

while checking the event queue implementation:
```python
    def qsize(self):
        """Return the size of the queue."""
        return len(self.queue)
```
it's impossible to inherit `Queue`, since the `_qsize()` is not called by the `qsize`, 

Can we make the best effort to keep the compatibility with standard python?

**Comment by temoto** [comment]
It is common practice in Python: names starting with underscore are private and may change behavior or be deleted without warning.

* Your best option is to avoid subclassing Queue altogether. If your sub-queue size is different, maybe you're making something using queue, as in `class Thing: q = Queue()`
* Next best option is to override `qsize`, not private `_qsize`.
