### ISSUE TITLE
greendns incorrectly treats /etc/hosts as case sensitive

### ISSUE THREAD

**Issue by stefannica** [eventlet/eventlet#458]
Currently greendns processes hostnames in the /etc/hosts file as case sensitive, which is incorrect.

A simple way to reproduce this:
 * have a hostname added to /etc/hosts including uppercase letters (e.g. deployerincloud-ccp-vip-KEY-API-mgmt')
 * the following monkey-patched getaddrinfo from eventlet-0.20.0 fails: 

```
from eventlet.support.greendns import getaddrinfo
getaddrinfo(**{'host': 'deployerincloud-ccp-vip-key-api-mgmt', 'flags': 0, 'family': 0, 'proto': 0, 'socktype': 1, 'port': 5000}) 
```
while the following socket getaddrinfo is working fine: 

```
from socket import getaddrinfo
getaddrinfo('deployerincloud-ccp-vip-key-api-mgmt', 5000, 0, 1, 0, 0)
```

**Comment by temoto** [comment]
@stefannica fix was merged in master a98bddd75c51ee59b87273614ba1e3a0aad45d45

Thanks to @rhafer .
