### ISSUE TITLE
RFC6455WebSocket.close didn't release socket fd when socket timeout raised

### ISSUE THREAD

**Issue by de1o** [eventlet/eventlet#474]
I have a flask-socketio app which leak fd each time the websocket server connection timeout, which is caused by the engineio's ping_timeout.

When fd leak occurs, `lsof -p $pid` show some rows like 

`python  24648  ...  128u  sock       0,6      0t0 ... can't identify protocol` 

and if I use strace to show the process's system call, only `shutdown` been called on fd 128 but not `close`

Here is my environment: 

OS: CentOS release 6.9
Python: 2.7.9
eventlet: 0.22.0
flask-socketio: 2.9.3

and here is how I reproduce the leak:

using a socket.io client, say the [python version](https://github.com/invisibleroads/socketIO-client)，remove all ping related code in it, so the connection will be timeout after 60 seconds by default.

```python
# client code
from socketIO_client import SocketIO, BaseNamespace

sio = SocketIO('localhost', 5004)

class ChatNamespace(BaseNamespace):

    def on_aaa_response(self, *args):
        print('on_aaa_response', args)

chat_namespace = sio.define(ChatNamespace, '/chat')
chat_namespace.emit('message', 'hello')
sio.wait()
```
Once the socket.timeout raised, `RFC6455WebSocket.close()` will be called. After that, the socket's fd remained as "can't identify protocol" in lsof output.

The timeout traceback is the same as these in #456 .

I try to call `self.socket.close()` directly in `RFC6455WebSocket.close()` instead of `self.socket.shutdown()` then `self.socket.close()`, and the socket seems closed properly. But I don't know why, does anybody know something about this issue? Thanks!

**Comment by temoto** [comment]
Thanks for bug report, the issue is clear.

Please show strace shutdown arguments.

**Comment by de1o** [comment]
Hi temoto,

the strace shutdown output is like: `24648 shutdown(128, SHUT_WR)            = 0`

Thanks.

**Comment by temoto** [comment]
Please, try this patch.

`pip install https://github.com/eventlet/eventlet/archive/d141c05ea2c6c23c184dd1c0fb5352dcf6819a28.zip`

**Comment by de1o** [comment]
Use shutdown(fd, SHUT_RDWR) and the fd still leaked, I tried this earlier and confirmed again just now.

**Comment by temoto** [comment]
Oh well, I hoped for easy fix. Will dig deeper.

**Comment by de1o** [comment]
Sorry, something to correct, I said call `self.socket.close()` directly can close socket properly which is wrong. `socket.close` also can not release the socket, so it remains ESTABLISHED and when I grep the string "can't identify protocol" I missed that fd.

So for now it seems when eventlet raise the timeout from Timer, the RFC6455WebSocket.socket object can not been garbage collected? Is it possible that socket is referenced somewhere?

**Comment by temoto** [comment]
Maybe it is referenced, I did other things today and didn't debug this yet.

**Comment by temoto** [comment]
@de1o who sets 60 second timeout?

**Comment by temoto** [comment]
I tried with server-initiated timeout and it works as intended (on OSX though).

Flow is like so:
```
client : connect, GET /path Upgrade: websocket
server: 101 Switching Protocols, socket.settimeout(0.5)
client: ... (wait)
server: gets socket.error on recv, socket is closed, file descriptor is released
```

**Comment by de1o** [comment]
It the socketio server that using eventlet set the 60s timeout， I tested on macOS the fd turned to CLOSED state in lsof result, emm. Thanks, I will do more test.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by de1o** [comment]
Ah, sorry temoto, after hours of digging, I found it might a bug in [engineio](https://github.com/miguelgrinberg/python-engineio), a [queue.join](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/socket.py#L120) whose content is [None] without consumer blocked the closing of an engineio Socket when timeout raised, so the reference to fd keeped and fd can not be gc.
