### ISSUE TITLE
Redirect traceback.print_exc() to Logging

### ISSUE THREAD

**Issue by Patchett** [eventlet/eventlet#477]
Hello, I am using eventlet's spawn_n() method to do some threading. I can see from the implementation here that it prints a stack trace if the method you run throws an exception: https://github.com/eventlet/eventlet/blob/79292bd16a6a1384d8c3d11bcefa40eb53bbeae4/eventlet/greenpool.py#L91-L93

This stack trace is going to stderr. But the logging for everything else in my program goes to a file using WatchedFileHandler. This causes the stack traces to not be shown in the the log file where the rest of the logging for my application takes place which is causing some problems.

Is there a way to get the stack traces from eventlet to print to the same file that the rest of my application logs to rather than printing to stderr?

Here is the logging conf that I currently use:

```[loggers]
keys = root

[handlers]
keys = watchedfile

[formatters]
keys = default

[logger_root]
level = INFO
handlers = watchedfile

[handler_watchedfile]
class = handlers.WatchedFileHandler
args = ('my_log.txt',)
formatter = default

[formatter_default]
format = %(asctime)s %(levelname)s [%(name)s] %(pathname)s:%(funcName)s:%(lineno)s %(message)s```

**Comment by temoto** [comment]
The key thing here is what you observe happens with eventlet.greenpool.DEBUG enabled (by default). And it prints traceback of **uncaught exceptions**. Things you should've wrapped in try/except. Without that safeguard debug print_exc, you'd have errors that are just lost. Forgetting about errors is bad.

```
def fun():
  try:
    do_your_work
  except Exception:
    log.exception("hello from greenpool")

pool = eventlet.GreenPool()
pool.spawn(fun)
pool.spawn(fun)
pool.waitall()
```
