### ISSUE TITLE
eventlet import_patched doesn't honor PEP 302 import hooks

### ISSUE THREAD

**Issue by nat-goodspeed** [eventlet/eventlet#480]
This is part of (e.g.) https://github.com/miguelgrinberg/python-socketio/issues/35#issuecomment-373960551 : [PyInstaller](https://www.pyinstaller.org/) has trouble with applications importing eventlet.

I know of two different problems.

One is that, in one-file mode, PyInstaller's boot loader uses [PEP 302](https://www.python.org/dev/peps/pep-0302/) import hooks to intercept dynamic imports. Its hook extracts the desired module from the packed file into a temp directory indicated in `sys._MEIPASS` and then loads it from there. But since the `__import__()` calls in `patcher.py` bypass import hooks, the boot loader doesn't extract modules (attempted to be) imported by `import_patched()`. They're not present in the temp directory.

The other, as indicated in the python-socketio issue comment linked above, is that in the PyInstaller one-file frozen environment, `os.path.dirname(__file__)` indicates a different directory than `sys._MEIPASS`.

In https://github.com/eventlet/eventlet/issues/7, [flub](https://github.com/eventlet/eventlet/issues/7#issuecomment-19206475) and [graingert](https://github.com/eventlet/eventlet/issues/7#issuecomment-19213338) suggest the idea of using `importlib.import_module()` instead of plain `__import__()`, potentially engaging import hooks. I will try to fix both problems noted above. I will submit a pull request referencing this github issue, but I wanted to create the issue first so I can reference it in the pull request.

Naturally, tinkering with the `import_patched()` machinery is likely to require some tweaks before all tests pass. Please bear with me during this process.

**Comment by temoto** [comment]
Thanks for taking on this hard problem.

> but I wanted to create the issue first so I can reference it in the pull request.

Pull request concept is an issue enough over simple patch exchange. Feel free to skip any intermediate bullshit next time.

**Comment by nat-goodspeed** [comment]
Okay, thanks. Of course I want to Do It Right.

I note that one useful side effect of creating an issue is that github cross-referenced that issue in the two that I mentioned above.

**Comment by nat-goodspeed** [comment]
Evidently my premise was mistaken: __import__() does honor PEP 302 import hooks. This issue is a non-issue.

**Comment by nat-goodspeed** [comment]
class DumbFounder(object):
        def find_module(self, fullname, path=None):
            print("find_module({}, {})".format(fullname, path))
            return None
    sys.meta_path.append(DumbFounder())
    __import__('eventlet')

**Comment by temoto** [comment]
Thank you.
