### ISSUE TITLE
Eventlet monkey patched SSL context does not observe environment PYTHONHTTPSVERIFY=0 or PEP 493 settings

### ISSUE THREAD

**Issue by Tehsmash** [eventlet/eventlet#484]
Eventlet monkey patches the default SSL context and as a result circumvents the logic added to python's ssl.py to change the default SSL verification behaviour here https://github.com/python/cpython/blob/2.7/Lib/ssl.py#L508-L518

**Comment by temoto** [comment]
Thank you. Let's continue in pull #485 it seems to contain more value.

For future: there is no bureaucracy on creating issue and pull request here. Any way (issue, email, messengers, call) to submit idea is great and enough. Any way to transport a patch is great.
