### ISSUE TITLE
#468 fix not pep 0333 compliant under cpython2

### ISSUE THREAD

**Issue by cboylan** [eventlet/eventlet#488]
The fix for #468 made the wsgi environment string pep 0333 compliant under cpython3 by coercing those unicode strings to be latin1. In doing so they are now unicode strings under cpython2 as well. Reading pep 0333 only python implementations where "the str or StringType type is in fact Unicode-based" may use a unicode string type with this subset restriction. Otherwise "All encoding/decoding must be handled by the application; all strings passed to or from the server must be standard Python byte strings, not Unicode objects."

This likely wouldn't be an issue except that python2 urllib path quoting methods seem to only operate on byte strings and not unicode strings (the lookup tables don't have keys for unicode strings, only bytestrings). The end result is that the fix for #468 breaks python2 urllib methods on these environment values. (Example of this happening at https://gist.github.com/notmyname/43413494ba62b22ba3d704a495563b74)

Considering this original change was made to be pep 0333 compliant, encode_dance() should be updated to return bytes on cpython2.

**Comment by temoto** [comment]
Thank you. This is interesting, I just encode dance was copied (supposedly) verbatim from Flask, I assumed Armin figured all unicode stuff. Probably copied wrong way.

**Comment by dbishop** [comment]
@cboylan if you have time, could you include the repr of `self.environ['PATH_INFO']` and `type(self.environ['PATH_INFO'])`?

**Comment by dbishop** [comment]
@cboylan nevermind, I fixed my own confusion.  This helped me see the light (in a py2 repr)
```
>>> s = u'teh\u062abomb'.encode('utf8')
>>> sl = s.decode('latin1')
>>> repr(s)
"'teh\\xd8\\xaabomb'"
>>> repr(sl)
"u'teh\\xd8\\xaabomb'"
>>> 
```

**Comment by temoto** [comment]
@nat-goodspeed would you please take a look?

**Comment by nat-goodspeed** [comment]
Um, digit transposition? My pull request is #486, not #468.

**Comment by temoto** [comment]
Yes, sorry, I misread digits.
