### ISSUE TITLE
error: cannot switch to a different thread

### ISSUE THREAD

**Issue by kushalagrawal** [eventlet/eventlet#492]
Hi,
We are facing an sporadic issue while using eventlet library. In our scenario we are calling a method using `tpool.execute(foo, arg1)`
In callee method we are making a rest call to external service using `httplib`.  But sometime it is able to complete the rest call but not able to complete the foo method execution and fail with the error.

> glare-api: File "/usr/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
> glare-api: timer()
> glare-api: File "/usr/lib/python2.7/site-packages/eventlet/hubs/timer.py", line 58, in __call__
> glare-api: cb(*args, **kw)
> glare-api: File "/usr/lib/python2.7/site-packages/eventlet/semaphore.py", line 147, in _do_acquire
> glare-api: waiter.switch()
> glare-api: error: cannot switch to a different thread

**Comment by temoto** [comment]
Do you use eventlet API in function `foo`? At this time it's not supported.

**Comment by kushalagrawal1** [comment]
No, We are only using it to execute a function `foo` (`pre_upload_hook` in real code)  using tpool.execute.
Here is the link to code.
https://github.com/openstack/glare/blob/master/glare/engine.py#L608-L609

Inside `foo`/`pre_upload_hook` we are calling a service using python httplib not eventlet.

**Comment by temoto** [comment]
I believe OpenStack does global monkey-patching. If `socket` module is monkey-patched, then effectively, httplib will use eventlet IO, but there is no need for tpool then since httplib would be "greenthread cooperative" already. Here's how you can verify patching:

`print('is it yes?', eventlet.patcher.is_monkey_patched('socket'))`

**Comment by kushalagrawal1** [comment]
Hi @temoto ,  I verifed by writing in our project code. `eventlet.patcher.is_monkey_patched('socket'))` is returning `True`. which means 'socket' is monkey_patched.

Though it is not only http call in that method but we are also doing other operations (like read file from file description etc.).

One more point is if it not supported,  it should fail continuously but for us, it happens very rarely.

If we something like thing,  may it  help ?
https://github.com/openstack/mistral/blob/master/mistral/cmd/launch.py#L22

**Comment by temoto** [comment]
* File IO makes sense in tpool.
* It will fail every time, yes. Maybe problem is somewhere else.
* Please try this: `httplib = eventlet.patcher.original('httplib')` it will be tpool friendly **if httplib.socket** will be unpatched, verify with `hasattr(httplib.socket, '__patched__')`

**Comment by kushalagrawal1** [comment]
will this `httplib = eventlet.patcher.original('httplib')` work, In case if are using `requests` instead of `httplib` ?

**Comment by temoto** [comment]
Yes, you'd need to change it to `requests = ...original('requests')`.
