### ISSUE TITLE
Error while using webob if eventlet.mokey_patched(os=true)

### ISSUE THREAD

**Issue by kushalagrawal1** [eventlet/eventlet#493]
Hi @temoto 
I am using  `eventlet.patcher.monkey_patch(all=False, socket=True, time=True, select=True, thread=True, os=True, MySQLdb=True)` in our code.

In our test code we using webob `best_match` function from  `webob.acceptparse.AcceptLanguage`

https://github.com/openstack/glare/blob/master/glare/tests/unit/test_wsgi.py#L253

Which is giving us exception like this
>    b'Traceback (most recent call last):'
>    b'  File "/home/stack/otherrepo/glare/.tox/py35/lib/python3.5/site-packages/mock/mock.py", line 1297, in patched'
 >   b'    arg = patching.__enter__()'
 >   b'  File "/home/stack/otherrepo/glare/.tox/py35/lib/python3.5/site-packages/mock/mock.py", line 1369, in __enter__'
 >   b'    original, local = self.get_original()'
 >   b'  File "/home/stack/otherrepo/glare/.tox/py35/lib/python3.5/site-packages/mock/mock.py", line 1343, in get_original'
 >   b'    "%s does not have the attribute %r" % (target, name)'
 >   b"AttributeError: <class 'webob.acceptparse.AcceptLanguage'> does not have the attribute 'best_match'"

**Comment by temoto** [comment]
And there is no problem with best_match without eventlet?

I think, this is a problem of real error shadowed by another "manually raised" exception. Find where AttributeError is raised and see if it catches other, remove try/except proxy to see real problem.

**Comment by kushalagrawal1** [comment]
I assume from your previous comments that you understand OpenStack code. Here is a review request which we created it to enable to use monkey_patched os dependency.
https://review.openstack.org/#/c/569761/

Because of that test case failed in the annotation itself.
https://github.com/openstack/glare/blob/master/glare/tests/unit/test_wsgi.py#L253

**Comment by temoto** [comment]
I am only familiar with OpenStack code based on talk in similar issues.

Here's the relevant part: Find where AttributeError is raised (mock.py get_original) and see if it catches other, remove try/except proxy to see real problem.

**Comment by kushalagrawal1** [comment]
Thanks, it worked :)
closing the issue
