### ISSUE TITLE
py3.7 deadlock with monkeypatch of stdlib thread modules + use of ThreadPoolExecutor

### ISSUE THREAD

**Issue by coreycb** [eventlet/eventlet#508]
There's a py3.7 deadlock when eventlet.patcher.monkey_patch(thread=True) is used with concurrent.futures.ThreadPoolExecutor().

Here's some sample code that deadlocks: https://bugs.python.org/file47709/bpo34173-recreate.py

Notice that it does not deadlock if the monkey_patch is removed.

I'm not sure if this is a bug in eventlet or concurrent.futures of the py3.7 standard library. I also have a py3.7 issue opened here: https://bugs.python.org/issue34173

If I switch /usr/lib/python3.7/concurrent/futures/thread.py back to use queue.Queue() (which was the case for py3.6) the deadlock goes away. This was changed in py3.7 from Queue to SimpleQueue:
```
- self._work_queue = queue.Queue()
+ self._work_queue = queue.SimpleQueue()
```

**Comment by temoto** [comment]
Eventlet and asyncio solve same problem. Why would you want concurrent.futures and eventlet in same application?

**Comment by coreycb** [comment]
@temoto I'll pose that question to folks from affected upstream projects who are more knowledgeable than I am. I'm just trying to get this packaged for Ubuntu.

**Comment by coreycb** [comment]
I've posed some questions upstream on the openstack-dev mailing list. You can follow along here: http://lists.openstack.org/pipermail/openstack-dev/2018-July/132473.html

Note that further testing has shown that https://docs.openstack.org/futurist/latest/reference/index.html#futurist.GreenThreadPoolExecutor does not deadlock.

**Comment by harlowja** [comment]
An idea (it's ok if it gets shot down), but it might be useful to suck `GreenThreadPoolExecutor` into eventlet itself (vs having it in futurist). I don't mind if the code that I/others wrote @ https://github.com/openstack/futurist/blob/master/futurist/_futures.py#L306-L491  gets taken or mutated or other...

**Comment by temoto** [comment]
@harlowja thank you, I absolutely agree that we should host eventlet related hacks in eventlet source tree.

**Comment by coreycb** [comment]
@temoto Yes, based on @harlowja's input it is an acceptable workaround to use GreenThreadPoolExecutor with eventlet.

**Comment by harlowja** [comment]
Cool, feel free to take it (if u want); just let me know if/when that happens (likely futurist will have to proxy to that new implementation for some time for deprecation purposes).

**Comment by untitaker** [comment]
I found this issue because I saw that eventlet does not patch SimpleQueue at all, which seems to be the cause of this. Why does it do that?
