### ISSUE TITLE
DNS resolution will try to contact nameservers even there's one IPv4 or IPv6 entry on hosts file

### ISSUE THREAD

**Issue by danalsan** [eventlet/eventlet#511]
Given that we have a system with  an IPv4 entry on /etc/hosts for overcloud.internalapi.localdomain, and executing the following script, the second call (with eventlet performing the DNS resolution) will take 30 seconds while the first one will return straight away.

```
import eventlet
import socket
import time

print socket.getaddrinfo('overcloud.internalapi.localdomain', 80, 0, socket.SOCK_STREAM)
print time.time()
eventlet.monkey_patch()
print socket.getaddrinfo('overcloud.internalapi.localdomain', 80, 0, socket.SOCK_STREAM)
print time.time()
```

The second call takes 30 seconds:

> $ python test.py
> [(2, 1, 6, '', ('192.168.1.9', 80))]
> 1533203446.53
> [(2, 1, 6, '', ('192.168.1.9', 80))]
> 1533203476.54

I think that eventlet should not change the system behavior when it comes to address resolution and should not attempt to contact nameservers if one entry is found on hosts file as getaddrinfo() apparently does.

**Comment by danalsan** [comment]
@temoto can we get a tag with the fix for this issue please? Thanks!

**Comment by temoto** [comment]
@danalsan v0.24.1 and also just uploaded to PyPI.

**Comment by danalsan** [comment]
Thanks a lot!
