### ISSUE TITLE
Maintainer call

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#513]
Current state of Eventlet, IMHO:
- widely used
- has few really important problems and about hundred "would be nice to fix" ones
- no active development from "core team"
- steady rate of patches from community
- notorious for months and even years old issues and pull requests -- which is completely my fault
- if things go bad, only @jstasiak has access to merge on Github and upload releases to PyPI

I wish to leave this project. It would be good if group of people would emerge to continue active development, or at least devote more time into handling issues and patches. Please speak here to get familiar and have public clarity on future plans.
- whether you represent interests of a business
- how you think things should change (or not)
- what are you going to do about it

Please share link here with whoever you think would be interested.

There's about 12$ yearly expenditure on eventlet.net domain, new maintainer group should take it or abandon domain. Asking public for donations is bad idea.

Ping @jstasiak @nat-goodspeed @vstinner @flub

**Comment by nat-goodspeed** [comment]
I'm sorry to hear you're stepping down! You have been a good gatekeeper, in my experience.

"What am I going to do about it" - can't answer off the cuff.

**Comment by flub** [comment]
Hey, thanks for the years of great work!  I'm afraid I haven't used eventlet myself for quite some time as you probably guessed from my activity.

With pytest we at some point decided to give anyone who's got one pull request merged developer access.  Together with a CONTRIBUTING.txt file describing when to merge PRs it in theory gives people who care about maintenance the power to do so.  This probably also needs a not too difficult RELEASEING.txt file as well.  The tricky bit is pypi access as pypi does not make this easy, but apparently pytest is now released simply by pushing a git tag, not sure how much work it is to set that up.

I don't actually know if this would work, with pytest we still have 1-2 ppl driving the releases and doing the bulk of maintenance work.  But it makes it easier for new people to get the maintenance they want at least in theory.

**Comment by vstinner** [comment]
Sorry, but I'm not interested to maintain eventlet.

**Comment by nat-goodspeed** [comment]
@temoto, as you might have guessed, I am a fan of, and user of, eventlet. I want it to continue to be maintained. I don't know what responsibilities that implies. 

I assume it means monitoring issues and pull requests, making a judgment call on each pull request (with guidance to the submitter as needed), deciding when a new release is warranted, and ... working some kind of magic to effect a Release.

If you would explain what else is involved, and what buttons you must push to perform a release, the prospect might be less scary.

**Comment by nat-goodspeed** [comment]
Just for example, you probably had to "do something" to initiate CI testing under Python 3.7 as that version was coming up for release. What were you watching, and what did you have to do?

**Comment by temoto** [comment]
@nat-goodspeed 
- on responsibilities: what you said + eventlet.net domain
- on release send me your PyPI username, then `bin/release` in eventlet source directory is designed for interactive dialog with confirm at each important step
- as of 2018-07 we use Travis for CI, study at https://docs.travis-ci.com/ edit config in eventlet source root `.travis.yml` example: https://github.com/eventlet/eventlet/commit/6c6cfc565f743c9de88fd131ec392cfb2162a984#diff-354f30a63fb0907d4ad57269548329e3

**Comment by temoto** [comment]
@nat-goodspeed `eventlet.net A` records point to Github Pages and yes, push to gh-pages is single action required to deploy website.

**Comment by temoto** [comment]
ping @smerritt

**Comment by temoto** [comment]
@nat-goodspeed send me your PyPI username for release access
temotor@gmail.com

**Comment by nat-goodspeed** [comment]
@beltran, yes, it would be fabulous if you would sift through issues and pull requests. Which most urgently need action? What, if anything, still needs work with those?

**Comment by kashirin-alex** [comment]
@temoto 
I'll be glad to be around, while so It is a question of time available in future.
On my side, I try to keep [Hypertable](https://github.com/kashirin-alex/hypertable) steady [Latest Changes](https://github.com/kashirin-alex/hypertable/blob/master/CHANGES)
While for me, Both(Eventlet and Hypertable) are at no less of importance, my project [Thither.Direct](https://Thither.Direct) runs on py(python/pypy) with eventlet and I have no reasons to change anything but only to improve further.
You are welcome to ask of anything, I'll definitely answer wither with can or cannot.

**Comment by vstinner** [comment]
@temoto: I have been asked if eventlet got a new maintainer. Sadly, I'm not sure about the answer after reading this issue. The issue is still open. Did someone show up and got the permissions to be the new maintainer?

**Comment by temoto** [comment]
@kashirin-alex no, thanks.

@vstinner new maintainers: @jstasiak and @nat-goodspeed
