### ISSUE TITLE
Websocket connections are not closed properly when we use them with WSGI middleware.

### ISSUE THREAD

**Issue by Hardtack** [eventlet/eventlet#543]
I'm getting following error whenever websocket connections are closed.

``` python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eventlet/wsgi.py", line 580, in handle_one_response
    write(b'')
  File "/usr/local/lib/python3.6/site-packages/eventlet/wsgi.py", line 472, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()
```

More precisely, I'm using [Flask-SocketIO](http://flask-socketio.readthedocs.io) with eventlet, with [Flask integration of sentry-sdk](https://docs.sentry.io/platforms/python/flask/).

As I see it, the problem occurred by following reason.

In `eventlet.websocket`, you made a special object called `ALREADY_HANDLED` which makes special functionalities for websocket handlers
https://github.com/eventlet/eventlet/blob/05d613d8ed123b87f64f8d1987968c5bf825b07a/eventlet/websocket.py#L136-L138

And, in `eventlet.wsgi`

The websocket-specific functionalities are handled by type of the return value of WSGI app. 

https://github.com/eventlet/eventlet/blob/05d613d8ed123b87f64f8d1987968c5bf825b07a/eventlet/wsgi.py#L547-L550

However, In sentry-sdk, the plugin wraps the WSGI responses (which are iterable objects) with there wrapper called [`_ScopedResponse`](https://github.com/getsentry/sentry-python/blob/3ac9097165180b4a53e5d483f73a3abfc2d239e6/sentry_sdk/integrations/wsgi.py#L134).

This is fine, since [PEP 3333](https://www.python.org/dev/peps/pep-3333/) specifies the return value of WSGI app just have to be an iterable object.

But it breaks the type check on `eventlet.wsgi`. So eventlet doesn't finish at the if statement, and emits the above error message.

I think, you may have to use another way to handle websocekt specific features.

**Comment by jamesharding** [comment]
I am encountering the exact same issue. @Hardtack Did you manage to find a workaround?

**Comment by Hardtack** [comment]
@jamesharding I already sent a [pull request](https://github.com/eventlet/eventlet/pull/544) that fix this issue, but it's not be merged yet.

**Comment by ranihorev** [comment]
@Hardtack it looks like it was approved. It'd be great if you'll merge it :)
