### ISSUE TITLE
Tests fail on Python 3.7

### ISSUE THREAD

**Issue by MeggyCal** [eventlet/eventlet#576]
I am trying to launch tests of version 0.25.0 and I encounter many failures like this one:
[   13s] ERROR: test_count (tests.zmq_test.TestQueueLock)
[   13s] ----------------------------------------------------------------------
[   13s] Traceback (most recent call last):
[   13s]   File "/home/abuild/rpmbuild/BUILD/eventlet-0.25.0/tests/__init__.py", line 173, in setUp
[   13s]     self.timer = eventlet.Timeout(self.TEST_TIMEOUT,
[   13s] AttributeError: module 'eventlet' has no attribute 'Timeout'
[   13s] 

And also this one:
[   13s] FAIL: tests.tpool_test.test_exception_leak
[   13s] ----------------------------------------------------------------------
[   13s] Traceback (most recent call last):
[   13s]   File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
[   13s]     self.test(*self.arg)
[   13s]   File "/home/abuild/rpmbuild/BUILD/eventlet-0.25.0/tests/tpool_test.py", line 373, in test_exception_leak
[   13s]     tests.run_isolated('tpool_exception_leak.py')
[   13s]   File "/home/abuild/rpmbuild/BUILD/eventlet-0.25.0/tests/__init__.py", line 378, in run_isolated
[   13s]     run_python(prefix + path, **kwargs)
[   13s]   File "/home/abuild/rpmbuild/BUILD/eventlet-0.25.0/tests/__init__.py", line 371, in run_python
[   13s]     assert ok, 'Expected single line "pass" in stdout'
[   13s] AssertionError: Expected single line "pass" in stdout

Could you please tell me what am I doing wrong? I guess it is some misconfiguration on my side...

I am running on recent openSUSE Tumbleweed, I have reasonably new versions of dnspython, greenlet, monotonic and six (e. g. they meet your minimal requirements). Thank you in advance.

**Comment by itamarst** [comment]
There were indeed problems with passing tests on 3.7, but we just dropped 3.7 so going to close this. Apologies for the very late response!
