### ISSUE TITLE
missing attibute '_is_main_interpreter' (python 3.9 support)

### ISSUE THREAD

**Issue by nirik** [eventlet/eventlet#604]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1794283

Currently building with python3.9 prereleases works, but tests fail. 

```tests.greendns_test.test_reverse_name ... Program /builddir/build/BUILD/eventlet-0.25.1/tests/isolated/greendns_from_address_203.py output:
---
Traceback (most recent call last):
  File "/builddir/build/BUILD/eventlet-0.25.1/tests/isolated/greendns_from_address_203.py", line 6, in <module>
    eventlet.monkey_patch(all=True)
  File "/builddir/build/BUILD/eventlet-0.25.1/eventlet/patcher.py", line 285, in monkey_patch
    modules_to_patch += modules_function()
  File "/builddir/build/BUILD/eventlet-0.25.1/eventlet/patcher.py", line 435, in _green_thread_modules
    from eventlet.green import threading
  File "/builddir/build/BUILD/eventlet-0.25.1/eventlet/green/threading.py", line 22, in <module>
    eventlet.patcher.inject(
  File "/builddir/build/BUILD/eventlet-0.25.1/eventlet/patcher.py", line 100, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/usr/lib64/python3.9/threading.py", line 37, in <module>
    _is_main_interpreter = _thread._is_main_interpreter
AttributeError: module 'eventlet.green.thread' has no attribute '_is_main_interpreter'
---
FAIL
```

This was apparently added in https://bugs.python.org/issue37266
(A bunch of the other tests also fail the same way, full list can be seen in: https://download.copr.fedorainfracloud.org/results/@python/python3.9/fedora-rawhide-x86_64/01309177-python-eventlet/build.log.gz

**Comment by metalalive** [comment]
I also run into the same issue with Python 3.9.0a5 . According to [this commit](https://github.com/python/cpython/commit/14d5331eb5e6c38be12bad421bd59ad0fac9e448#diff-b250d3d0e0d909784a67083e9069ce507513a67e8514a011e2f364027e25e0b0L35) in cpython , they removed access to internal `_is_main_interpreter` function , so the question would not happen if you can work with python version  after that commit.

Or it seems harmless to simply comment off everything related to `_is_main_interpreter` in your `/PATH/TO/PYTHON/Lib/threading.py` , which might not be perfect solution but it works for me.

**Comment by temoto** [comment]
**Affected versions: CPython 3.9.0a1 to 3.9.0a6 (pre-releases)**

**Workaround: use CPython >= 3.9.0a6**

So basically, there were few unreleased Python versions with new symbol `threading._is_main_interpreter` and it's gone then.

I am inclined to just call it unfortunate inconvenience and wontfix.

@jstasiak ?

**Comment by jstasiak** [comment]
I think if anyone sent a patch for this we could accept it, but other than that I think it's ok to not fix it if the next CPython works fine.
