### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib2'

### ISSUE THREAD

**Issue by peterhesp** [eventlet/eventlet#606]
New to eventlets and trying it out on the python shell.
But in fails at the first hurdle.

Any ideas why?
Running on a macOS Catalina machine

>>> import eventlet
>>> from eventlet.green import urllib2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/.virtualenvs/websockets_test/lib/python3.7/site-packages/eventlet/green/urllib2.py", line 16, in <module>
    ('urllib', urllib))
  File "/Users/me/.virtualenvs/websockets_test/lib/python3.7/site-packages/eventlet/patcher.py", line 100, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
ModuleNotFoundError: No module named 'urllib2'
>>>

**Comment by telnetning** [comment]
I am new to eventlet and if I am wrong plz let me know.
  
Maybe your Interpreter is Python3.  
The `urllib2` library in Python2 has changed a lot in Python3. In Python3, this library is called `urllib` and `urlopen` is defined in `urllib.request`.  
Our code should fit into this：  
  
with Python2:    

```python2
from eventlet.green import urllib2
urllib2.urlopen()
```

But with Python3：  

```python
from eventlet.green.urllib import request
request.urlopen()
```

**Comment by marcelogrsp** [comment]
@telnetning is right. The snippet below should work.
Tested and worked with Fedora 32 and Python 3.8.3

```python
import eventlet
from eventlet.green.urllib import request

urls = [
    "https://www.google.com/intl/en_ALL/images/logo.gif",
    "http://python.org/images/python-logo.gif",
    "http://us.i1.yimg.com/us.yimg.com/i/ww/beta/y3.gif",
]


def fetch(url):
    print("opening", url)
    body = request.urlopen(url).read()
    print("done with", url)
    return url, body


pool = eventlet.GreenPool(200)
for url, body in pool.imap(fetch, urls):
    print("got body from", url, "of length", len(body))
```

Return:
```
opening https://www.google.com/intl/en_ALL/images/logo.gif
opening http://python.org/images/python-logo.gif
opening http://us.i1.yimg.com/us.yimg.com/i/ww/beta/y3.gif
done with https://www.google.com/intl/en_ALL/images/logo.gif
got body from https://www.google.com/intl/en_ALL/images/logo.gif of length 8558
done with http://us.i1.yimg.com/us.yimg.com/i/ww/beta/y3.gif
done with http://python.org/images/python-logo.gif
got body from http://python.org/images/python-logo.gif of length 2549
got body from http://us.i1.yimg.com/us.yimg.com/i/ww/beta/y3.gif of length 1874
```

**Comment by temoto** [comment]
@telnetning yes, that is correct answer, thank you.
