### ISSUE TITLE
eventlet breaks select.poll()

### ISSUE THREAD

**Issue by IamFive** [eventlet/eventlet#608]
Hi, i try to install openstack ironic on ubuntu 18.04. And eventlet lib seems breaking things. But it's wierd that others do not have this issue.

I can simply reproduce it by:

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
>>> 
>>> eventlet.patcher.monkey_patch()
>>> import select
>>> select.poll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'select' has no attribute 'poll'
>>> eventlet.version_info
(0, 25, 0)
>>> 
```

**Comment by jstasiak** [comment]
This is intentional, see f63165c0e3c85699ebdb454878d1eaea13e90553. The client code is expected to check if `select.poll` (or other method) exists and fall back to `select.select` (or use the `selectors` module that does that behind the scenes).

**Comment by IamFive** [comment]
thanks for the answer. will check why select.poll is called directly then.
