### ISSUE TITLE
missing git release tag for v0.25.2

### ISSUE THREAD

**Issue by anthraxx** [eventlet/eventlet#609]
Hey folks,

It would be awesome to keep the git tags in sync with the pypi releases. It makes it lot easier to know which release exactly is the commit in the source code tree matching the pypi released one.

cheers

**Comment by anthraxx** [comment]
@temoto @jstasiak can we please get the missing tag in git? This is required for the distro packaging, we are stuck with the previous version.

**Comment by temoto** [comment]
Sorry, it's my mistake. `bin/release` contains `git push --tags` but wasn't executed for some reason, I don't remember why now.

**Comment by anthraxx** [comment]
@temoto happens... thanks a lot for taking care :cat:
