### ISSUE TITLE
Eventlet: any type hints or stub files for static type checkers (mypy)?

### ISSUE THREAD

**Issue by jamesbraza** [eventlet/eventlet#627]
I use a static type checker ([python/mypy](https://github.com/python/mypy)) to help catch bugs early.

Currently, I am using `eventlet.queue.Queue`, and mypy reports:

```
error: Skipping analyzing 'eventlet': found module but no type hints or library stubs  [import]
```
This means that that ([source](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-type-hints-for-third-party-library)):

> mypy was able to find the module you were importing, but no corresponding type hints

I read around a bit and can't find any information on type hints/stub files for eventlet.  Is this true?  Or are there any stubs out there?

---

Versions

```
Python==3.8.2
eventlet==0.25.2
mypy==0.782
```

**Comment by jstasiak** [comment]
There are no type hints in the code and I'm unaware of any type stubs.

**Comment by jamesbraza** [comment]
Sounds good, thought it was worth an ask.

I think type hinting could be a good addition in the future, especially since there's a plan to deprecate older Python versions in https://github.com/eventlet/eventlet/issues/623

**Comment by jstasiak** [comment]
We agree. :)

**Comment by Gunni** [comment]
Reopen and fix?
