### ISSUE TITLE
0.25.2 regression: test_connect_ssl hangs

### ISSUE THREAD

**Issue by mgorny** [eventlet/eventlet#633]
Apparently the `set_nonblocking()` isn't as redundant as it seems. The new version hangs almost immediately after starting the test suite for me:

```
tests.test_run_python_timeout ... ok
tests.test_run_python_pythonpath_extend ... ok
test_001_trampoline_timeout (tests.api_test.TestApi) ... ok
test_connect_ssl (tests.api_test.TestApi) ... 
```

For comparison, in 0.25.1 the test passes almost immediately.

Reproduced with all the following:
```
$ python3.6 --version
Python 3.6.11
$ python3.7 --version
Python 3.7.8
$ python3.8 --version
Python 3.8.5
$ distro
Name: Gentoo/Linux
Version: 2.7 (n/a)
Codename: n/a
$ uname -rm
5.7.9 x86_64
```

**Comment by temoto** [comment]
Does it fail with `tox -e py37-epolls` ?

**Comment by mgorny** [comment]
I can't reproduce it with tox. However, I do can reproduce it reliably when running tests via the Gentoo package manager (Portage). I'm going to investigate further.

**Comment by mgorny** [comment]
Hmm, it seems to happen only when `PYTHONPATH` is set to point to `build/lib`. If I run it with `PYTHONPATH` unset, the test passes. This seems above my pay grade, so I'm just going to unset it in the ebuild. Feel free to close the bug if you don't have any idea why `PYTHONPATH` would be causing this (I don't have a previous version installed on my system while testing).

**Comment by temoto** [comment]
@mgorny this sounds too similar with https://github.com/eventlet/eventlet/issues/362 (maybe 5 minutes reading), basically tox tests against pinned deps and upgrading them causes interesting results.

I am very sorry that eventlet patching is so brittle. It may be not comforting but helpful that root error is very different from the exception. Usually I try to gradually reduce environment (concurrent tests, dependencies) until it doesn't reproduce.

I can dig into this if you provide reproduction instruction starting from empty VM/container/whatever.

**Comment by mgorny** [comment]
The real problem is, I can't really reproduce it outside Portage. I've tried reusing the same build directory, setting the same PYTHONPATH, calling the same command, unsharing network the same way… yet tests still pass when run manually. I can't really think of any other thing I could change to make it reproducible but Portage is a complex beast and it might be something totally unexpected.

I could try to make a simple Dockerfile spawning Portage to build it but I don't think it will be very helpful without full environment to play with Portage internals. Plus, my local Docker install seems broken x_x.

**Comment by temoto** [comment]
@mgorny ok I understand. So I'll close this issue for now and please add instruction anytime.
