### ISSUE TITLE
eventlet with Flask/SocketIO in debug mode with watchdog installed hangs on startup

### ISSUE THREAD

**Issue by mortoray** [eventlet/eventlet#634]
It appears that having the `watchdog` package installed caused eventlet to hang while starting a Flask/Flask-SocketIO server.

I am not referencing this package in the source code for the server. It's only installed for another process.

Turning off Flask debug in `socketio.run` allows the server to start.
Not calling `eventlet.monkey_patch()` allows the server to start.
Uninstalling `watchdog` allows the server to start.

I don't know how watchdog causes the issue, and I'm totally unsure of where to report such a defect. In theory, if the defect is simple, anybody with a Flask/Flask-SocketIO server using eventlet can install `watchdog` and check for the same behaviour.

The behaviour is that the server locks, doesn't server requests, and doesn't reload.  I suspect it's something with the file watching, since watchdog also watches files. But how it interferes, I don't know.

**Comment by temoto** [comment]
Please post reproduction instruction starting from empty virtualenv.

**Comment by merlinran** [comment]
Encountered the same.

**Comment by merlinran** [comment]
To reproduce, `pip install flask eventlet watchdog`, then run the following:

```python
from flask import Flask
import eventlet
eventlet.monkey_patch()

app = Flask("app")
app.run(
    debug=True,
    use_reloader=True,
    host="0.0.0.0", port=8000)
```
The presence of either `debug` or `use_reloader` will stop Flask from responding HTTP request, after connections being established.
```
➜  reproduce netstat -ltn | grep 8000
tcp4     549      0  127.0.0.1.8000         127.0.0.1.57331        ESTABLISHED
tcp4       0      0  127.0.0.1.57331        127.0.0.1.8000         ESTABLISHED
tcp4     575      0  127.0.0.1.8000         127.0.0.1.57328        CLOSE_WAIT
tcp4       0      0  127.0.0.1.57328        127.0.0.1.8000         FIN_WAIT_2
tcp4     575      0  127.0.0.1.8000         127.0.0.1.57326        CLOSE_WAIT
tcp4       0      0  127.0.0.1.57326        127.0.0.1.8000         FIN_WAIT_2
```

As mentioned, avoiding `eventlet.monkey_patch()` or simply uninstalling `watchdog` would solve this as well.

**Comment by merlinran** [comment]
BTW I encountered this because I installed `pytest-watch` in the Docker image, which depends on `watchdog`.
