### ISSUE TITLE
SSLSocket.accept fails when monkey-patched

### ISSUE THREAD

**Issue by Xandaros** [eventlet/eventlet#651]
Currently setting up a fairly simple SSL server and I wanted to use eventlet to spawn handler threads for the clients. Unfortunately, if I use `eventlet.monkey_patch`, the code stops working (with no other modification).

```
Traceback (most recent call last):
  File "./test.py", line 45, in <module>
    main()
  File "./test.py", line 38, in main
    client_sock, addr = ssl_sock.accept()
  File "/home/xandaros/workspace/company/test/server/venv/lib/python3.8/site-packages/eventlet/green/ssl.py", line 405, in accept
    new_ssl = type(self)(
  File "/home/xandaros/workspace/company/test/server/venv/lib/python3.8/site-packages/eventlet/green/ssl.py", line 79, in __new__
    ret = _original_wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 1393, in wrap_socket
    raise ValueError("certfile must be specified for server-side "
ValueError: certfile must be specified for server-side operations
```

The monkey-patching happens right at the top of the file:
```python
import eventlet
eventlet.monkey_patch()
```

To create the SSL socket, I don't use `ssl.wrap_socket`, but instead create my own SSL socket and load the certificates:
```python
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    context.load_cert_chain(certfile="server.crt", keyfile="server.key")
```

Then I wrap the socket:
```python
    sock = socket.create_server(('0.0.0.0', 1234))
    ssl_sock = context.wrap_socket(sock, server_side=True)
```

And finally, I call `ssl_sock.accept()`, which causes aforementioned error when a client connects; but only if the environment is monkey-patched.

**Comment by temoto** [comment]
@Xandaros thank you, that's a shame to fail such basic interaction. Sorry.

I've found the culprit of problem, it's a one line fix, but I'm afraid it may potentially break a lot of other things. So asking you to participate in as extensive testing as you can afford before it may be released to public. Please read shortest instruction and report problems here https://github.com/eventlet/eventlet/pull/655

**Comment by Xandaros** [comment]
Due to time constraints I had to move away from eventlet, so I don't actually have a use-case to test this on, sorry.

At this point it would be too much work to move everything back to eventlet, especially when using an unpublished version we wouldn't be able to deploy.

**Comment by temoto** [comment]
@Xandaros ok anyway thanks for reporting this. Good job with development speed. Just curious, have you done it on asyncio then?

**Comment by Xandaros** [comment]
No, we switched to gevent.

**Comment by temoto** [comment]
Since it's a change in important ssl code path, fix was released separately from other changes. 0.29.0 on PyPI.
