### ISSUE TITLE
ModuleNotFoundError: No module named 'OpenSSL.tsafe'

### ISSUE THREAD

**Issue by bneradt** [eventlet/eventlet#671]
Using the following Pipenv:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"

[packages]
pyOpenSSL = "*"
eventlet = "*"

[requires]
python_version = "3"
```

Create a pipenv using that file:

```
$ pipenv install
Creating a virtualenv for this project…
Pipfile: /tmp/Pipfile
Using /usr/local/bin/python3.8 (3.8.3) to create virtualenv…
...
Successfully created virtual environment! 
...

```

Now import eventlet.green.OpenSSL.SSL:

```
$ pipenv run python
Python 3.8.3 (default, Jun 29 2020, 18:02:49) 
[GCC 8.3.1 20190311 (Red Hat 8.3.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from eventlet.green.OpenSSL import SSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myuser/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.8/site-packages/eventlet/green/OpenSSL/__init__.py", line 3, in <module>
    from . import tsafe
  File "/home/myuser/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.8/site-packages/eventlet/green/OpenSSL/tsafe.py", line 1, in <module>
    from OpenSSL.tsafe import *
ModuleNotFoundError: No module named 'OpenSSL.tsafe'
>>> 

```

I suspect this has to do with the following PyOpenSSL commit which is now released via 20.0.0:
https://github.com/pyca/pyopenssl/commit/2dca7a75eef7c931abbbb6b9a87b1659db5ae6c8

**Comment by temoto** [comment]
Thanks, Brian. As workaround, you may just remove pyOpenSSL from virtualenv if possible, or temporary pin it to `<20`

**Comment by bneradt** [comment]
> Thanks, Brian. As workaround, you may just remove pyOpenSSL from virtualenv if possible, or temporary pin it to `<20`

Thanks for the quick reply. Yes, I can pin it to the previous release:

`pyOpenSSL = "==19.1.0"
`

That will currently work around the issue for me. I cannot remove it, however. If I could I'd never have hit this issue because I wouldn't have tried the import.

**Comment by temoto** [comment]
@bneradt Please, try again with latest code.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`

**Comment by bneradt** [comment]
> @bneradt Please, try again with latest code.
> 
> `pip install https://github.com/eventlet/eventlet/archive/master.zip`

Looks good.

### Verification Steps

I repeated the steps described in the description. I created a new Pipenv using the Pipfile described there. Pipfile.lock shows I'm testing with the following, latest eventlet and PyOpenSSL packages:

* [v0.30.0](https://github.com/eventlet/eventlet/releases/tag/v0.30.0) of eventlet
* [20.0.0](https://github.com/pyca/pyopenssl/releases/tag/20.0.0) of pyopenssl

With these packages installed, I can now import eventlet's SSL without issue:

```
$ pipenv run python
Python 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from eventlet.green.OpenSSL import SSL
>>> 
```

Thank you for a quick turn around of a solution!
