### ISSUE TITLE
Using Eventlet with coroutines and asyncio directly

### ISSUE THREAD

**Issue by mortoray** [eventlet/eventlet#673]
I'm uncertain of how to use monkey_patch in combination with asyncio and my own coroutines.

I want to use eventlet to wrap my connection to Mongo and Redis. I want to use asyncio directly (via Python websockets). 

If I try the obvious, of simply calling 'monkey_patch' and using `asyncio.get_event_loop()` I end up with an error:
   `raise RuntimeError('There is no current event loop in thread %r.'`

This call to 'get_event_loop' is inside Python websockets, but I have some direct calls as well.

What is the correct way to get this setup?

**Comment by temoto** [comment]
## Issue 
My guess asyncio assigns something to thread-local storage and `get_event_loop` looks it up.

`eventlet.monkey_patch()` by default patches `thread` module making thread-local storage local to greenthreads. Then you access `get_event_loop` from a different greenthread and thread-local storage is not consistent with asyncio expectations.


## Correct way
Correct way is to not mix different async implementations. Use eventlet or asyncio exclusively.

Suppose you expect network event from both eventlet wrapped Redis and asyncio websocket at the same time. All the way down the stack both libraries make select/poll/epoll/kqueue system call and wait for event from OS kernel. So the question is, which library is allowed to make the syscall in each OS thread. The other would be waiting for chance to work without knowing about it.


## A better correct way
Write asyncio hub for eventlet, see twisted hub in git history for reference, some things would be common on launching hub.


## Workaround
You may try following just for fun.
- `eventlet.monkey_patch(thread=False)`
- `eventlet.tpool.execute(everything_asyncio_fun)`

**Comment by mortoray** [comment]
Both of the libraries I need now, MongoDB and Redis, have asyncio versions, so I can do the correct way for now, and hope I don't need more later.

It should be possible to run the different listeners on different threads, perhaps using the setup calls you show. Is there a way to communicate through the threads? That is, us there a Queue than on one side is eventlet and on the other side is asyncio, or whatever it'd need to be?

**Comment by temoto** [comment]
Naive approach with Queue will not work because `Queue.put` will block all other network operations in both eventlet and asyncio cases. You may be able to bend Queue to your will, I just can't see how exactly off top of my head.

Probably the best way of communication is local socket. Pipe is better on POSIX OS. socket if you want to support Windows. Take a look at ZeroMQ.

To communicate as in share data you can just use any object like `str`, `int`, `list`, `dict`. Everything in pure Python is thread-safe. If you actually send data through socket/pipe you get correct multiple senders/readers semantic at the cost of extra work on marshaling and copying. Again, in ZeroMQ there are separate request-response and publish-subscribe semantics, so it's a lesson that putting every mode into same code with a lot of flags may be a very hard path.

To communicate as in synchronize you could use (maybe signals) or socket or poll on raw data. Polling introduces delay or CPU burning, and generally should be avoided.

If you want to work on socket-synchronized data sharing, it would be very welcome in Eventlet, we have one place where we use pipe for this job and that's not supported on Windows.

This is a rough sketch:
```python
class PleaseMakeBetterName:
  __slots__ = ("data", "sock_send", "sock_recv")

  def __init__(self):
    self.sock_send, self.sock_recv = socket.socketpair()
    # TODO setsockopt SO_SNDBUF=1 SO_SNDLOWAT=1 SO_RCVBUF=1 SO_RCVLOWAT=1
    # but the problem is, different OS may not respect these settings to full extent
    # so you may have to invent a bit more sophisticated signalling protocol
    # to fully cover cases like "block on send" and "multiple concurrent senders and readers"

  def send(self, data):
    self.data = data
    self.sock_send.send(b".")

  def recv(self):
    signal = self.sock_recv.recv(1)
    if signal == b".":
      return self.data
    raise EPIPE  # or return default
```

**Comment by temoto** [comment]
(just to clarify) Eventlet has patched Queue version that will correctly block only current green thread but asyncio sending into it will block other asyncio operations

**Comment by mortoray** [comment]
Okay, thanks. This gives me an idea of where I'd have to go if I want to support both in the same app. At the moment I have two different apps, one with eventlet, and one with asyncio. The socket approach will be the same for two apps vs. one app, so I might end up trying it.

**Comment by temoto** [comment]
Reopen if you want.

**Comment by igor-mendix** [comment]
I suspect the following might be related so I'll leave it here for future generations. This small script:
```python
import asyncio
import eventlet
import threading


class TestThread(threading.Thread):
    def run(self):
        asyncio.set_event_loop(asyncio.new_event_loop())
        print("Event loop set successfully")


if __name__ == '__main__':
    t = TestThread()
    t.start()
```
fails with this stacktrace (MacOS Catalina):
```
/usr/local/bin/python3.9 /Users/Igor/test/socketio_thread_async_test.py
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '4 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Igor/test/socketio_thread_async_test.py", line 14, in <module>
    t.run()
  File "/Users/Igor/test/socketio_thread_async_test.py", line 8, in run
    asyncio.set_event_loop(asyncio.new_event_loop())
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 61, in __init__
    self._make_self_pipe()
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 112, in _make_self_pipe
    self._add_reader(self._ssock.fileno(), self._read_from_self)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
TypeError: changelist must be an iterable of select.kevent objects
Exception ignored in: <function BaseEventLoop.__del__ at 0x110502e50>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 63, in close
    if self._signal_handlers:
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers'

Process finished with exit code 1
```
If I don't `import eventlet` everything works fine.
