### ISSUE TITLE
Release inconsistency

### ISSUE THREAD

**Issue by bnavigator** [eventlet/eventlet#674]
The release numbers are a mess

* GitHub release: 0.26.0
* Tags on GitHub: 0.29.1
* PyPI:  0.29.1
* http://eventlet.net/doc/: 0.28.1

Maybe,some other case of #609 ?

Which one is the last "stable" release?

**Comment by temoto** [comment]
Yes, it could be cleaner.

There is documentation for particular version of Eventlet published on website. Documentation doesn't state which version is latest or stable. It does say
> Eventlet team is commited to have only stable code in master branch

So depending on your preferred way to specify package requirements, latest stable is PyPI release or master branch.

I don't know why there is separate Github release, seems not useful.

**Comment by bnavigator** [comment]
Github releases: It is useful for watching the github project with "Custom > Releases" checked. And it allows for better announcement annotation than pure tags. Currently your **GitHub main page** shows 0.26.0 as the current release.

docs: You should rename the header from "Eventlet 0.28.1 documentation" to "Eventlet documentation" then.

**Comment by temoto** [comment]
Thanks for education about watching for "Custom > Releases".

**Comment by temoto** [comment]
@eventlet/developers  do you think we should delete github releases to avoid this confusion? Because better approach to automate their creation, I think nobody has time for that.

**Comment by flub** [comment]
Personally I've always considered the pypi to be authoritative for any python package.  I've never used or seen the point of github releases for libraries (for any language) so simply removing them is what I'd do.  But that doesn't mean there couldn't be legitimate use cases that I'm not aware off.  However for a package that is primarily used via pypi not having them seems reasonable.

(added disclaimer is also that I haven't used eventlet for a long while now)

**Comment by bnavigator** [comment]
A PyPI badge  in the README would help, too.

[![PyPI version](https://img.shields.io/pypi/v/eventlet.svg)](https://pypi.python.org/pypi/eventlet)

```rst
.. image:: https://img.shields.io/pypi/eventlet.svg
    :target: https://pypi.python.org/pypi/eventlet
```

**Comment by jstasiak** [comment]
@temoto I'd just get rid of GitHub releases.

**Comment by temoto** [comment]
Removed Github releases, added PyPI badge.

My personal opinion: version in docs is helpful. Patches are welcome.

**Comment by bnavigator** [comment]
Now the remaining outdated page is http://eventlet.net/doc/changelog.html, linked from the main site https://eventlet.net where a version badge would also be great.

**Comment by temoto** [comment]
@bnavigator fixed, thanks for reminding there were two files with badges.
