### ISSUE TITLE
Is subprocess.run patched?

### ISSUE THREAD

**Issue by mattpepin** [eventlet/eventlet#688]
In eventlet.green.subprocess, I see no mention of subprocess.run. Is it patched when monkey patching?

**Comment by tipabu** [comment]
`run` ultimately [uses `Popen`](https://github.com/python/cpython/blob/v3.9.2/Lib/subprocess.py#L505), which does get patched. So yes, `subprocess.run` will be green when monkey-patching.

**Comment by mattpepin** [comment]
Thanks :)
