### ISSUE TITLE
imp deprecated

### ISSUE THREAD

**Issue by wschmrdr** [eventlet/eventlet#691]
During a pytest run on a local application, I saw the following warning:

.../venv/lib/python3.9/site-packages/eventlet/patcher.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
    
Perhaps a migration over to importlib is in order?

**Comment by temoto** [comment]
Thank you. Duplicate of https://github.com/eventlet/eventlet/pull/582
