### ISSUE TITLE
Eventlet raises a different exception on SSL timeouts vs standard Python

### ISSUE THREAD

**Issue by ShaneHarvey** [eventlet/eventlet#692]
With standard Python 3.2+ (not monkey patched) timeouts on ssl connections raise `socket.timeout: The read operation timed out`. `socket.timeout` is a standard class that applications can use to identify network timeouts vs other network errors. For example:
```python
# import eventlet
# eventlet.monkey_patch()

import socket
import ssl

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.SOL_TCP)
sock.settimeout(2)  # Set timeout to 2 seconds.
sock.connect(("www.python.org", 443))
print('client socket connected')
client_context = ssl.create_default_context()
client_conn = client_context.wrap_socket(sock, server_hostname="www.python.org")
print('client TLS connected')
client_conn.read()  # This line will timeout.
```

The above example produces to following output:
```
$ python3 eventlet_ssl_timeout_bug.py
client socket connected
client TLS connected
Traceback (most recent call last):
  File "eventlet_ssl_timeout_bug.py", line 14, in <module>
    client_conn.read()  # This line will timeout.
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1103, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out
```

However when we uncomment the monkey patching, eventlet raises the more general `ssl.SSLError` exception:
```
$ python eventlet_ssl_timeout_bug.py
client socket connected
client TLS connected
Traceback (most recent call last):
  File "eventlet_ssl_timeout_bug.py", line 14, in <module>
    client_conn.read()  # This line will timeout.
  File "/Users/shane/pymongo-pycharm-3.8/lib/python3.8/site-packages/eventlet/green/ssl.py", line 186, in read
    return self._call_trampolining(
  File "/Users/shane/pymongo-pycharm-3.8/lib/python3.8/site-packages/eventlet/green/ssl.py", line 164, in _call_trampolining
    trampoline(self,
  File "/Users/shane/pymongo-pycharm-3.8/lib/python3.8/site-packages/eventlet/hubs/__init__.py", line 159, in trampoline
    return hub.switch()
  File "/Users/shane/pymongo-pycharm-3.8/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 313, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)
```

I would consider this a bug because the behavior differs from standard python and code that catches `socket.timeout` errors will no longer work as expected.

For related issues see:
- https://bugs.python.org/issue10272 where Python 3.2 changed ssl to raise socket.timeout on socket timeouts.
- https://jira.mongodb.org/browse/PYTHON-1157

**Comment by m0ppers** [comment]
This bug also appears when using eventlet together with redis:

```
import redis
import eventlet
eventlet.monkey_patch(socket=True)

r = redis.Redis(host='127.0.0.1', port=6379, db=0,
                ssl=True, ssl_ca_certs='ca.crt')
r.set('he', 'he')
```

Upon establishing a connection the redis client tries to read from the socket and runs in an expected timeout (i.e. it catches the timeout and then it proceeds normally)

As eventlet raises a different exception the logic fails.

The result is that you cannot use redis + eventlet :upside_down_face:

**Comment by temoto** [comment]
@m0ppers thanks, I'll try to fix it sooner.

`socket=True` selects to patch only that module, so `ssl` is still blocking. That would heavily restrict possible improvements from eventlet anyway.

**Comment by m0ppers** [comment]
@temoto yes this was just my minimal testground to dig into the problem. this is not what is happening in the real application. thanks for looking into it

**Comment by m0ppers** [comment]
btw I have an ugly monkey patch that patches the monkey patch that works (probably not a proper fix though :joy: :see_no_evil: )

```
from eventlet.green import ssl
import redis
import eventlet
import socket
eventlet.monkey_patch(socket=True)

ssl.timeout_exc = socket.timeout

r = redis.Redis(host='127.0.0.1', port=6379, db=0,
                ssl=True, ssl_ca_certs='ca.crt')
r.set('he', 'he')
```

**Comment by dmittal77** [comment]
The above patch doesn't seem to work with Python3.9.  Can you please clarify with which python version this would work

Redis is not an integral part of websockets apps and Redis Secure doesn't work with eventlet.

**Comment by numan-sahnou** [comment]
@m0ppers Thank you for your inputs it helped me a lot !

**Comment by johnsom** [comment]
FYI, the workaround to change the exception works for me on python3.9 + redis + TLS.

**Comment by baszoetekouw** [comment]
@temoto is there anything I can do to help get this bug fixed?  It's rather annoyingly breaking our MySQL and Redis TLS connections.  

Would you appreciate a PR to make the eventlet SSL lib exceptions to match recent python stdlib?

**Comment by temoto** [comment]
@baszoetekouw patches are always welcome, this one seems to have been battle tested too.

**Comment by temoto** [comment]
Fix by @baszoetekouw  is merged in master caf9f9983a43c537efff5c4c9ff1d543af6e1220
Release is pending in days, after more testing.

**Comment by puittenbroek** [comment]
This issue seems fixed on master, when is a release scheduled?

**Comment by risicle** [comment]
Can this issue be closed?
