### ISSUE TITLE
copy contributing.md

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#70]
https://github.com/h5bp/server-configs-nginx/blob/master/CONTRIBUTING.md

**Comment by Aayush-Kasurde** [comment]
@temoto Could you please elaborate this further ? I can help you in this.

**Comment by temoto** [comment]
@Aayush-Kasurde Well, you can start by copying contributing.md from h5bp link and adapting its text to what eventlet.net index page says about contributing patches. In the end we need to provide a clear text description what's required and not to contribute to Eventlet.

**Comment by temoto** [comment]
@Aayush-Kasurde I appreciate your willingness to help, especially with those non critical issues, as I'm bad at keeping balance to which things require attention. And as each project is unique, so are contribution rules. The goal here is to provide actual recommendations for our project. It would work best if you study some closed pull requests to identify Eventlet contribution guidelines.
