### ISSUE TITLE
Feature Request: Enable usage of prepared statements when using db_pool

### ISSUE THREAD

**Issue by daniel-kun** [eventlet/eventlet#709]
Hello eventlet team!

First of all, I'd like to thank you for your awesome work. We are using eventlet in this stack: python3 > gunicorn[eventlet] > flask. We benchmarked the different gunicorn worker types and found that eventlet is by far the fastest for our workloads that primariliy consist of database operations and very little computing (very i/o-bound).

In this scenario, I came across a shortcoming that is is not easily possible to use `db_pool` and use prepared statements that are prepared once a database connection is established, so that further uses are blazingly fast. I have not found a clear solution for this - maybe I am just missing something, or the API does not easily allow this.

I would like help you and implement a feasible API for this myself, but I need your guidance as to how a good designed solution could look like.

My first idea was to add a "companion" object to the database connection two callbacks: one for initialization and one for teardown. Here's how the new API could look like:

1) Add a "create_companion" parameter to the `BaseConnectionPool` ctor. The parameter is a function taking two parameters: `(pool: BaseConnectionPool, connection: object)`. The function is called right after a new connection has been established and must return an object, which is then internally stored as the `companion` to this connection.
2) Add a "cleanup_companion" parameter similar to the "cleanup" parameter, to tear down the companion.
3) Add a method `get_companion()` to `GenericConnectionWrapper` to be able to access the companio

With these API changes, you have flexible possibilities and can use this to create and store cursors in the companion that you can then use in your request.

What do you think? Better ideas? Is there already an easier solution to this with the existing API?

**Comment by temoto** [comment]
Thanks for proposal.

Please describe usage of said approach with pseudo-code. At first glance, companion idea as described seems only half useful to generic public.

## Performance

If you start a new project and really crave for speed, try Starlette/FastAPI. It runs on modern async/await engine, so completely different path than Eventlet. And incompatible with Eventlet and old IO libraries.

## Prepared statements

End-user needs prepared statements which, at least in PostgreSQL, are purely server-side. Arguably for most use cases, this is already sufficient:

```python
with db_pool.item() as conn:
    try:
        conn.execute(f"EXECUTE {query_name}")
        stats.inc("db.prepared.hit")
    except FIXME_PreparedStatementNotFound:
        stats.inc("db.prepared.miss")
        conn.execute(f"PREPARE query AS {query_name}")
        conn.execute(f"EXECUTE {query_name}")
```

It's not optimal because you could track availability of prepared statement in client. Note: you'd only save the network roundtrip, everything else is almost free.

You can just attach new attributes to connection wrapper objects.

```python
with db_pool.item() as conn:
    prepareds = conn.__dict__.setdefault("user_prepared", set())
    if query_name not in prepareds:
        conn.execute(f"PREPARE query AS {query_name}")
        prepareds.add(query_name)
    conn.execute(f"EXECUTE {query_name}")
```

Now adding a polished and tested version of this code is very welcome, at least by me. You could use a "static" attribute defined on `GenericConnectionWrapper` instead of `__dict__`.

## Setup/teardown

Setup function is useful by itself or can be used to aggressively prepare some very popular statements. I think setup should be only called implicitly by db_pool and not exported as externally callable `create_companion` method.

Teardown is already available as `BaseConnectionPool(cleanup=default)` and `item/put(cleanup=override)`.

If you want to do this, please write setup as isolated feature and then build prepared statements on top.

**Comment by temoto** [comment]
@eventlet/developers RFC

**Comment by daniel-kun** [comment]
Thanks for your reply, @temoto!

The proposal of executing the "PREPARE" statement for every client request and catching the exception, in my opinion kinda beats the purpose of doing the database server roundtrip only once per connection. While a failed "PREPARE" *might* be faster than an actual "PREPARE", it is still a server roundtrip which introduces latency and server-side load.

I already tried your proposed solution of attaching a property to the object returned by `db_pool.item()`. However, I experienced that the property did not preserve across all calls - I assumed that it happens that other Proxy objects are created for the same underlying connection under circumstances discarded that approach. At least I did not see a guarantee in the documentation that the same Proxy object is used for the same connection at all times.

My proposal of the "companion" object was just an attempt to wrap this workflow into a clean API. Reading your answer and thinking about it, however, it might be even much easier to just introduce a new `dict` property to `GenericConnectionWrapper` - maybe called "user_data" - which one might use as seen fit, and which is guaranteed to be preserved per connection. Feels much less complicated.

The teardown could then be done in the normal `cleanup` callback.

What do you think?

**Comment by temoto** [comment]
Quick clarification, I'm on the move, more later. You would optimistically
EXECUTE and only PREPARE on "404". So cost is one excessive roundtrip per
connection x statement.

**Comment by daniel-kun** [comment]
@temoto Ah, I understand now. Much better than the "PREPARE"-for-every-request-approach, performance-wise. However, this yields the difficulty that you have to explicitly catch the error that the executed prepared statement name is not valid, and distinguish it from other errors. Still feels a bit ugly and maybe prone to changes when upgrading the client library and/or the server version.

What is your opinion on the simplified "user_data" idea from my previous post?

**Comment by temoto** [comment]
@daniel-kun `user_data` idea is awesome. We should have more of that everywhere (not just this project).

**Comment by daniel-kun** [comment]
Sorry, I did not prepare a pull request in the following weeks :-(

After thorough investigation we digged deeper into FastAPI and have decided to replace gunicorn+flask+eventlet+psycopg2 with uvicorn+fastapi+asyncpg and have had wonderful results.

The performance is basically the same, though. We did measure the difference in performance between those two exact stacks and these were roughly the same. But the codebase is much cleaner with fastapi and asyncpg, which have been built with async in mind from the ground up.

Nevertheless, thanks for your great support and the great eventlet project. 👍

**Comment by temoto** [comment]
@daniel-kun yeah FastAPI is just awesome. You may be interested in hypercorn for multiprocess deployment, also it can consume systemd activated sockets with `--bind fd://0` and `StandardInput=socket`

IMHO, user_data and db_pool/setup are good ideas, so this is a perfect opportunity for feature adding contribution, if anyone is interested.
