### ISSUE TITLE
"/etc/resolv.conf" assumed default path is wrong for termux

### ISSUE THREAD

**Issue by rawrrawrfox** [eventlet/eventlet#725]
termux: the default path for resolv.conf file is not "/etc/resolv.conf", but the code presumes that to be the case

(pull request https://github.com/eventlet/eventlet/pull/724)

termux is a terminal app for android capable of running many linux utilites

the file resolv.conf is not found at the default location, and throws an exception which therefore breaks other projects which use this one as a dependency

i ran accross this problem when trying to run the termux version of onionshare (https://github.com/oleanderxoxo/onidroid) which uses this library as a dependency somewhere downstream

i'm not sure what would be the most elegant solution to the resolv.conf location problem, but i've tested this code, and it works as a quickfix nonetheless

it checks if the $PREFIX environment variable is set and if it points to the termux app's "...data/files/usr" system path, then specifies explicitly the location of the resolv.conf file when creating the resolver object, which needs to be $PREFIX + "/etc/resolv.conf"

**Comment by temoto** [comment]
Thanks, one of issue or patch is enough.
