### ISSUE TITLE
websocket: change max_frame_length from default 8MB

### ISSUE THREAD

**Issue by javismiles** [eventlet/eventlet#728]
Good day, we love eventlet, it's really great. 

We are working in a project that combines python with websockets, and we need to go above the 8mb frame limit for the websockets. 

How can we change the limit? it is essential for our app to be able to do it. Our A.I. related app combines a python backend with a react frontend, and we need to send images back and forth in sets that often go above the 8mb limit.

In this page, 
https://eventlet.net/doc/modules/websocket.html
we read:
""An optional argument max_frame_length can be given, which will set the maximum incoming uncompressed payload length of a frame. By default, this is set to 8MiB. Note that excessive values here might create a DOS attack vector."
thank you so much for your help "

so it seems that it can be changed. But we don't yet understand how. We are using Flash Socketio, and socket.io is using eventlet. But all our declarations and commands are done through socket.io. How can we change that limit in this scenario?

By the way all is working great with the combo Flask Socket.io + Eventlet, all that is left for us is to be able to increase this 8mb limit, 

thank you again

**Comment by temoto** [comment]
Right, so best option to configure frame limit is where websocket handlers are declared, in your case seems in socket-io. I'll try to talk to socket-io team about that.

Your next best option is probably this
```python
eventlet.websocket.DEFAULT_MAX_FRAME_LENGTH = 8<<20
```
before letting socket-io to load your app.

Let's keep this issue open until a better way is established.

**Comment by javismiles** [comment]
@temoto thank you very much for your quick reply, we would super appreciate it if maybe you could see if the socket-io team has any options for this, that would be awesome thank you very much, we will also try the other option you suggested and we will update this with results as our A.I. app won't be feasible without solving this, thank you so much again

**Comment by javismiles** [comment]
@temoto , we tried to do

import eventlet
eventlet.monkey_patch()
eventlet.websocket.DEFAULT_MAX_FRAME_LENGTH = 8<<20

but we get error:
  File "server.py", line 4, in <module>
    eventlet.websocket.DEFAULT_MAX_FRAME_LENGTH = 8<<20
AttributeError: module 'eventlet' has no attribute 'websocket'

**Comment by temoto** [comment]
`import eventlet.websocket`

**Comment by javismiles** [comment]
@temoto thank you very much, just added it and now it runs, now we will test, to change to for example 16 instead of 8, would the change be:  = 16<<20 ?

**Comment by temoto** [comment]
There is no magic syntax really, "shift left by tens" is just a convenient way to write 1024-based thousands, so
- `1<<10 = 1*(1024)` for kilobytes
- `1<<20 = 1*(1024*1024)` for megabytes, and so on

You could also write `DEFAULT_MAX_FRAME_LENGTH = 16000000`

**Comment by javismiles** [comment]
@temoto 
thank you very much, we just tested and unfortunately we still have problems after the same amount of data, so it seems that this is not helping:

import eventlet
import eventlet.websocket
eventlet.monkey_patch()
eventlet.websocket.DEFAULT_MAX_FRAME_LENGTH = 128<<20

hopefully, there is some other way, using those lines we are seeing things breaking at the same point as before unfortunately

**Comment by javismiles** [comment]
@temoto and the issue is definitely that limit, because the maximum we are able to transfer is about 6 images that each has a size of one point something mb which yeah is about that 8mb limit, after that it breaks, so yes we are bumping into that limit unfortunately :)

**Comment by temoto** [comment]
Is this code run before socket-io?

**Comment by temoto** [comment]
If you send each image in a distinct websocket frame (socketio event), that may solve everything while keeping safe frame limit.

**Comment by javismiles** [comment]
@temoto thank you very much, we have put the code at the very top of our server.py, at the very beginning, before any socket.io code begins, so I guess that is the earliest we can put it in I think

the other option you mention I don't think we can do that because we are sending x number of images to a backend function that will create an interpolation of all those images and so that function needs to receive them all as a set

**Comment by temoto** [comment]
Please show minimal reproduction script.

This is common pattern for uploading a set of big files:

```
set_id = api.create_set()
for f in files:
    api.set_upload(set_id, f)
api.set_commit(set_id)  # this runs heavy computation on all items in set
```

**Comment by tipabu** [comment]
Yeah, unfortunately patching out `eventlet.websocket.DEFAULT_MAX_FRAME_LENGTH` won't do much since the 8MB value gets baked into the signature of `WebSocketWSGI` and `RFC6455WebSocket`.

I remember bringing up the idea of how an application developer could override the value when reviewing https://github.com/eventlet/eventlet/commit/1412f5e4125b4313f815778a1acb4d3336efcd07, but with the GHSA repo gone I think I've only got a record of the conversation in my email. Looks like the preferred override method we arrived at to adjust the limit for a single endpoint like
```
@websocket.WebSocketWSGI
def handler(ws):
    ...
```
was to add afterward something like
```
handler.max_frame_length = 128 << 20
```
(or whatever value). Or, unpack the decorator a bit and do
```
def handler(ws):
    ...

handler = websocket.WebSocketWSGI(handler, max_frame_length=128 << 20)
```
similar to what [we do in tests](https://github.com/eventlet/eventlet/blob/v0.32.0/tests/websocket_new_test.py#L34-L38).

From what I can tell about flask-socketio, python-socketio, and python-engineio, though, you probably aren't the one responsible for calling WebSocketWSGI -- simplest way to punch through all the layers involved may be to do something like
```
import engineio.async_drivers.eventlet
engineio.async_drivers.eventlet._async['websocket'] = functools.partial(
    engineio.async_drivers.eventlet._async['websocket'],
    max_frame_length=128 << 20)
```

**Comment by javismiles** [comment]
@tipabu @temoto thank you so much to both of you, great news, this latest code using engineio seems to work!! we are testing but so far it seems to be working and we finally can transmit more data than before, I will confirm here shortly after the tests are completed but so far its looking good :)

**Comment by javismiles** [comment]
@tipabu @temoto Yes it works! this seems to fix it, we have changed the limit and now its not breaking anymore when sending, thank you so much for your super great help :)
