### ISSUE TITLE
Is the WSGI server production ready?

### ISSUE THREAD

**Issue by davidism** [eventlet/eventlet#735]
I'm reviewing Flask's docs about deploying, and there's a section about Eventlet's built-in WSGI server.

What is your feelings about using Eventlet's server in production? Is it particularly well tested, stable, and secure? I go to great lengths to communicate that Flask's dev server isn't suitable for production, so I don't want to be recommending something else that's in the same place.

There's also a section about using Gunicorn with Eventlet workers, which seems preferable because Gunicorn is much more configurable and probably has more testing as a production server.

**Comment by temoto** [comment]
TL;DR: eventlet.wsgi is production ready behind reverse proxy.

Hi. Search issues with word wsgi or label feature-wsgi, remove "only open" filter to see closed questions. So it's not ideal. But it should work for most users. At work mostly I choose gunicorn for light and uwsgi for heavy load, usually without green threads.

I do recommend placing `eventlet.wsgi` (and indeed most other similar software) behind reverse proxy like nginx/haproxy/traefik/etc to avoid easy resource exhaustion attacks.

**Comment by temoto** [comment]
Duplicate https://github.com/eventlet/eventlet/issues/440

**Comment by davidism** [comment]
Thanks, that matches the general advice I give for other production WSGI servers.
