### ISSUE TITLE
when use eventlet.green.fdopen(）to write a file with 'a' mode raise "io.UnsupportedOperation: File or stream is not writable." error

### ISSUE THREAD

**Issue by wuming0** [eventlet/eventlet#757]
if you run some code like below in python 3,you will find it will occur a error,"OSError: File or stream is not writable." :
```python
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# create by Zhichao Wu at 2022-06-17

# import os
from os import  O_CREAT, O_APPEND, O_RDWR

from eventlet.green import os


def write_file():
    filepath = './1.txt'
    fd = os.open(filepath, O_RDWR | O_CREAT | O_APPEND, 0o640)
    with os.fdopen(fd, 'a') as fw:
        fw.write('eventlet.greenio.py3.GreenFileIO.writable() bug!')

    print(f'---{filepath} result----')
    with open(filepath, 'r') as fr:
        print(fr.read())


if __name__ == "__main__":
    write_file()
````

if you run in python 3,you will got this error:
![github_evenlet_issue_2](https://user-images.githubusercontent.com/13671455/174300453-8abf2b40-b8d5-4df2-8856-06745ffe919c.PNG)

 What error in this code?
So I use pdb to debug this code,i find the call chain :
eventlet.green.os.fdopen() --> eventlet.greenio.py3.GreenPipe() --> _pyio.open() --> _pyio.BufferedWriter() --> eventlet.greenio.py3.GreenFileIO.writable() 
the code of "BufferedWriter" and “GreenFileIO”  class like this :
```python
class BufferedWriter(_BufferedIOMixin):
    def __init__(self, raw, buffer_size=DEFAULT_BUFFER_SIZE):
        if not raw.writable():
            raise OSError('"raw" argument must be writable.')

        _BufferedIOMixin.__init__(self, raw)
        if buffer_size <= 0:
            raise ValueError("invalid buffer size")
        self.buffer_size = buffer_size
        self._write_buf = bytearray()
        self._write_lock = Lock()

class GreenFileIO(_OriginalIOBase):
    def __init__(self, name, mode='r', closefd=True, opener=None):
         ……

    def writable(self):
        return 'w' in self._mode or '+' in self._mode
```
so GreenFileIO.writable will return false then BufferedWriter.__init__ raise OSError.
I think the function of eventlet.greenio.py3.GreenFileIO.writable() should cause consider the case when open file with mode ‘a’. may like this:
```python
class GreenFileIO(_OriginalIOBase):
    def __init__(self, name, mode='r', closefd=True, opener=None):
         ……

    def writable(self):
        return 'w' in self._mode or '+' in self._mode or 'a' in self._mode
```

**Comment by temoto** [comment]
Thanks, your solution seems good.

**Comment by wuming0** [comment]
I try fix up this last night(https://github.com/eventlet/eventlet/pull/758),also write some simple doc test to verify this.
![测试结果](https://user-images.githubusercontent.com/13671455/175191540-93808df8-a683-4a63-b444-852e65a65e37.PNG)
![测试结果2](https://user-images.githubusercontent.com/13671455/175191549-b450d45b-96bf-4008-b057-3130e9b66033.PNG)
.

**Comment by temoto** [comment]
Thanks. Your fix is merged in master.
