### ISSUE TITLE
Python3.10 support

### ISSUE THREAD

**Issue by CaptainBloodz** [eventlet/eventlet#780]
Since my distro is currently moving away from python3_9, I'm getting concerned with eventlet upgrade.

**Comment by vimalraghu** [comment]
yes same here, how far are we with 3.10 ?

**Comment by temoto** [comment]
Py3.10 is being added to CI with fixed http.client. There is ongoing test fail on patching existing locks, it's probably important enough to block production deploy.

If you experience issues other than `RuntimeError: cannot release un-acquired lock` please create them separately.

We can use this as meta-issue to track py3.10 support.

**Comment by CaptainBloodz** [comment]
Packaged install against master runs fine here.
Calling app isn't ready yet to test usability...

**Comment by CaptainBloodz** [comment]
> Packaged install against master runs fine here. Calling app isn't ready yet to test usability...

pgAdmin4 launches fine on python3_10 on gentoo with local packaging ebuild.

Thks

**Comment by AyushAgnihotri2025** [comment]
What is the estimated date for its compatibility release with Python 3.10?

**Comment by CaptainBloodz** [comment]
> > Packaged install against master runs fine here. Calling app isn't ready yet to test usability...
> 
> pgAdmin4 launches fine on python3_10 on gentoo with locally packaged ebuild.
> 
> Thks
commit f724f4ac0a6ed01c6a882412963b088e6c588a54 breaks it at start with 'module flask not found' error.

**Comment by temoto** [comment]
@CaptainBloodz thanks, does it show full traceback by chance?

**Comment by CaptainBloodz** [comment]
> @CaptainBloodz thanks, does it show full traceback by chance?

Dunno how to achueve this, sorry.

**Comment by CaptainBloodz** [comment]
Just gave it try on current master which works fine here.
Thks

**Comment by zsiciarz** [comment]
How far along is eventlet with being fully compatible with 3.10? From what I've gathered, #754 is the main blocker, isn't it?
