### ISSUE TITLE
sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [eventlet/eventlet#790]
The sdist package at PyPI is missing `tox.ini`.  Please add the `tox.ini` file to the sdist package to make downstream testing easier.  Thank you.

**Comment by temoto** [comment]
@mtelka locally verified that tox.ini gets into package

actual release is blocked by suspected regression by f724f4a https://github.com/eventlet/eventlet/issues/780#issuecomment-1445421635
