### ISSUE TITLE
eventlet: deprecation of Python libraries asyncore and asynchat

### ISSUE THREAD

**Issue by thomasgoirand** [eventlet/eventlet#804]
Hi there!

I'm the maintainer of Eventlet (and many other packages) in Debian. As per:
https://bugs.debian.org/1040096

"In Python 3.6, asyncore and asynchat have been formally marked as deprecated. Code that imports these libraries will no longer work from Python 3.12, which is currently in Trixie (Debian 13)."

Please get rid of asyncore / asynchat from Eventlet.

Cheers,

Thomas Goirand (zigo)

**Comment by bschoening** [comment]
+1

**Comment by itamarst** [comment]
As far as I can tell this code is dead code, that doesn't get imported so shouldn't prevent packaging.
