### ISSUE TITLE
Memory leak in greendns

### ISSUE THREAD

**Issue by jiajunsu** [eventlet/eventlet#810]
Hi, we've found a memory leak in module `greendns`, when the dns server response `query` with exception `dns.exception.Timeout` or `dns.exception.DNSException`, we got a memory leak with `EAI_EAGAIN_ERROR` or `EAI_NODATA_ERROR`.

The root cause of this memory leak is from `TracebackType`:

1. In [greendns.py](https://github.com/eventlet/eventlet/blob/v0.33.3/eventlet/support/greendns.py#L88), we initialize `EAI_*_ERROR` as instances of class `socket.gaierror`, which has `__traceback__` attribute as [PEP-3134](https://peps.python.org/pep-3134/#traceback-attribute) defined. 
2. The `__traceback__` is a [`TracebackType`](https://docs.python.org/3/reference/datamodel.html#traceback-objects), when the same instance `EAI_NODATA_ERROR` being called multiple times, it inserts `tb_next` to the top of `EAI_NODATA_ERROR.__traceback__.tb_next`.

To simplify and reproduce the problem, we made a script, the main logic is same with function `greendns.resolve`.

```python
import socket
EAI_NONAME_ERROR = socket.gaierror(socket.EAI_NONAME, 'Name or service not known')

def query():
    raise EAI_NONAME_ERROR


def step():
    try:
        query()
    except Exception:
        pass


print("Init")
print(EAI_NONAME_ERROR.__traceback__)  # None

step()
print("After first raise")
print(EAI_NONAME_ERROR.__traceback__)  # <traceback object at 0x7f04dd6a3d90>
print(EAI_NONAME_ERROR.__traceback__.tb_next)  # <traceback object at 0x7f04dd6a1770>
print(EAI_NONAME_ERROR.__traceback__.tb_next.tb_next)  # None

step()
print("After second raise")
print(EAI_NONAME_ERROR.__traceback__)  # <traceback object at 0x7f04dd6a17c0>
print(EAI_NONAME_ERROR.__traceback__.tb_next)  # <traceback object at 0x7f04ddf48aa0>
print(EAI_NONAME_ERROR.__traceback__.tb_next.tb_next)  # <traceback object at 0x7f04dd6a3d90>
print(EAI_NONAME_ERROR.__traceback__.tb_next.tb_next.tb_next)  # <traceback object at 0x7f04dd6a1770>
print(EAI_NONAME_ERROR.__traceback__.tb_next.tb_next.tb_next.tb_next)  # None
```

I tested and reproduced the script with python version 3.7.10, 3.8.8, 3.11.0, and will try to commit a pull request to fix this issue.

IMHO this issue is not related to OS version, my environment info is blow:

`uname -a`
> Linux 3.10.0-862.14.4.el7.x86_64

**Comment by jiajunsu** [comment]
I just notice a PR https://github.com/eventlet/eventlet/pull/682, 
@jjohnson42 has found this problem before. Hope my reproduce script could help with it.
Besides, we can discuss how to fix it in a better way.

**Comment by shihai1991** [comment]
FYI, the original discussion and solution in: https://mail.python.org/pipermail/python-3000/2007-January/005395.html

**Comment by jiajunsu** [comment]
@temoto @edwardgeorge @flub 
Could you please take a few minutes, looking at this issue and review the PR? We hope the next release of eventlet could fix this memory leak problem, thanks.

**Comment by jiajunsu** [comment]
@4383 I've noticed that you are a maintainer of eventlet and plan to release version 0.34.0, could this memory leak bug be fixed in the new release?
