### ISSUE TITLE
tests fail with kernel 6.6

### ISSUE THREAD

**Issue by jirislaby** [eventlet/eventlet#821]
Downstream report: https://bugzilla.suse.com/show_bug.cgi?id=1216858
Kernel report: https://lore.kernel.org/all/738bb6a1-4e99-4113-9345-48eea11e2108@kernel.org/

tl;dr
https://github.com/torvalds/linux/commit/dfa2f0483360d4d6f2324405464c9f281156bd87 causes https://github.com/eventlet/eventlet/blob/dd2f0ea32d6b6d064be52fe8e27fca275985cdc4/tests/greenio_test.py#L389
to fail due to timeout -- the test takes now 1.7 s instead of the previous 300 ms. 

So far the result from the above is:

> It seems the test had some expectations.
> 
> Setting a small (1 byte) RCVBUF/SNDBUF, and yet expecting to send
> 46080 bytes fast enough was not reasonable.
> It might have relied on the fact that tcp sendmsg() can cook large GSO
> packets, even if sk->sk_sndbuf is small.
> 
> With tight memory settings, it is possible TCP has to resort on RTO
> timers (200ms by default) to recover from dropped packets.

and

> Retracting TCP windows has always been problematic.
> 
> If we really want to be very gentle, this could add more logic,
> shorter timer events for pathological cases like that,
> I am not sure this is really worth it, especially if dealing with one
> million TCP sockets in this state.

Michal proposes:

> How about my suggestion to set SO_SNDBUF and SO_RCVBUF before listen() and
> connect()? Would that be an acceptable solution or does the test depend on
> setting the buffer sizes this late?

**Comment by 4383** [comment]
Thanks for the heads up!

**Comment by radeksm** [comment]
The way how this seems to be working is that default size of SO_SNDBUF is 16kB.
And at least on my Linux laptop you can't set buffer smaller than 4608. 
```
>>> import socket
>>> test_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> test_sock.getsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF)
16384
>>> test_sock.setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF, 1)
>>> test_sock.getsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF)
4608
>>> 
>>> test_sock.setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF, 4096)
>>> test_sock.getsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF)
8192
>>> test_sock.setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF, 2048)
>>> test_sock.getsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF)
4608
```

And on top of this, man 7 socket says:
```
SO_RCVBUF Sets or gets the maximum socket receive buffer in bytes.
The kernel doubles this value (to allow space for bookkeeping overhead)
when it is set using setsockopt(2), and this doubled value is returned 
by getsockopt(2)
```


So even if you request the SO_SNDBUF buffer size to be 1B, in fact you get 4608,
which is double of the usable buffer size 2304.

@jirislaby what was your Linux distro with 6.6 kernel ? I was looking for any but couldn't find any, unless you compiled 6.6 kernel yourself ?

**Comment by jirislaby** [comment]
> And at least on my Linux laptop you can't set buffer smaller than 4608.

Yes, that's correct:
https://bugzilla.suse.com/show_bug.cgi?id=1216858#c5

> what was your Linux distro with 6.6 kernel ?

openSUSE Tumbleweed always follows the latest stable kernel.

**Comment by mkubecek** [comment]
Please see https://lore.kernel.org/all/20231103092706.6rw2ehuigxfdvhlc@lion.mk-sys.cz/ for explanation of what I believe is the primary problem of the test script.

**Comment by 4383** [comment]
@mkubecek: Nice. Do you want to propose a patch?

@jirislaby: is it the only test you identified as failed?

AFAICS the `bufsized` method [1], the method that  set `SO_RCVBUF` [2] to the given socket' option, seems called many time with more or less similar scenarios i.e. the receiver side sets SO_RCVBUF after connect() so that the window shrinks after sender already sent more data.

[1] https://github.com/eventlet/eventlet/blob/dd2f0ea32d6b6d064be52fe8e27fca275985cdc4/tests/greenio_test.py#L24
[2] https://github.com/eventlet/eventlet/blob/dd2f0ea32d6b6d064be52fe8e27fca275985cdc4/tests/greenio_test.py#L32C47-L32C56

**Comment by 4383** [comment]
This test ran successfully on my laptop, with the current code base and with a similar kernel:

```
$ uname -sr
Linux 6.6.8-200.fc39.x86_64
```

Tox output:
```
tests/greenio_test.py::TestGreenSocket::test_full_duplex PASSED          [ 35%]
tests/greenio_test.py::TestGreenSocket::test_full_duplex PASSED          [ 35%]
tests/greenio_test.py::TestGreenSocket::test_full_duplex PASSED          [ 35%]
tests/greenio_test.py::TestGreenSocket::test_full_duplex PASSED          [ 36%]
```

Will made another test with changes over `SO_RCVBUF`.

**Comment by 4383** [comment]
Tests are also successful with changes applied:

```
tests/greenio_test.py::TestGreenSocket::test_full_duplex PASSED          [ 35%]
tests/greenio_test.py::TestGreenSocket::test_full_duplex PASSED          [ 35%]
tests/greenio_test.py::TestGreenSocket::test_full_duplex PASSED          [ 35%]
tests/greenio_test.py::TestGreenSocket::test_full_duplex PASSED          [ 36%]
```

```
diff --git a/tests/greenio_test.py b/tests/greenio_test.py
index ce87cf54..b4bce022 100644
--- a/tests/greenio_test.py
+++ b/tests/greenio_test.py
@@ -417,8 +417,8 @@ class TestGreenSocket(tests.LimitedTestCase):
 
         server_evt = eventlet.spawn(server)
         client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
-        client.connect(('127.0.0.1', listener.getsockname()[1]))
         bufsized(client)
+        client.connect(('127.0.0.1', listener.getsockname()[1]))
         large_evt = eventlet.spawn(read_large, client)
         eventlet.sleep(0)
         client.sendall(b'hello world')
```
