### ISSUE TITLE
Rename the master branch to main.

### ISSUE THREAD

**Issue by damani42** [eventlet/eventlet#828]
It can maybe be good to follow the new convention and rename the master branch to main.

**Comment by 4383** [comment]
Let's fix the urgent things first. Also I fear that renaming the master branch could impact all the opened pull request. I don't know how github handle this kind of structural change internally to PRs.

I think its a good idea, but I think its not urgent. That's the kind of improvement that could be planed for next steps.

It would also require to socialize this change to all contributors and maintainers, to allow them to fetch the new branch and adapt their local clones.

**Comment by 4383** [comment]
As the team is now mostly composed of newcomers, I'd rather suggest to create a specific dev branch and to redirect the urgent pull requests on the top of this  new development branch to conduct our current restore operation.

That would avoid to break more things, and the merges would be conducted against an isolated environment. Once we think reached our goal, then we would be able to merge this dev branch with master.

if something went wrong during the management of the urgent things, and if we found an issue related to our recent actions, this development branch would avoid to do patches reverts directly from the master branch.

@itamarst, @jeckersb any opinion?

**Comment by jeckersb** [comment]
@4383 I think that's a good plan.  I also agree re: master->main that it's a good idea, but probably more mid-to-long term.  We have enough immediate problems in front of us, and we should get a handle on those before we rename branches and possibly cause ourselves even more problems.

**Comment by 4383** [comment]
As discussed in #839 and in #835 our top priority is going through PRs, many of which have fixes for real issues that impact someone enough that they submitted a fix. We surely decide to move to legacy mode soon.

Once `0.34.0` will be out and early next year, I think we would be able to close feature proposal by explaining our motivations and kindly thanking authors. 

I'm closing this issue to clean our backlog, we would be able to reopen it later once urgent things will be done.
