### ISSUE TITLE
Decide on maintenance goals, and document status for users

### ISSUE THREAD

**Issue by itamarst** [eventlet/eventlet#835]
I can imagine different maintenance goals for the project going forward:

* **Legacy:** Maintenance for stability and bug fixing, no new features, discourage usage in new projects.
* **Maintenance:** Maintenance for stability and bug fixing, no new features, new projects by new users are fine.
* **Active:** Also add new features and enhancements, not just maintenance.

My _personal_ feeling is that eventlet should be in legacy mode, but the maintainers as a group should decide on a level and then document it so users know what to expect.

**Comment by 4383** [comment]
As discussed on the [Openstack side](https://review.opendev.org/c/openstack/governance/+/902585) I proposed to smoothly led eventlet to retirement in the coming years, so my personal is:

- move to legacy mode
- introduce aiohub as an official repo of the eventlet orga https://github.com/4383/aiohub/ . I was think propose to move aiohub into the eventlet orga early in 2024 and focus first on urgent things on eventlet. aiohub would be an official guideline to all eventlet users to transition smoothly to asyncio.
- officially retire eventlet in 2-3 years, unless in the meantime someone wants to continue eventlet.

**Comment by 4383** [comment]
The aiohub repo is ready for development and I was thinking inspire from [aioeventlet](https://pypi.org/project/aioeventlet/#files) and from gevent-asyncio to implement aiohub. I think that both projects are solid rock foundations for aiohub.

IMO aiohub should be an official response, from the eventlet orga, concerning the future of eventlet.

**Comment by 4383** [comment]
aiohub would how we discourage the usage of eventlet in new projects and how we allow to migrate the existing ones.

**Comment by 4383** [comment]
I moved aiohub into the eventlet orga https://github.com/eventlet/aiohub

As we are closes from the end of year celebrations, I propose to let this topic opened until early next year (2024), to allow people to react. If nobody else will replied, then, we could consider moving officially to the legacy mode.
