### ISSUE TITLE
 missing attibute '_is_main_interpreter'

### ISSUE THREAD

**Issue by ericsnowcurrently** [eventlet/eventlet#838]
This is essentially a recurrence of #604, but affecting a recently released Python version: 3.12.1.  See https://github.com/python/cpython/issues/112826.  I merged a workaround in CPython for 3.12 (to preserve compatibility with 3.12.0), but for 3.13+ this will need to be fixed in eventlet.

Basically, eventlet/eventlet/green/thread.py needs something like the following added:

```py
_is_main_interpreter = __thread._is_main_interpreter
```

I'm happy to open a PR if that would help.

**Comment by 4383** [comment]
Thanks for the heads up.
If you don't mind feel free to open a PR, we would be happy to review it.

**Comment by ericsnowcurrently** [comment]
Thanks for taking care of that!

**Comment by 4383** [comment]
You are welcome
