### ISSUE TITLE
Cleaning backlog and prioritize work

### ISSUE THREAD

**Issue by 4383** [eventlet/eventlet#839]
Hey,

By inspecting the backlog, we can observe issues that are open and without much activity since 2014. Many of them are related to Python 2.7.

As we surely want to move to legacy mode (#835), I'd suggest to close all the issues without activity since 2016. It would remove unnecessary noise and give us a better vision of the urgent things to fix. Are you ok with that?

In parallel, I started to close duplicating tickets and I introduced a couple of new labels to allow us to prioritize things.

Let me know if you agree with my suggestion and if you have questions or suggestions.

**Comment by 4383** [comment]
I'd suggest to manage things by following the Eisenhower's matrix:
![image](https://github.com/eventlet/eventlet/assets/1541489/be3a9e09-ddfb-4466-81cc-ead9d72fea65)

Urgent things are not necessarly important, and important things are not necessarly urgent, but some things are important and urgent, fix them first.

According to this philosophy, I created related labels to identify each case and then properly identify priorities.

**Comment by itamarst** [comment]
Probably top priority is going through PRs, many of which have fixes for real issues that impacted someone enough that they submitted a fix.

**Comment by 4383** [comment]
> Probably top priority is going through PRs, many of which have fixes for real issues that impacted someone enough that they submitted a fix.

> Probably top priority is going through PRs, many of which have fixes for real issues that impact someone enough that they submitted a fix.

I agree. Also if we decide to move to legacy mode, I think we can close feature proposal by explaining our motivations and kindly thanking authors. I'll try to triage them if ones exists.
