### ISSUE TITLE
Reconsider 3.7 support

### ISSUE THREAD

**Issue by itamarst** [eventlet/eventlet#846]
@tipabu suggests at https://github.com/eventlet/eventlet/pull/827#issuecomment-1858614954 that maybe dropping 3.7 was a mistake; it's still about an eighth of downloads.

* Debian Buster is still getting security updates, and includes 3.7.
* Ubuntu 18.04 had 3.7 as an option. 18.04 was end of life in April, unless you pay for extended support, but I imagine some people are still using it.
* Probably there's a bunch of Docker images out there that hardcoded buster, e.g. `python:3.7-buster-slim` or similar.
* I think RHEL never had 3.7? RHEL 8 skipped it, if memory serves.

I automatically suggested dropping 3.7 on my default attitude as open source maintainer that it's been 4 years since Python 3.8 came out, and every relevant LTS distro (that I pay attention to) with 3.7 has had two major updates since.

But, that might have been the wrong perspective. From a harm reduction perspective it's possible that given the scope of eventlet usage, supporting 3.7 for a while yet is still worth it. `cryptography` is still supporting 3.7, for example.

If we do add back support, I would suggest any usage on 3.7 come with a very clear warning (or log message?) on startup.

**Comment by 4383** [comment]
WFM.
The warning could be added into `eventlet/__init__.py` with a check of the python version in use at runtime.
