### ISSUE TITLE
eventlet (0.34.3) causes runtime error when calling eventlet.monkey_patch()

### ISSUE THREAD

**Issue by kelvin-j-li** [eventlet/eventlet#896]
After I upgraded eventlet to the current latest 0.34.3, the python3 app stops working during app start up when calling eventlet.monkey_patch():

```
  File "/Users/kelvin j li/ato/pre-checker/./checker.py", line 22, in <module>
    eventlet.monkey_patch()
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 278, in monkey_patch
    _green_existing_locks()
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 399, in _green_existing_locks
    _upgrade_instances(sys.modules, rlock_type, upgrade)
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 455, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 469, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 464, in _upgrade_instances
    container_vars = vars(container)
                     ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
**RuntimeError: Working outside of request context.**

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
```

As soon as I fallback to any older version eventlet (ex: pip3 install eventlet==0.34.2), the above error goes away.

According to the eventlet doc, 
https://eventlet.net/doc/patching.html#monkeypatching-the-standard-library

It is **important** to call [**monkey_patch**()](https://eventlet.net/doc/patching.html#eventlet.patcher.monkey_patch) **as early in the lifetime of the application as possible**. Try to do it as one of the first lines in the main module. The reason for this is that sometimes there is a class that inherits from a class that needs to be greened – e.g. a class that inherits from socket.socket – and inheritance is done at import time, so therefore the monkeypatching should happen before the derived class is defined. It’s safe to call monkey_patch multiple times. 

However, the latest eventlet 0.34.3 appears to expect **monkey_patch**() to be called inside a request context. I tried to do that within app.route (ex: /) , but got a different error instead:

  File "/opt/homebrew/lib/python3.11/site-packages/pymongo/topology.py", line 259, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: module 'select' has no attribute 'poll', Timeout: 30s, Topology Description: <TopologyDescription id: 65a7fcfa47a7ee7058736902, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AttributeError("module 'select' has no attribute 'poll'")>]>

Is this a bug in 0.34.3 or there's breaking changes related to monkey_patch()? 

Thanks.

Kelvin J Li

**Comment by 4383** [comment]
Without too digging, I think it could be an unexpected side effect related to https://github.com/eventlet/eventlet/commit/dec2ed5de1f170fad9539f0638278dbe36a3672f

**Comment by 4383** [comment]
Thanks for raising our attention.

**Comment by 4383** [comment]
The problem seems located around the new function `upgrade_or_traverse`, added by the new logic introduced by [dec2ed](https://github.com/eventlet/eventlet/commit/dec2ed5de1f170fad9539f0638278dbe36a3672f).

**Comment by itamarst** [comment]
You really should be calling `eventlet.monkey_patch()` _before_ any library imports. The fact that werkzeug was imported suggests you're not.

**Comment by jayofdoom** [comment]
There are cases, demonstrated by CI for https://review.opendev.org/c/openstack/ironic-inspector/+/906011/, where that isn't possible. In this specific case, Sphinx autodocs -- I'm not sure for scenarios like this how to sanely monkey_patch beforehand. 

I'm going to look at better strategies to prevent monkey patching from happening in the sphinx autodocs case for ironic-inspector; but I wonder if there are better ways to handle this situation when it's non-critical (like for autodocs).

**Comment by kelvin-j-li** [comment]
> Please can you provide us a scenario to reproduce your issue?

`#!/usr/bin/env python3

from flask import Flask, render_template, send_file
from flask import request
from flask import Response
from flask import jsonify
from flask_apscheduler import APScheduler
from flask_swagger import swagger

# activate eventlet
import eventlet
**eventlet.monkey_patch()**
from eventlet import wsgi
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['JSONIFY_PRETTYPRINT_REGULAR'] = 1

LOG_LEVEL = os.environ.get('LOG_LEVEL', 'DEBUG')
app.logger.setLevel(LOG_LEVEL)
app.logger.info(f"INIT: LOG_LEVEL = <{LOG_LEVEL}>, app.logger level = {app.logger.level}")

# activate Flask-socketio
socketio = SocketIO(app)

PORT = int(os.getenv("PORT", 8080))
DEBUG = os.environ.get('DEBUG', False)

# ...

if __name__ == '__main__':
    socketio.run(app,
        host="0.0.0.0",
        port=PORT,
        debug=DEBUG,
    )
`

**Comment by jayofdoom** [comment]
> There are cases, demonstrated by CI for https://review.opendev.org/c/openstack/ironic-inspector/+/906011/, where that isn't possible. In this specific case, Sphinx autodocs -- I'm not sure for scenarios like this how to sanely monkey_patch beforehand.
> 
> I'm going to look at better strategies to prevent monkey patching from happening in the sphinx autodocs case for ironic-inspector; but I wonder if there are better ways to handle this situation when it's non-critical (like for autodocs).

Yeah, in this case, we were able to root cause it back in the way that Itamar originally suggested for the original bug poster:

Basically, for ironic-inspector, our usual run was by using a cmd to launch, so we monkey_patch() in ironic_inspector/cmd/__init__.py. However, in the case of sphinx autodoc, it imports the module directly, which loads from the root module first, in a less determinate order. By monkey patching in the root of the module's __init__.py file, we got rid of the error.

**Comment by kelvin-j-li** [comment]
moving monkey_patch() at the beginning seems to be suppress the runtime error:

`
#!/usr/bin/env python3

\# activate eventlet
import eventlet
eventlet.monkey_patch()

from flask import Flask, render_template, send_file
from flask import request
from flask import Response
from flask import jsonify
`

However, in local dev environment, we have to take out DEBUG flag when bring up the socketio / app, otherwise the tcp for the flask server would not be ready. In cloud k8s env, it's ok to keep DEBUG=1

`
   **DEBUG=0**
    socketio.run(
        app,
        host="0.0.0.0",
        port=PORT,
        # debug=False,
        **debug=DEBUG**
    )
`

**Comment by kelvin-j-li** [comment]
> moving monkey_patch() at the beginning seems to be suppress the runtime error:
> 
> ` #!/usr/bin/env python3
> 
> # activate eventlet import eventlet eventlet.monkey_patch()
> 
> from flask import Flask, render_template, send_file from flask import request from flask import Response from flask import jsonify `
> 
> However, in local dev environment, we have to take out DEBUG flag (or set it to 0) when bring up the socketio / app, otherwise the tcp portfor the flask server would not be ready - the commandline flask server was stuck. In cloud k8s env, it's ok to keep DEBUG=1
> 
> ` DEBUG=0
> 
> ```
> socketio.run(
>     app,
>     host="0.0.0.0",
>     port=PORT,
>     debug=DEBUG
> )
> ```
> 
> `

to workaround the DEBUG flag issue in local env, I have to selective patch instead of having empty params for monkey_patch():

`
+import os
 import eventlet
-eventlet.monkey_patch(thread=False, socket=False)
+if os.environ.get('K8S_ENV', ''):
+    eventlet.monkey_patch()
+else:   # localhost
+    eventlet.monkey_patch(thread=False, socket=False)
`

**Comment by jayofdoom** [comment]
I bet #907, included in 0.35.1, resolves this issue. Please confirm and close if so.

**Comment by kelvin-j-li** [comment]
hi @jayofdoom,
thanks for your update!

I tried eventlet-0.35.1 locally (on mac arm) just now. if I just do eventlet.monkey_patch() w/o setting thread and socket to be False, I still observe the flask server got stuck. 

best regards

**Comment by itamarst** [comment]
I will take a look.

**Comment by kelvin-j-li** [comment]
> I ran the following code:
> 
> ```python
> #!/usr/bin/env python3
> # activate eventlet
> import eventlet
> eventlet.monkey_patch()
> 
> import os
> 
> from flask import Flask, render_template, send_file
> from flask import request
> from flask import Response
> from flask import jsonify
> 
> from eventlet import wsgi
> from flask_socketio import SocketIO
> 
> app = Flask(__name__)
> app.config['JSONIFY_PRETTYPRINT_REGULAR'] = 1
> 
> LOG_LEVEL = os.environ.get('LOG_LEVEL', 'DEBUG')
> app.logger.setLevel(LOG_LEVEL)
> app.logger.info(f"INIT: LOG_LEVEL = <{LOG_LEVEL}>, app.logger level = {app.logger.level}")
> 
> # activate Flask-socketio
> socketio = SocketIO(app)
> 
> PORT = int(os.getenv("PORT", 8080))
> DEBUG = os.environ.get('DEBUG', False)
> 
> # ...
> 
> if __name__ == '__main__':
>     socketio.run(app,
>                  host="0.0.0.0",
>                  port=PORT,
>                  debug=True,
>                  )
> ```
> 
> The server successfully served up a 404 page, and I wasn't able to reproduce any problems. Notice monkey patching happens first.
> 
> Can you provide a self-contained, minimal reproducer that has enough code to actually reproduce the problem?

Thank you for your follow up @itamarst . 
I was able to re-produce the stuck issue on my local machine (mac m1 pro, python 3.11.7) by using the above code.

pip3 list | grep -E 'socket|thread'
python-socketio             5.7.2
websocket-client            1.6.4

I got 404 after I change the event patching to eventlet.monkey_patch(thread=False, socket=False).  If I use eventlet.monkey_patch(), the server is not responding. Perhaps it's sth to my local setup. 

Let me try to run the sample else where (linux, or a different mac).

Thanks.

**Comment by kelvin-j-li** [comment]
just tried it on linux and a home intel mac, I am not able to re-produce the stuck issue -- eventlet.monkey_patch() works fine.

let me do more research tomorrow and try it on other M1 mac in the office. 

Thanks.

**Comment by kelvin-j-li** [comment]
I tried the sample script with python3 -m venv in my local machine (m1 mac), confirmed that there's no stuck issue.

```
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install eventlet flask flask_socketio python-socketio
```
The stuck issue appears to be specific to my local env with lost of python3 moduels. 
we can close this issue. 

Thank you all!

**Comment by 4383** [comment]
Thank you @kelvin-j-li
