### ISSUE TITLE
monkey_patch() fails to green all rlocks

### ISSUE THREAD

**Issue by itamarst** [eventlet/eventlet#969]
Right now greening of locks happens _before_ modules are patched.

Unfortunately the patching process can trigger imports of additional modules, which can then create more RLocks that never get greened.

This is can be observed in OpenStack's ironic when running on Python 3.12; the logging module is somehow imported during the module-patching process, so its lock never gets greened.

**Comment by 4383** [comment]
Which logging module? oslo.log?

We should also notice that oslo.log relied on the "multiple readers" until recently https://opendev.org/openstack/oslo.log/commit/8705f67bfbd733edf923003c0a5850e7a4a5735b

Depending on the used version of oslo.log multiple readers protection was disabled and so concurrent access to a file descriptor was allowed, I don't know if it could have somehow an impact with rlocks.

**Comment by itamarst** [comment]
Python stdlib logging.
