### ISSUE TITLE
os.read() blocks even after monkey patching.

### ISSUE THREAD

**Issue by ethan-vanderheijden** [eventlet/eventlet#973]
This is likely the root cause behind #634.

I thought that monkey patching the os module means all blocking functions are converted into non-blocking functions. However, while using Watchdog, I found that `os.read()` still block. Simple example using watchdog:
```py
import eventlet
from eventlet.greenthread import spawn, sleep

eventlet.monkey_patch()

import logging
from watchdog.observers import Observer
from watchdog.events import LoggingEventHandler

increment = 0


def heartbeat():
    global increment
    while True:
        print('second:', increment)
        increment += 1
        sleep(1)


if __name__ == "__main__":
    spawn(heartbeat)
    sleep(2)

    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
    event_handler = LoggingEventHandler()
    observer = Observer(generate_full_events=True)
    observer.schedule(event_handler, '/home/ethan/test', recursive=True)
    observer.start()
    try:
        while observer.is_alive():
            observer.join(1)
    finally:
        observer.stop()
        observer.join()
```

I expect it to print out time stamps forever ("seconds: 0", "seconds: 1", "seconds: 2", "seconds: 3" ...), but once Watchdog starts, it stops printing because Watchdog blocks on the main thread.

The issue is that Watchdog spawns a new thread and reads from the INotify API. The read calls are executed through `os.read(fd, size)` here:
https://github.com/gorakhargosh/watchdog/blob/9f23b599f369cdd873c0cf3dd9e69567234d78fb/src/watchdog/observers/inotify_c.py#L302

Of course the read calls are redirected to the monkey patched version:
https://github.com/eventlet/eventlet/blob/06ec82896ebb9a26edaf6e1ad4d63393990f15b7/eventlet/green/os.py#L36-L51

I believe the issue is that the monkey patched method immediately calls the original read function, which blocks because no output is available yet, before it calls `trampoline`. If I change the order of method calls to call `trampoline` first, it works fine:
```py
def read(fd, n):
    while True:
        try:
            hubs.trampoline(fd, read=True)
        except hubs.IOClosed:
            return ''

        try:
            return __original_read__(fd, n)
        except OSError as e:
            if get_errno(e) == errno.EPIPE:
                return ''
            if get_errno(e) != errno.EAGAIN:
                raise
```

It makes more sense to me that Eventlet waits until data is available before calling a potentially blocking function. Is this a bug with Eventlet? If not, is `os.read` designed to be blocking (even after being monkey patched)?

**Comment by 4383** [comment]
Hello,

Did you observed errors somewhere in your logs?
Which Eventlet version is in use and which Python version are you using?

**Comment by ethan-vanderheijden** [comment]
No errors in the logs
Eventlet version: 0.36.1
Python version: 3.12.4
OS: linux

Sorry, I should have clarified that the Watchdog example only works on Linux.

Here's a simplified example that uses no dependencies besides Eventlet (should work on Windows and Mac):
```py
import eventlet
from eventlet.greenthread import spawn, sleep

eventlet.monkey_patch()

import os

increment = 0


def heartbeat():
    global increment
    while True:
        print('second:', increment)
        increment += 1
        sleep(1)


def read_fd_blocking(fd):
    print('starting to read')
    os.read(fd, 8192)
    print('finished reading')


if __name__ == "__main__":
    heartbeat_thread = spawn(heartbeat)
    sleep(2)

    read_fd, write_fd = os.pipe()
    spawn(read_fd_blocking, read_fd)

    heartbeat_thread.wait()
```

Again, you would expect that the heartbeat thread continues printing out timestamps, but in reality, the call to `os.read()` blocks the main thread and the program freezes.
