### ISSUE TITLE
Python 3.13: threading.Thread.is_alive() wrongly returns True

### ISSUE THREAD

**Issue by CyrilRoelandteNovance** [eventlet/eventlet#998]
Consider the following piece of code:

```
#import eventlet; eventlet.patcher.monkey_patch()
import queue
import threading


class Worker(threading.Thread):
    EXIT_SENTINEL = object()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.q = queue.Queue(maxsize=-1)
        self.daemon = True

    def run(self):
        while True:
            task = self.q.get()
            if task == self.EXIT_SENTINEL:
                break
            print(f'Treating task {task}')
            # Pretend to work

    def submit(self, job):
        self.q.put(job)

    def terminate(self):
        self.q.put(self.EXIT_SENTINEL)
        self.join()

worker = Worker()
assert not worker.is_alive()
worker.start()
assert worker.is_alive()
worker.submit(1)
worker.terminate()
assert not worker.is_alive()
```

Here is the output in Python 3.13:

```
$ python rep.py 
Treating task 1
```

If we uncomment the first line in order to use eventlet, this is what we get:

```
$ python rep.py 
Treating task 1
Traceback (most recent call last):
  File "/usr/src/app/rep.py", line 35, in <module>
    assert not worker.is_alive()
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

This is because worker._handle.is_done() still returns False when it should be returning True.

This worked properly in Python 3.12 and started failing in Python 3.13.

**Comment by 4383** [comment]
Hey Cyril,

Thanks for opening this issue.

We will have a look ASAP.

**Comment by 4383** [comment]
I wonder if these [oslo.messaging errors observed on debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1089050) are not the same than the problem described here.

**Comment by 4383** [comment]
@stefanor FYI ^

**Comment by stefanor** [comment]
Doesn't suprise me at all! :)

**Comment by CyrilRoelandteNovance** [comment]
It's definitely the same failure. There are a few different OpenStack projects that use this pattern, so it's going to cause this exact failure multiple times.

**Comment by 4383** [comment]
Sorry, I've problems with my laptop so I cannot launch things like I'd love, can you tell me if you still face the error even when `self.daemon = False`?
I wonder if daemon do not need some additional adjustments.
